### ISSUE TITLE
When eldritch crabs attack player, "Fatal Error" occurs and they get kicked.

### ISSUE THREAD

**Issue by goalie1248** [Azanor/thaumcraft#1409]
Full log: http://paste.atlauncher.com/view/6b087d8d

First kick happens at about line 500

This player has the thorns enchant on their terrasteel armor, the other so far does not have the enchant but does have terrasteel armor.

This only happens when the crabs attack them, not when they attack the crabs.

**Comment by Azanor** [comment]
Well, no log was forthcoming so closing this for now.
