### ISSUE TITLE
Vis net is completly unpredictable.

### ISSUE THREAD

**Issue by Frontrider** [Azanor/thaumcraft#1422]
I have 2 nodes in my network(one has a lot of things, the other is an ignis), one of them (the ignis), just disconnected itself from the main network, and also i could note that it disconnects every time i log into the server i have to break and replace at least half of my network, and its not visual as it was before, vis does not flows anywhere. For me, energised nodes are obsolite for now.
The whole area is being chunk loaded all time, so its can not be the issue

**Comment by tschallacka** [comment]
Maybe that would fix the visnet crash bug too because you now will have a predictable and testable path to tread where you can test if the tile at position x y z actually exists/is loaded.

**Comment by tschallacka** [comment]
btw, you can fix the relays too by just letting it loop through the colours with the wand. the moment the colours change it recalculates where it draws vis from. especially handy for those annoying to place/remove spots.

**Comment by MalkContent** [comment]
Why do they reform their connections? can't you save parent and children of a vis relay? I mean it's exactly what you would have to do when you want to make the connections manually, unless you'd want people to reconnect their relays everytime the chunks unloaded.

**Comment by the-vindicar** [comment]
MalkContent, if my understanding is correct, right now relays are simple
blocks, with linking and drawing vis done by block update logic.
To remember the parent relay, they'd need to be tile entities, which is
slightly more complicated.

2015-01-12 17:50 GMT+03:00 MalkContent <notifications@github.com>:

**Comment by tschallacka** [comment]
They are tileentities.. The way they work is by searching the area around them for a vis powersource. They perform this check each tick when unlinked.
When they find a source crystal they keep requesting parents all the way to the node.

Everytime you unload the chunk and reload the entire network is recalculated and connections may alter.

The parents and vis available are stored in the tileentity. Also the channel colour.

Problems occur when your network spans more than one chunk. If the node unloads or parts of the network, or are slow in loading in time whilst the getParents() loop is running we get an eternal loop issue. The objects are still in memory, but are defacto discarded and waiting for gc. The only check thats performed is != null. Its getparents calling getparents untill infinity.

Hmmh. This answer got a bit longer than expected and im not sure what i answered lol.

--- Oorspronkelijk bericht ---

Van: "the-vindicar" <notifications@github.com>
Verzonden: 13 januari 2015 07:07
Aan: "Azanor/thaumcraft" <thaumcraft@noreply.github.com>
CC: "tschallacka" <mdibbets@outlook.com>
Onderwerp: Re: [thaumcraft] Vis net is completly unpredictable. (#1422)

MalkContent, if my understanding is correct, right now relays are simple
blocks, with linking and drawing vis done by block update logic.
To remember the parent relay, they'd need to be tile entities, which is
slightly more complicated.

2015-01-12 17:50 GMT+03:00 MalkContent <notifications@github.com>:

> Why do they reform their connections? can't you save parent and children
> of a vis relay? I mean it's exactly what you would have to do when you want
> to make the connections manually, unless you'd want people to reconnect
> their relays everytime the chunks unloaded.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azanor/thaumcraft/issues/1422#issuecomment-69580324>.
>

---

**Comment by the-vindicar** [comment]
...pardon the offtopic but how do you know that? I thought TC isn't
completely opensource.

2015-01-13 14:44 GMT+03:00 tschallacka <notifications@github.com>:

**Comment by tschallacka** [comment]
It isnt. The glory of being a former 90's hacker helps :-)

--- Oorspronkelijk bericht ---

Van: "the-vindicar" <notifications@github.com>
Verzonden: 13 januari 2015 14:01
Aan: "Azanor/thaumcraft" <thaumcraft@noreply.github.com>
CC: "tschallacka" <mdibbets@outlook.com>
Onderwerp: Re: [thaumcraft] Vis net is completly unpredictable. (#1422)

...pardon the offtopic but how do you know that? I thought TC isn't
completely opensource.

2015-01-13 14:44 GMT+03:00 tschallacka <notifications@github.com>:

> They are tileentities.. The way they work is by searching the area around
> them for a vis powersource. They perform this check each tick when
> unlinked.
> When they find a source crystal they keep requesting parents all the way
> to the node.
>
> Everytime you unload the chunk and reload the entire network is
> recalculated and connections may alter.
>
> The parents and vis available are stored in the tileentity. Also the
> channel colour.
>
> Problems occur when your network spans more than one chunk. If the node
> unloads or parts of the network, or are slow in loading in time whilst the
> getParents() loop is running we get an eternal loop issue. The objects are
> still in memory, but are defacto discarded and waiting for gc. The only
> check thats performed is != null. Its getparents calling getparents untill
> infinity.
>
> Hmmh. This answer got a bit longer than expected and im not sure what i
> answered lol.
>
> --- Oorspronkelijk bericht ---
>
> Van: "the-vindicar" <notifications@github.com>
> Verzonden: 13 januari 2015 07:07
> Aan: "Azanor/thaumcraft" <thaumcraft@noreply.github.com>
> CC: "tschallacka" <mdibbets@outlook.com>
> Onderwerp: Re: [thaumcraft] Vis net is completly unpredictable. (#1422)
>
> MalkContent, if my understanding is correct, right now relays are simple
> blocks, with linking and drawing vis done by block update logic.
> To remember the parent relay, they'd need to be tile entities, which is
> slightly more complicated.
>
> 2015-01-12 17:50 GMT+03:00 MalkContent <notifications@github.com>:
>
> > Why do they reform their connections? can't you save parent and children
> > of a vis relay? I mean it's exactly what you would have to do when you
> want
> > to make the connections manually, unless you'd want people to reconnect
> > their relays everytime the chunks unloaded.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Azanor/thaumcraft/issues/1422#issuecomment-69580324>.
>
> >
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Azanor/thaumcraft/issues/1422#issuecomment-69699798
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azanor/thaumcraft/issues/1422#issuecomment-69732661>.
>

---

**Comment by Frontrider** [comment]
If you are right, then what you say to the fact, that they reform even if all chunks are being loaded all the time.

**Comment by Azanor** [comment]
I'll add a check to see if the chunk is loaded.

**Comment by MexxPowerHafted** [comment]
The vis relays are still not connecting properly with 4.2.3.4 for me. :(

**Comment by MalkContent** [comment]
Didn't say it would in the changelog, did it? ;P

**Comment by MexxPowerHafted** [comment]
I thought it was fixed because he said he added a check to see whether the chunk is loaded or not.

**Comment by MalkContent** [comment]
"added chunk check to *prevent possible recursion crash* with vis relay network"  
now what part of that says "fixed the connection stuffs"

**Comment by tschallacka** [comment]
The bug he fixed was the server crashing visnet bug.

This is a wholly different bug

--- Oorspronkelijk bericht ---

Van: "MalkContent" <notifications@github.com>
Verzonden: 1 februari 2015 19:06
Aan: "Azanor/thaumcraft" <thaumcraft@noreply.github.com>
CC: "tschallacka" <mdibbets@outlook.com>
Onderwerp: Re: [thaumcraft] Vis net is completly unpredictable. (#1422)

"added chunk check to *prevent possible recursion crash* with vis relay network"
now what part of that says "fixed the connection stuffs"

---

**Comment by Azanor** [comment]
In regards to both this and any other vis-relay related issues:
They are going away in the 1.8 version of Thaumcraft and for the most part I have stopped working on the 1.7.10 version. So, I'm going to close this.
