### ISSUE TITLE
Aspects on Cake

### ISSUE THREAD

**Issue by netmc** [Azanor/thaumcraft#1432]
The auto aspect builder for cake doesn't work. It adds in the metallum aspect from the 3 buckets of milk even though you get the buckets back when making the cake recipe.  Cake ends up with 18 metallum on it.  This could be used with the iron duplication crucible recipe to easily dupe iron from a cake factory.   I also tested it in a creative world with just thaumcraft, and still had the same aspects (minus the gulla from forbidden magic.)

![2014-12-28_01 20 35](https://cloud.githubusercontent.com/assets/10328528/5563322/cfa29914-8e2f-11e4-81cf-8015bfef0f5a.png)
![2014-12-28_01 30 59](https://cloud.githubusercontent.com/assets/10328528/5563343/5ac7bc1c-8e31-11e4-838b-b7c8c5ee89a4.png)

**Comment by MalkContent** [comment]
Damn... 18 f-ing iron... Before it was "teehee, i can make metal from cake", now it's "I AM THE IRON LORD, BAKER OF CAKES!"  
Maybe substract the essentia of crafting ingredients container items in recipes? Just see that the crafting ingredient's aspects minus the container item's aspects don't go negative.

**Comment by elan-morin** [comment]
I can confirm that the same thing happens with other mods. I'm using Pam's Harvestcraft and it has a lot of food recipes that use some ingredients and a pan which you get back after crafting. The results have metallum in them, because that's what the pan is made of.
