### ISSUE TITLE
lightning effect randomly appears on energized nodes

### ISSUE THREAD

**Issue by avuong2962** [Azanor/thaumcraft#1434]
The electrical effect seen when creating an energized node can sometimes randomly occur with no actual effects on the node. The node is not actually being destroyed or converted. The effect continues when the node is manually destroyed.
![2014-12-28_11 34 24](https://cloud.githubusercontent.com/assets/10332527/5564595/d3909e48-8e86-11e4-9dc4-084107d0d8b1.png)

![2014-12-28_11 34 39](https://cloud.githubusercontent.com/assets/10332527/5564598/ec742a88-8e86-11e4-986e-f2530b7bdda2.png)

-Yes, the node transducer and stabilizer were active.
-There were vis relays running from the node, this seemed to cause the effect. Sometimes, breaking/replacing the relay would fix the problem.

**Comment by avuong2962** [comment]
This might be related to #1422, since it is sometimes fixed by breaking and replacing vis relays.

**Comment by Azanor** [comment]
In regards to both this and any other vis-relay related issues:
They are going away in the 1.8 version of Thaumcraft and for the most part I have stopped working on the 1.7.10 version. So, I'm going to close this.
