### ISSUE TITLE
Vis relay beam rendering inconsistent

### ISSUE THREAD

**Issue by bshelden** [Azanor/thaumcraft#1437]
The image describes this better than I can.

Note that someties I see all beams, sometimes none.  But pictured is the most common.
To get this shot, I at first had no beams.  I forced a reload by linking ot the nether and back, and took this screenshot.
![2014-12-28_12 35 26](https://cloud.githubusercontent.com/assets/464894/5564925/a90d1d74-8e8e-11e4-9fce-16a157afe345.png)

**Comment by chrisbecke** [comment]
As per #1563 this issue seems to occur when vis relays are at maximum range. It smalls like a floating point comparison error where the client thinks the relays are 0.0000...001 too far apart to be connected.

**Comment by Azanor** [comment]
In regards to both this and any other vis-relay related issues:
They are going away in the 1.8 version of Thaumcraft and for the most part I have stopped working on the 1.7.10 version. So, I'm going to close this.
