### ISSUE TITLE
[Request] Hook for dungeon chest generation

### ISSUE THREAD

**Issue by ReikaKalseki** [Azanor/thaumcraft#1447]
I would like to add a bit of extra loot (specifically 1-3 ChromatiCraft info items per structure) to the barrow hills chests (and not the source chest types it pulls from). Would you consider adding a custom Forge event to the ThaumCraft API (probably containing a `Collection<ItemStack>` to be added to the chest, as well as data of which chest (and thus loot table) the event corresponds to, and optionally other things like world, x, y, z for biome/dimension/etc variability) and firing it during the generation phase (around lines 2534, 2543, and 2555 of WorldGenMound)?

**Comment by chrisbecke** [comment]
My personal experience is that, in some games, even with standard terrain generation, I don't find any barrow hills at all due to map seed / rng generating plains bioms infrequently, small or hilly. Barrow Dens only seem to generate if the terrain is quite flatish.

**Comment by Azanor** [comment]
I might add a hook in the future, but I have no plans to do it right now.

**Comment by ReikaKalseki** [comment]
If you ever decide to do so, you can look to ChromatiCraft for a sample implementation:
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/API/Event/StructureChestPopulationEvent.java#L22
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/World/DungeonGenerator.java#L301
