### ISSUE TITLE
Wooden chests providing incorect essentia

### ISSUE THREAD

**Issue by JasonMcRay** [Azanor/thaumcraft#1453]
After update of thaumcraft (from 4.2.1.4 -> 4.2.2.1) Wooden chests have metallum and lucrum aspect associated with them. in past I remember it had only Vacuos and Arbor.

This can be effectively used with a normal tree farm to get kind of infinite iron, silver, electrum and gold with the power of Metal Transmutation. I know its not free, but having the tree farm is not hard to get, and some players of my modpack (InfiTech 2) are bit concerned due to balance reasons :)

Thanks for looking into this and for any response

**Comment by Azanor** [comment]
You must have a mod that changes the recipes or aspects associated with it - the aspects are still correct in vanilla TC.

**Comment by JasonMcRay** [comment]
I have found that Refined Relocation is adding reversable recipe Sorting Wooden chest -> Wooden chest. The sorting one is made with 2 gold ingots. Might this be the cause?
