### ISSUE TITLE
Request the REPOST license

### ISSUE THREAD

**Issue by TehporP** [Azanor/thaumcraft#1456]
Hey @Azanor 
I am a big fan of your awesome mod,thus,I would requst a license form you to REPOST license
this mod to the almost biggest China minecraft forum(we called it MCBBS)
REPOST means:
1.Clarified origin auhor name which is you(I just a "reposter")
2.Clarified origin URL link could reach to ThaumCraft thread directly
3.Obey EULA with no conditions
4.Never re-compile/re-package/re-distribute this mod(Although you didn't open source)
5.A free/ad-free Chinese net-disk download link to boost download speed(No cent could be earn I promis)

**Comment by Azanor** [comment]
Isn't this sort of thing already covered under the modpack permissions?

**Comment by TehporP** [comment]
humm What his name？

**Comment by TehporP** [comment]
@Azanor Well ,I just need YOU give the repost permission to me, Because our forum have a foolish rule,if we dont have author‘s permission,we CANNOT post ANY mod.So I just need you say :You can repost my mod is ok

**Comment by Azanor** [comment]
In that case: Sure, you have my permission.

**Comment by TehporP** [comment]
Thanks！：)
