### ISSUE TITLE
Crimson Knight make Crimson Cleric to despawn

### ISSUE THREAD

**Issue by vemntss** [Azanor/thaumcraft#1458]
crimson knight tend to move near the clerics, when they moves sometimes makes the cimson clerics to despawn (the clerics taking away from the node) when the chunks are unloaded.

sorry if i wrote this wrong, i'm not good at english.

**Comment by blockbreaker1361** [comment]
What I don't like is how the guards can move the clerics. What I suggest for Azanor is for the "ritual area" to be guarded by some sort of barrier that can only be lowered once the guards are killed. This would make for a more realistic scenario in getting to the altar to set up the portal.
