### ISSUE TITLE
Client Crash when attempting to craft Botania Item in Arcane Worktable

### ISSUE THREAD

**Issue by kingofrunes** [Azanor/thaumcraft#1459]
I'm running into a client side crash whenever I put a Mana Blaster with a Flash Lens from the Botania mod together in the Arcane Worktable.

Here is the crash report of what happens when I try and take the finished product out: http://pastebin.com/1VBAKf4S

Here's a visual representation of the problem for replication purposes:
http://puu.sh/dZFZp/06b9944137.png

**Comment by Azanor** [comment]
You might want to report it to Vazkii. I am picking up the item as having a container item, but the actual container item is null. I'll add a null check on my side, but it really shouldn't be happening.

**Comment by Vazkii** [comment]
It's on my side, this check should reflect if the item has a lens or not: https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/ItemManaGun.java#L143
