### ISSUE TITLE
[Client crash] Warded blocks infinite recursion

### ISSUE THREAD

**Issue by KaseiFR** [Azanor/thaumcraft#1462]
Hi,

Sometimes (happened twice for now), when I'm connecting to my server, I get a client crash with that report (cut the recursive part): http://pastebin.com/D6gvNPg1
At the logout, I was near my base, with some warded blocks underground, but none within line of see.
I manage to login by altering my position and login in away from my base. Once logged in, I didn't encountered that problem again.
I've always used the 4.2.2 version.

**Comment by Biochao** [comment]
This is happening on my modpack for singleplayer clients as well. The world was created in 4.2.1.4 and has large amounts of warded blocks.

Crash (Singleplayer): http://pastebin.com/JkJAhMJj
Crash (Non-integrated multiplayer server)  : http://pastebin.com/Let35SNB
