### ISSUE TITLE
Issues with Silk Touch Upgrade for Excavation Focus

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft#1463]
~~The displayed Cost of an excavation focus with silk touch has "ullLucrum" as an additional cost next to terra vis. I suppose something went a bit wrong there. :3~~

TC 4.2.2.1, Forge 1277

Edit:
I'll tag on that the Silk Touch Upgrade is possible even after already choosing Treasure, which makes no sense, since Silk Touch virtually overrides Treasure/Fortune.  
I'll also throw into the room that Treasure 3 costing 3 of 5 slots of the Excavation Focus as compared to 1 for silk touch might be unbalanced. If you build a refining station that breaks stuff like Red Stone Ore with an arcane bore and a fortune pick (which is not super complicated or expensive), Silk Touch is the definitive way to go. Mining costs less inventory space and is faster/cheaper. I present a problem with no solution :3 Nobody is gonna get hurt if it stays the way it is, though.

Edit 2: Changed issue to tagged on issue

**Comment by forsaken1111** [comment]
#1427 Related?

**Comment by MalkContent** [comment]
Rats. I limited my search on excavation and silk touch. Derp.
