### ISSUE TITLE
Energizing Compound Aspects calculation issue

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft#1470]
In the interest of science we looked at growing compound nodes for energization and came across an error of some sort. Compound aspects break down into 1 point of each contained primal for the purposes of energizing. The resulting CV is sqrt the max vis of each primal, rounded down, for normal nodes. So 9 max vis becomes 3 CV, 16 -> 4, 25 -> 5, 36 -> 6 and so on. However compound aspects require one additional point to go over a new threshold, so 10->3, 17->4, 26->5 (maximum tested was for 100->10). Looked at the code and have no idea why that is. It isn't game breaking at all or anything, it just doesn't look like it's intended and now it's a mystery that demands solving by on the fly debugging :D  
PS: not really demanding ;P

**Comment by Azanor** [comment]
I'm calling this a feature.
