### ISSUE TITLE
Sun-Scorned+Regen Crash

### ISSUE THREAD

**Issue by zlyfire** [Azanor/thaumcraft#1472]
Whenever I get the sun-scorned warp effect, I somehow get regen(I have no clue why), and then I promptly crash. Openeye keeps sending a report to its servers, but the issue is apparently not due to thaumcraft, even though it exclusively happens when I'm under the sun-scorned effect.

http://openeye.openmods.info/crashes/f66dddf5e6709f3bc7de1011e476d7d7

**Comment by forsaken1111** [comment]
Reported before: #1402 #1346

Also it helps if you tell what version you are using

**Comment by zlyfire** [comment]
I was using Thaumcraft 4.2.2.0 on Forge 10.13.2.1277
I had also believed I was on the most recent thaumcraft, but now I see that I am not.
