### ISSUE TITLE
Alchemy golems don't work well with buffers

### ISSUE THREAD

**Issue by swilbur** [Azanor/thaumcraft#1481]
I have an alchemy golem set up to take essentia from a buffer, and it's waiting until the buffer has at least 4 of a particular aspect before picking up any of it. (it's a wood golem, so it can carry 4 at a time)  Unfortunately, if there are multiple types of essentia draining into it at once, the buffer can be full and not have 4 of any type. (e.g. 3 Arbor, 3 Ordo and 2 Praecantatio) In this case, the buffer won't accept any more essentia and the golem won't pick any up, clogging the system.  Using a straw golem is a workaround, but it works much more slowly.

**Comment by swilbur** [comment]
More information: this bug only occurs when there are multiple types of essentia in the buffer, but not enough of any of them to fill the golem's inventory.

**Comment by Azanor** [comment]
Golems aren't really intended to work with buffers and I'm actually surprised it is possible in the first place. Still this bug might occur with other stuff so I will take a look.

**Comment by Azanor** [comment]
Turns out it is a "feature" with the buffers themselves. I will fix this for the next version.
