### ISSUE TITLE
Sword of Zephyr with Repair

### ISSUE THREAD

**Issue by commonsensei** [Azanor/thaumcraft#1485]
The repair enchantment causes the sword to bounce when the durability is repaired. This hiccup also causes the zephyr's right-click ability to pause. A solution could be that the right-click ability lasts for a small duration to outlast the hiccup.

**Comment by MalkContent** [comment]
how about suspending the repair enchantment when a tool/weapon is in use? no nbt updates -> no hiccup

**Comment by chrisbecke** [comment]
This is annoying as hell.
I'd support the repair enchantment being delayed to not kick in while the sword is being used to prevent this. As it stands, Repair I is soo fast on a SotZ compared to how fast its possible to damage the sword that this would not really effect the swords use.

**Comment by commonsensei** [comment]
Is there no way for repair to not cause the hiccup? It is unsightly seeing tools bob up and down constantly. Data value decrease -> no bounce; increase -> bounce?

**Comment by MalkContent** [comment]
huh... that's actually an interesting question, how tools take damage during use without the refresh bop

**Comment by the-vindicar** [comment]
I second this issue, Repair II SoZ is actually harder to use.

**Comment by TheMadmanofChaos** [comment]
Bit of a vanilla issue actually. The code treats the change in meta data up as a it becoming a new item, so that is why it bobs and the item name comes up. Only way to really fix is to go with what MalkContent said, and just have it not repair in hand. This is by no means a perfect salutation, as it adds the issue of risking tool breakage even when you have plenty of vis.

**Comment by the-vindicar** [comment]
But it makes some sense - active arcane energies of the weapon destabilize repair enchantment, preventing it from work. Plus it'd also make Unbreakable enchant useful again.

**Comment by Azanor** [comment]
I hate that vanilla bobbing thing and I wish there was a way MC would know the difference between the item actually changing and just the meta changing.

**Comment by Azanor** [comment]
Anyway, it isn't actually only repair causing the problem - the sword itself takes damage very second while you use its right-click ability so disabling it for repair won't make a difference.

**Comment by Azanor** [comment]
Either way, closing this since it isn't really a bug, but I will see if there is anything I can do for the 1.8 version.

**Comment by chrisbecke** [comment]
So inhibiting repair while the rmb function is used would help SMP players? :P
