### ISSUE TITLE
Thaumonmicon attempts to create research note but nothing appears in inventory and paper isn't used up.

### ISSUE THREAD

**Issue by joshmackey** [Azanor/thaumcraft#1486]
For whatever reason, this ONLY happens with my account. Others on my server can use it just fine and it also works fine in single player.

I've also tried wiping the playerdata .dat file and trying again, but no change.

**Comment by Azanor** [comment]
Unfortunately this is very little information to go on and it is the first time I've seen an error like this reported. You do have scribing tools in your inventory?

**Comment by joshmackey** [comment]
I have since updated to the latest version and all is well.

At the time, yes I did. The book told me the research note was added to my inventory but nothing ever was.

**Comment by Azanor** [comment]
Strange, but glad to hear it is working now :)
