### ISSUE TITLE
Disable/add option to disable logging of champion monster deaths

### ISSUE THREAD

**Issue by Cobra1117** [Azanor/thaumcraft#1489]
Although the new champion monsters are really cool, their deaths get outputted to the chat even if they are killed by a mob farm. My chat window is constantly being filled with things like:
Infested Zombie fell out of the world
Bold Zombie was slain by [Minecraft]
Armored Enderman was slain by [CoFH]
etc.
It would be nice if (A) it only outputted to chat when a champion was killed by a real player and (B) there was an option to turn it off altogether.

Tested with:
Forge: 10.13.2.1277
Thaumcraft: 4.2.3.0

**Comment by Azanor** [comment]
This is really strange - they are just normal mobs for the most. Nor do I see their death messages output to the console. Do you have any other mods installed?

**Comment by Mengmoshu** [comment]
CoFHcore has a setting B:EnableGenericDeathMessage=true which might be posting the messages to chat.
It looks like this in the config:

    # Set to true to display death messages for any named entity.
    B:EnableGenericDeathMessage=true

**Comment by Cobra1117** [comment]
@Mengmoshu is correct--that was the problem. I've disabled it for now. I'm not too familiar with Team CoFH's API, but if there is a hook to disable those messages just for Thaumcraft champions you may want to call it, since the default setting for that is "true". (Obviously not high-priority, since there's a work-around! :smile: )

**Comment by Mengmoshu** [comment]
Glad to help. Gives me the warm fuzzies.
