### ISSUE TITLE
Arcane Lamps can chunkload

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft#1492]
I performed this investigation trying to diagnose some performance issues with a server.

Thaumcraft 4.2.1.4
and a subset of mods from the Direwolf20 1.0.3 pack for MC 1.7.10
Using Opis' map view set to Loaded Chunks to view the chunks Opis thinks are loaded.

First, I created a new world, and moved ~100m away from spawn.
I verified that only the 12x12 spawn chunks, and the chunks around my character remained loaded.

Second, I placed ~4 arcane lamps. It was daytime but there were some caves so I assumed some glimmering lights had been created when I moved away (again, ~100m).
While the chunks were unloading I noticed a brief period in which the area around the "lit" chunks remained loaded, but after a few minutes only the spawn chunks and the area around my character still showed as loaded.

Then I placed 20 arcane lamps in a grid to light up an area and waited for night. The opis report eventually showed 1.8k glimmering light TEs.
I them moved away and watched the opis loaded chunks view. The center of the lit area did not unload. After a minute, the loaded area actually expanded by a few chunks.
waiting over an hour, and the opis view shows all the chunks with arcane lamps and lit by glimmering lights remaining loaded (in addition to the area around my character and spawn).

**Comment by Azanor** [comment]
While I cannot argue with your findings, this has to be a forge or vanilla bug of some kind - neither the lamps nor the glimmers have any sort of chunkloading code associated with them. I wonder if the sheer number of ticking tile entities is somehow keeping the chunks alive.

**Comment by chrisbecke** [comment]
I was going to title the report "Arcane lamps inadvertently chunkload" - It was never my suspicion that this behaviour was in any way intentional.
Given that there seems to be some critical number of arcane lamps to cause this is does seem to be an unintentional emergent behaviour of "too many tile entities".

**Comment by Azanor** [comment]
I'm in the process of rewriting the glimmers of light to not be tile entities and just light blocks.

**Comment by chrisbecke** [comment]
Well, wrt to the original perf issue i was investigating, TC 4.2.3.2 did remove 12k tile entities, the chunks are no longer persisting, and SSP fps is back to ~100 from 5.
