### ISSUE TITLE
cant get the research expertis note 

### ISSUE THREAD

**Issue by shockwave9898** [Azanor/thaumcraft#1496]
Hi, i played on my crackpack private world and when i had done my blood magic i was going for thaumcraft. 
But when i was going to get the expertis research I couldnt get it, 
It says i have the expertis but i got no note, 
i got the paper  and the scribing tools but cant get it, tried several times
I went to the config file and change the -1 to both 0 and 1 to test but i still cant get it.
looked everywhere for help but cant find anything. 
pls help 
![2015-01-08_15 55 31](https://cloud.githubusercontent.com/assets/10451021/5664214/e2a7fe1e-974e-11e4-868d-d41f4050a0b9.png)

![2015-01-08_15 55 26](https://cloud.githubusercontent.com/assets/10451021/5664221/e9016f5c-974e-11e4-9db5-c4a58fdb5e8a.png)

**Comment by MalkContent** [comment]
that looks like you already researched it. which means that you now can't get any more research notes for it.

**Comment by shockwave9898** [comment]
so i must do a new world to get it ?

**Comment by MalkContent** [comment]
that or delete your players thaumcraft research file. why do you need more research notes if you already researched it?

**Comment by shockwave9898** [comment]
i didnt, i clicked but i never gout the research note i my hand, is it important to get the research notes or can i just play on and skiping them ?

**Comment by shockwave9898** [comment]
find a link how to reset the research and it did work. ty for your help. 
i really appriciate it ty
