### ISSUE TITLE
Incorrect essentia for chests, bowls, oak wood

### ISSUE THREAD

**Issue by elan-morin** [Azanor/thaumcraft#1499]
I've encountered the same issue as #1453 and #1420. I know this isn't because of Thaumcraft, but I found the mod causing the problem, so I thought I'd leave a comment for those affected ( @JasonMcRay @akvgergo @the-vindex ) and anyone else looking for a solution in the future, so please don't delete this comment, just lock it.

The mod is Big Reactors, in case you want to remove it or watch out for updates. I'll notify the developer right away.

**Comment by elan-morin** [comment]
Correction - Big Reactors are not causing the problem, it is some other mod linking BR and TC. Check the BR thread above for more information. I apologize to anyone concerned.

**Comment by elan-morin** [comment]
After some testing I finally identified the source of the problem - it's Thermal Expansion. So anyone who has these three mods at the same time - Thaumcraft, Big Reactors and Thermal Expansion - will probably experience this issue.

For anyone reading this - if you have these mods, could you verify it ?

**Comment by Barhandar** [comment]
>For anyone reading this - if you have these mods, could you verify it ?

I'm getting some zero-aspect items and blocks, for example furnaces and levers. Chests, bowls, and oakwood are fine, so I suspect some of the 200+ mods I use affect the issue as well.

**Comment by chrisbecke** [comment]
I doubt its thermal expansion. I mean, something about the mod combo is causing TCs essentia scanning to derp out, but none of the other mods implicated so far change recipes for things like oak wood.

**Comment by Azanor** [comment]
I tried to fix this on my end, but the "fix" unfortunately makes my mod not work with anything that adds copper or silver ore. Looks like this is not something I can fix on my end. It will have to be fixed on the TE side.

**Comment by dredhorse** [comment]
So will getting the right version of TE just fix the issue or do I need to do something specific?

**Comment by elan-morin** [comment]
@dredhorse 
I haven't updated my mods for some time, and this was posted two months ago, so I can only tell you what worked two months ago - having Thermal Expansion version 4.0.0 B6 and no higher.

However, all of the mods in question have been updated since then, so I'd recommend getting the latest Thaumcraft, Thermal Expansion and Big Reactors if you have this problem. Only if it doesn't solve the problem get the TE 4.0.0B6.
