### ISSUE TITLE
Goggles of revealing auto repair with no repair enchantment

### ISSUE THREAD

**Issue by dmb1881** [Azanor/thaumcraft#1500]
Thaumcraft Version: 4.2.3.0        Forge Version: 10.13.2.1277

Hi im playing on this thaumcraft server (Only thaumcraft, and its vanilla) and I enchanted my goggles of revealing and I got protectiong IV and thorns II, When an creeper explodes or a skeleton shoots me in the head my goggles take damage but they will replenish durability. All of my other armor takes durability though. I have no idea if this is just a visual bug where my goggles aren't really taking damage.

I have a few mods for myself installed:
Armor Status,
Status Effect,
Code Chicken Core,
Dynamic Map,
FastCraft,
InventoryTweaks,
Nei,
Thebombzenapi,
And Waila.

**Comment by dmb1881** [comment]
Sorry for the repost. I read the posting thread rules thingy after I posted, and had to make some edits.

**Comment by Azanor** [comment]
I cannot duplicate this at all. You might have an invalid enchantment ID causing TC to think one of the goggles enchants is repair. Check you config file and the repair enchantment id.

**Comment by dmb1881** [comment]
It is the default enchantment, 151, I may have a solution to fixing it though, I am just going to delete my config file, because I may have some mod conflict, I play around with lots of mods.

**Comment by dmb1881** [comment]
It seems to be still doing it after I did that, but I will keep looking for what may be causing this to happen

**Comment by mSh4ke** [comment]
Same problem here , it also applies to any Thaumcraft items. Also when i try to put item with such an enchant into an anvil , my client crashes.

**Comment by ThePB** [comment]
Linking this reddit post here, as it seems pertinent.
http://www.reddit.com/r/Thaumcraft/comments/2shl56/artifice_tools_not_displaying_enchantments/
It seems that while the item is actually enchanted, it's just the "Repair X" tag that it's not showing, at least in that case. Since i'm not the one suffering from the problem, i can't actually give more infos on the system and configuration it happens on.

**Comment by Azanor** [comment]
Yeah it is technically impossible for the goggles to just repair themselves - either there is some kind of hidden enchantment or it is some other mod doing the repairing.

**Comment by 6269329** [comment]
All of these problems are caused by messed up enchantment Id's, the server and the client have different ids for the repair enchant which causes the repair enchant to work but not be seen on the item and crashes the client when the item is placed in an anvil. It is most likely that the server of client didn't allow the config file to be refreshed when switching versions. All that is needed to fix the problem is to change the client id to match the server id or have both parties delete their config files and allow thaumcraft to re make it.

**Comment by mSh4ke** [comment]
Actually , that was the first thing , i thought of . However, since i use default Thaumcraft cfg both server and client have default id for enchants , wich are the same (150 for haste and 151 for repair).

**Comment by 6269329** [comment]
You own the server?

**Comment by mSh4ke** [comment]
I doubt it will help , since we decided to create a new world for new thaumcraft update . Will try anyway , and post if it helps or not.

**Comment by tschallacka** [comment]
@mSh4ke another user on my server had the same issue, changing the id s in his config file helped. When your servers stems from the 4.2.0/1 era it has different enchant id s than people who start out in the 4.2.3 version. What numbers(@6269329) says is the solution, or you simply delete the thaumcraft.cfg file in minecraftserver/config/Thaumcraft.cfg

that will make sure you get all fresh new defaults.

**Comment by 6269329** [comment]
Just deleting it wont work if the server ids are still the old ones though(server updated to 4.2.3.0, but didn't update the config file)

**Comment by tschallacka** [comment]
I was referencing to the server deleting the cfg file.

--- Oorspronkelijk bericht ---

Van: "Numbers" <notifications@github.com>
Verzonden: 17 januari 2015 00:59
Aan: "Azanor/thaumcraft" <thaumcraft@noreply.github.com>
CC: "tschallacka" <mdibbets@outlook.com>
Onderwerp: Re: [thaumcraft] Goggles of revealing auto repair with no repair enchantment (#1500)

Just deleting it wont work if the server ids are still the old ones though(server updated to 4.2.3.0, but didn't update the config file)

---

**Comment by dmb1881** [comment]
Sorry I haven't replied to any messages. No I do not own the server. And I have to say I have to agree with 6269329 what he said makes sense, with the enchant id's not being the same. But the only thing I think that is weird is the fact I used a vanilla enchanting table.

**Comment by dmb1881** [comment]
It is simply just that the repair enchant isn't showing. I put repair on my harness and it isn't showing
