### ISSUE TITLE
Mana Beans Render incorrectly from certain Angles

### ISSUE THREAD

**Issue by Xirema** [Azanor/thaumcraft#1502]
I've noticed ever since the most recent content updates (4.2.2.1 & 4.2.3.0) Mana beans can lose their color if viewed from the wrong angle. This wasn't happening in 4.2.1.x.

The screenshots were taken with a resource pack in place, but I did verify that the phenomenon was happening under the default textures as well.

For color check purposes, the beans I was looking at were Potentia (the light cyan/light blue beans).

Correct Color:
![2015-01-10_15 37 36](https://cloud.githubusercontent.com/assets/1447761/5693385/13b9ecaa-98e0-11e4-938b-de91979c876f.png)

Slightly different angle with Wrong Color:
![2015-01-10_15 37 44](https://cloud.githubusercontent.com/assets/1447761/5693714/a90a2c6a-98f0-11e4-9739-6620b8efcb82.png)

Correct Color from a different viewpoint:
![2015-01-10_15 38 18](https://cloud.githubusercontent.com/assets/1447761/5693716/bd0d096c-98f0-11e4-8310-3692dc93cba9.png)

Wrong color from an offset of the different viewpoint:
![2015-01-10_15 38 13](https://cloud.githubusercontent.com/assets/1447761/5693718/c6db8e8c-98f0-11e4-87a7-3f565edba8e5.png)

Correct Color w/out Texture Pack:
![2015-01-10_17 50 08](https://cloud.githubusercontent.com/assets/1447761/5693723/2e8a4fb4-98f1-11e4-842f-61def52d361d.png)

Wrong Color w/out Texture Pack (Notice that some appear correct but most appear incorrect):
![2015-01-10_17 50 14](https://cloud.githubusercontent.com/assets/1447761/5693725/3c5efe50-98f1-11e4-8fcb-1360fdfe1659.png)

**Comment by Azanor** [comment]
This could actually be related to an advanced alchemical furnace rendering bug. Is there one of those in the direction you are looking?

**Comment by Xirema** [comment]
Hmm. You might be right.

In Image #2, the furnace is off-screen, but just barely, on the upper-left corner.

In Image#4, the minimap is blocking the furnace but you can kind of see it around the edges.

In Image#6, the minimap is again blocking the furnace, but it is indeed there.

The running trend for images #1, #3, and #5 is that the furnace is well off the screen.

**Comment by Azanor** [comment]
I thought as much - this bug should be fixed in the next version
