### ISSUE TITLE
Shielding broken unusually quickly on server

### ISSUE THREAD

**Issue by astronomicalphenomena** [Azanor/thaumcraft#1506]
This bug only appears on Cauldron server.
When a player wearing any RunicArmor and get runic shielding, he won't get knock-back, and any monster that can act close combat will attack player rapidly with no interval, and the shielding will decrease directly until the shielding is broken. (By the way, the attack that break the shielding won't count armor and hurt the player as he wears no armor.) Spider won't do so because they have to pounce before attack, but zombie will act combat with no interval. Once the shielding is broken and player can get knock-back again, monster won't attack so quick. This won't happen on local game, zombies will attack in normal interval. I hadn't test it on pure Forge Server, because I'm still confusing about how to make a forge server run.

**Comment by Ulysses2** [comment]
See issue #1326. Thaumcraft does not officially support Cauldron, so if you want this fixed you'll need to contact the Cauldron developers.

**Comment by Azanor** [comment]
Yup, unfortunate but true. Normally mobs have an internal timer between their attacks, but for some reason cauldron breaks this - nothing much I can do about that.
