### ISSUE TITLE
Armor chestplates not equivalent to diamond protection 

### ISSUE THREAD

**Issue by Terpo** [Azanor/thaumcraft#1508]
Void Thaumaturge Robe, Void Chestplate and Thaumium Fortress Cuirass seem to have less protection than the Diamond Chestplate.

I am not sure if the Void Chestplate and Thaumaturges Robe should have diamond protection but the Thaumium Fortress Armor is mentioned as diamond in the Thaumonomicon.

Diamond Chestplate: 4 armor points
Thaumcraft chestplates: 3.5 armor points

Thaumcraft version: 4.2.3.1

**Comment by Azanor** [comment]
If you read the description you will see that the more pieces of Thaumium fortress you wear, the higher the armor bonus - it is a hidden bonus and not reflected on the tooltips.
The other armor values are correct since they have significant other bonuses.
