### ISSUE TITLE
Display inconsistency for Infusion Recipe whose components contain a block after an item

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft#1511]
So. When you create an infusion recipe, any blocks in the components (the not center part of the recipe) which are ordered in after an item will be shaded, which is a break with their usual display in the thaumonomicon.  
I believe this is because of minecraft's itemRenderer, which, at the end of rendering an actual item (as opposed to a block item), enables GL11.GL_LIGHTING.
I believe a workaround would be to insert glPushAttrib(GL11.GL_LIGHTING) and glPopAttrib(GL11.GL_LIGHTING) inside of thaumcraft.client.gui.GuiResearchRecipe.drawInfusionPage(...) at line ~1395 inside of the for loop (not sure how you feel about me just posting the code). Alternatively of course just insert a new glDisable(GL11.GL_LIGHTNING).

**Comment by MalkContent** [comment]
Sorry for the delay, here's a small pic to demonstrate what I mean:
sinister-lore.de/mcpics/tc_infusionPageLighting.png

I also encountered another not purely cosmetic issue with the infusion pages. I have a case where both displayed pages contain an array of recipes, which are not of the same length. When they are cycled through, BOTH pages are reset to display their first recipe, when the page with the shorter array reaches the end of its cycle.
You can see for yourself in my mini addon. The research in question is "Stone Infusion", under Artifice, behind Arcane Bore.

sinister-lore.de/downloads/CosmeticTurgery-1.7.10-0.2.jar

**Comment by Azanor** [comment]
Strange, I don't experience either of these issues. 
For example, in the infusion enchantment recipe entries I have pages of different recipes with varying lengths of recipes it cycles through on the same page.

**Comment by Azanor** [comment]
Actually, I managed to duplicate the first issue now. I'll take a look at it.

**Comment by MalkContent** [comment]
Okay. But the infusion enchantment recipe entries are kinda different, using different functions to draw. I think I found the issue. You have a single variable "cycle" used for cycling recipes/components, which get's reset to zero when it's out of bounds in drawInfusionPage, thereby resetting it for the other page, too. I propose retrieving the array object by  
tr = ((Object[])(Object[])pageParm.recipe)[cycle%((Object[])(Object[])pageParm.recipe).length];  
rather than with the current try/catch + reset.
