### ISSUE TITLE
Spined Mobs vs Entropy guard golems == mega lag

### ISSUE THREAD

**Issue by tschallacka** [Azanor/thaumcraft#1513]
When a guard golem with entropy upgrade hits a champion mob that is spined they enter in a thorns loop.

The golem will hit zombie. The thorns of the zombie will hit golem. The thorns of golem will hit zombie and it keeps going until one gives.

Please add in a check if damage received comes from thorns and that the golems dont fire a new thorns.

For your study and edification
http://thaumcraft.duckdns.org/downloads/crashlog.txt

**Comment by Cobra1117** [comment]
Related: Having a bug with the same stack trace, but it's causing a server-size crash for me. Relevant versions:
Forge: 10.13.2.1277
Thaumcraft: 4.2.3.2

Crashlog: http://pastebin.com/0LcbauT4
Also, since the stack trace in the log was slightly different: http://pastebin.com/Ls2KfyCW

**Comment by tschallacka** [comment]
Heh. My server refused to crash. It just kept chugging along. All the players could do was chat. Nothing more, till the zombie died.

Took me a while to figure out what excactly caused the loop heh. Then we all got mad at the infamous bruce(name of the golem)

I think it can be easely solved by adding a tick delay before the thorns damage is given back to the opponent. That way their on entity hurt update doesnt cause the thorns to loop.

--- Oorspronkelijk bericht ---

Van: "Cobra1117" <notifications@github.com>
Verzonden: 15 januari 2015 03:20
Aan: "Azanor/thaumcraft" <thaumcraft@noreply.github.com>
CC: "tschallacka" <mdibbets@outlook.com>
Onderwerp: Re: [thaumcraft] Spined Mobs vs Entropy guard golems == mega lag (#1513)

Related: Having a bug with the same stack trace, but it's causing a server-size crash for me. Relevant versions:
Forge: 10.13.2.1277
Thaumcraft: 4.2.3.2

Crashlog: http://pastebin.com/0LcbauT4
Also, since the stack trace in the log was slightly different: http://pastebin.com/Ls2KfyCW


---
