### ISSUE TITLE
Warded Glass cannot be picked up if used on Spectral blocks (Blood Magic).

### ISSUE THREAD

**Issue by OJwithC** [Azanor/thaumcraft#1515]
In Blood Magic, there is a ritual (and a sigil) that creates Spectral blocks. If you right click a block on them, the spectral block is replaced by the block in your hand. When I used Warded Glass on it, I could not pick it back up with my wand.

**Comment by Azanor** [comment]
When you place warded glass it gets linked to your player, but I guess spectral blocks somehow bypasses that. Unfortunately nothing much I can do to prevent that from my side - I don't have control over other mods. You might want to report this to the Blood Magic dev.
