### ISSUE TITLE
Eldritch Guardian drop Ethereal Essence with no appropriate nbt data

### ISSUE THREAD

**Issue by gaymode** [Azanor/thaumcraft#1516]
Thaumcraft Version: 4.2.3.2

When I killed a creative-spawned Eldritch Guardian, it dropped some Ethereal Essence.
Some of them have correct nbt data registered. However, it will sometimes drop some unregistered Ethereal Essence. Those essences will change their colour like the one in NEI.

I have tried to regenerate the config of thaumcraft. But it did not help

![2015-01-15_15 16 27](https://cloud.githubusercontent.com/assets/6838982/5753810/3f28283c-9cca-11e4-85be-b70c88bad757.png)

**Comment by MalkContent** [comment]
huh. i thought that was a feature :|
