### ISSUE TITLE
Alchemical  Furnace can no longer break down some items

### ISSUE THREAD

**Issue by Euius** [Azanor/thaumcraft#1517]
The vanilla Diamond chest (56 total aspects) can not be broken down in an alchemical furnace. This is likely due to the recent re-calculation of the aspects of items done in  4.2.2.0

First noticed in 4.2.3.0, but updated to 4.2.3.2 to become current and is still present.

**Comment by Azanor** [comment]
Not a bug - the alchemical furnace has a limit as to what it can break down - items with too many aspects cannot be broken down.

**Comment by MentalMouse** [comment]
Also, a "Diamond chest" with 56 total aspects is certainly not vanilla.

**Comment by Euius** [comment]
When one hears "vanilla diamond chest", one should think of "diamond chestplate" not "a modded chest that uses diamonds"

**Comment by forsaken1111** [comment]
Perhaps one should be more precise when explaining rather than expecting others to read one's mind.
