### ISSUE TITLE
Unable to put wand foci onto a staff

### ISSUE THREAD

**Issue by micglin** [Azanor/thaumcraft#1519]
Discovered while guiding a person playing Dark Trilogy modpack through some Thaumcraft progression.  Tested in my game playing BevoTechPack v11, with Thaumcraft 4.2.1.4 with various staffs, first with zero vis, then charged somewhat.  Tested again with the below mods and versions to see if it'd been corrected in later versions, and to minimize conflicts.  Then tested again with just forge and Thaumcraft. 

Started a test world, gave myself a bone staff core, 3 gold wand caps, and a primal charm, plus a full thaumium bossed silverwood wand and a shock focus.  Crafted the gold capped bone staff.

With the wand selected, I as able to use my F key to open the foci selection menu to add the focus to the wand.  Then hold Shift+F to remove it to my inventory.  When selecting the staff, the same actions had zero effect; I was unable to put the wand focus onto the staff.

forge-1.7.10-10.13.2.1236-universal.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
MobiusCore-1.2.3_1.7.10.jar
NBTEdit_1.7.10.jar
NotEnoughItems-1.7.10-1.0.4.83-universal.jar
Thaumcraft-1.7.10-4.2.3.2.jar
thaumcraftneiplugin-1.7.10-1.6a.jar
Waila-1.5.8a_1.7.10.jar
WailaNBT-1.7.10-1.4.jar

**Comment by OJwithC** [comment]
Three caps and a primal charm? Sounds like a crafting sceptre, not a staff.

**Comment by KlutzLament** [comment]
That's definitely the recipe for a scepter, not a staff. Scepters don't accept foci.

**Comment by micglin** [comment]
What?  That's...interesting.  You make a staff core with 2 wand cores and a primal charm.  Then the staff core, 3 wand caps, and the primal charm make a staff with one capacity, or (now that you mentioned it, I've tried it, and that seems familiar from AgSkies...) you can just combine the staff core and 2 caps for something still identified as the same "X Banded Y Staff", but it has greater capacity.

I also don't know how I got the gold capped primal staff to show up as costing only 108vis.

![image](https://cloud.githubusercontent.com/assets/3885242/5771545/fe2b9a36-9d04-11e4-96d6-42c53e7d3083.png)

Here's the same staff core, just without the charm and only 2 wand caps.

![image](https://cloud.githubusercontent.com/assets/3885242/5771586/e52503a0-9d05-11e4-837f-4689927f730f.png)

Given that I can't see in the thauminomicon what you DO with the staff cores ones crafted, I seem to have stumbled upon a recipie for a greater capacity staff...that won't take wand foci.  Is the fact this greater staff doesn't take wand foci an intended behavior, or a bug as I originally thought?

**Comment by Azanor** [comment]
Not a bug - you have been able to craft staff-sceptres for ages, but they are virtually useless as anything else other than a vis battery or to craft in-world structures.

**Comment by micglin** [comment]
Ah, vis batteries, like the vis stone amulets that hold 25 and 250 vis, that can charge in wand-recharge pedestals, but also from aura nodes like wands.  But one that you can also use for a few wand/staff functions (e.g: jarring nodes).

Neat, thanks for clarifying that.
