### ISSUE TITLE
Iron capped Wood wand "requires" 1 point of vis of each type in the Arcane Workbench

### ISSUE THREAD

**Issue by ThePB** [Azanor/thaumcraft#1521]
As title, TC 4.2.3.2, Forge blabla.1231, Baubles, Nei + chickencore (hopefully they do not interfere), nothing else.

More than "requiring" in the strict meaning of the term, the recipes shows a 1 vis off each type cost while not actually needing it... but still draining any wand that happens to be in the wand slot if it has vis.

So:
You can craft the ICWW in an arcane workbench even with no wand, but it has blinking vis symbols asking for 1 vis.
You can craft the ICWW with an empty wand
You can craft the ICWW with a charged wand, the wand will be drained of the "correct" amount of essentia, discounts applied.

I highly doubt this is intentional, even if minor.
Edit:
He beat me in reporting it :D
https://github.com/Azanor/thaumcraft/issues/1520
Closing this :D

**Comment by Dream-Master** [comment]
;-)
