### ISSUE TITLE
Scepter recipe with staff core makes a useless staff-scepter hybrid item.

### ISSUE THREAD

**Issue by cromambo** [Azanor/thaumcraft#1523]
The SCEPTER recipe can be made with a STAFF core instead of a rod. The result is listed as a staff and has a larger storage than a scepter or staff of the same materials, but the function of neither. It cannot hold foci. It cannot be put in an arcane workbench for crafting. It cannot be enchanted. It CAN be a giant vis storage device for bottling nodes.

I made this on accident trying to make my first ever staff. Afterwards, I spent about half an hour trying to figure out why staves couldn't hold foci, until I realized what I had done. It's pretty easy to mix up a rod and a core.

Code speculation time: Recipes are made dynamically at runtime somehow, evidenced by each combination not having an NEI entry. Staff cores and rods have similar IDs, like 4137:56 for a core and 4137:1 for a rod, so if those recipes are using the ID 4137 for being valid (ignoring that damage value) but getting properties from the rod/core for the product, it would explain this.
![bone core as scepter gives useless staff](https://cloud.githubusercontent.com/assets/4332494/5788046/52670790-9dd5-11e4-8f97-06980b043a08.PNG)
![three tools](https://cloud.githubusercontent.com/assets/4332494/5788047/5642a8ec-9dd5-11e4-97ca-677fcfdbf1ed.png)

**Comment by ThePB** [comment]
It's known and not a bug. It's still useful as a Vis battery for fueling repair and runic shieldind along with in world crafting (infernal furnace, node in a jar and so on and so forth)

**Comment by KlutzLament** [comment]
Where in the Thaumnomicon is this mentioned?

**Comment by ThePB** [comment]
Nowhere, it's a non-intended consequence of the wand system that Azanor has time and again stated will remain as-is. In short, "It's a feature, not a bug!" :D 

Example: https://github.com/Azanor/thaumcraft/issues/1519

**Comment by KlutzLament** [comment]
I have no issue with it but it should be mentioned in the Thaumnomicon, even if it's just tacked on to the end of the scepter entry.

**Comment by MalkContent** [comment]
Why? \^\^ come on, it's not like you craft this by accident. You craft it for science!
