### ISSUE TITLE
ThaumcraftFakePlayer doesn't extend FakePlayer

### ISSUE THREAD

**Issue by hilburn** [Azanor/thaumcraft#1527]
Currently working on something that would only be usable by real players, and running into an issue with ThamcraftFakePlayers (specifically with the Dynamism Tablet from TT and the Tunnel Bore) as they are not FakePlayers. Now it is possible to get around this with a
> player instanceof FakePlayer || (Loader.isModLoaded("Thaumcraft") && player instanceof ThaumcraftFakePlayer)

but that requires extra dependencies and is frankly all a bit of a faff. The FakePlayer class was provided to make this stuff a little easier, so would really appreciate it if you could use it.

**Comment by Azanor** [comment]
The ThaumcraftFakePlayer is actually not used by TC at all - it was just old code lying around from the time when the forge FakePlayer was broken. I use the default forge fake player. 
I tried to remove the class a while ago which broke some addon mods so I ended up just leaving it in. It will be removed in the next update. It was never part of the api so they shouldn't be using it in the first place.

**Comment by hilburn** [comment]
Ah ok, I know the Dynamism Tablet uses it which was the major issue I was running into
