### ISSUE TITLE
Strange things with new Aspect Calculation

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft#1530]
I have come about a couple of weird results of the new aspect calculation, such as glass bottles not having aspects (3 made from 3 glass, should have 1 vitreus), stone(brick) slabs lacking aspects, when they should have 1 terra (6 made from 3 blocks with 2 terra) and weirdest of all, the Mixed Crystal Cluster which lacks the primals aer and ignis, but has the other 4.

TC 4.2.3.3

**Comment by Barhandar** [comment]
>such as glass bottles not having aspects (3 made from 3 glass, should have 1 vitreus)

Bottles are made to contain, 1 Vacuos, same as phials.

**Comment by MalkContent** [comment]
Phials are 8 from 3 glass, not a 1:1 ratio. Also water bottles (the filled ones) still have their 1 aqua, 1 vitreus.

**Comment by Azanor** [comment]
There is some rounding an reduction that occurs with the aspect calculations.

**Comment by MalkContent** [comment]
Well then I'll limit my complaining to the mixed crystal clusters for now, because it's stupid. Also wooden plank slabs with 1 arbor from planks with 1 arbor whereas stone (brick) slabs with nothing from stone (bricks) with 2 terra.
