### ISSUE TITLE
Can't delete Thaumcraft copper/gold... capped Wand with Mod Tweaker and add them back with other Recipes.

### ISSUE THREAD

**Issue by Dream-Master** [Azanor/thaumcraft#1532]
I can't delete Thaumcraft copper/gold etc. capped Wand with Mod Tweaker and add them back with other Recipes. (Mod Tweaker) I think it isn't a Thaumcraft issue but with the Iron Wand it works now(After the Update to 4.2.3.3). The recipes is still shown in Thaumcraft Nei plugin but i cant craft it any more. Thanks for that.
Maybe there is a way to fix that Problem too.

**Comment by Azanor** [comment]
Not a bug really - the wand recipes use custom code that bypasses vanilla recipes.
