### ISSUE TITLE
Focus Warding warded blocks MASSIVE fps drop when warded area is seen

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft#1533]
as title, tc 4.2.3.3., forge 1277

Warded blocks displayed: http://sinister-lore.de/mcpics/tc_warded_blocks_a.png
vs not displayed: http://sinister-lore.de/mcpics/tc_warded_blocks_b.png

Warded blocks also seem to cause a considerable drop in fps without the area being displayed, noticable once you got enough warded blocks. The weirdest thing about it is that cpu, gpu or ram does not go up.

Edit: updated the pictures to show better difference in entities used. Also you might see optifine in there, the issue is the same without it.
Edit: added forge version. derp.

**Comment by MalkContent** [comment]
Not sure if it helps, but maybe changing BlockWarded.isOpagueCube to return true instead of false to reduce the number of sides it has to render. Atm I believe it causes all sides of the block and any adjacent blockt to get rendered, which might be part of the drastic fps drop. I'm just grasping at straws, though.

**Comment by Tiscareon** [comment]
Warded area hasnt to be seen directly for this effect to take place. Seems to be created by warded surface, a row of warded walls lowers my fps more than a qube

**Comment by MalkContent** [comment]
did you get to try the thingy I posted above yet? just curious if a fix might be that simple :)

**Comment by Kenosos** [comment]
Getting this issue too
http://i.imgur.com/P085kNK.jpg
http://i.imgur.com/kwTwgjz.jpg

**Comment by Azanor** [comment]
This is a known issue and will be addressed in the 1.8 version of TC.
