### ISSUE TITLE
Can primordial pearls be blacklisted from uncommon treasure bags?

### ISSUE THREAD

**Issue by thcv** [Azanor/thaumcraft#1534]
Seems a bit overpowered.

**Comment by Azanor** [comment]
Already done for next version :)

**Comment by MentalMouse** [comment]
Is that in 4.2.3.3, or whatever is coming up afterwards?

**Comment by Azanor** [comment]
It will be in the next update - I was maybe a bit hasty on closing this

**Comment by thcv** [comment]
This bug still exists in 1.7.10-4.2.3.5

**Comment by Azanor** [comment]
Since there hasn't been an update yet... Yes, the bug still exists.

**Comment by Yulife** [comment]
Not trying to advertise but if you want to modify the loot bag contents you can soon do it with Modtweaker2 :) Code here ~ https://github.com/jaredlll08/Mod-Tweaker2/blob/master/src/main/java/modtweaker2/mods/thaumcraft/handlers/Loot.java
