### ISSUE TITLE
Golem Animation Core: Use will not place buckets of lava

### ISSUE THREAD

**Issue by ma7hatter** [Azanor/thaumcraft#1535]
I'm using the direwolf20 1.7.10 v1.0.3 pack (Thaumcraft 4.2.1.4).  The use animation core can fill buckets, but when I try and have the golem place buckets on the ground, it will just stare at the location but not do anything will the filled bucket.  I've tried both block/air arrangements, and all sides of target location I could think of.  I thought perhaps that the golem is picking the lava back up to fast for it to register as being put down, but there isn't any visual indication of that happening.

**Comment by MentalMouse** [comment]
You may need to mark the empty space rather than the ground, as with saplings.

**Comment by chrisbecke** [comment]
@MentalMouse hmmm? My use core golems have planted saplings just fine being targetted on the grass block over many TC versions.

**Comment by ma7hatter** [comment]
I have in fact tried the 'empty space' method as mentioned above with no luck.  I should mention that the golems do other things just fine (like the saplings).  I just can't seem to get them to dump a bucket.

**Comment by MalkContent** [comment]
for me the 4.2.3.3 use golem can't even fill buckets. Also won't use bucket o' liquid death or purifying fluid. Maybe it's a small hint for using the decanting golem :3 cause usegolem definitly still works phials and jars, so no issue with a changing item in hand.

**Comment by ma7hatter** [comment]
I wouldn't mind if use golems have buckets blacklisted for them, but the description of the cores will need to change.  We are of course speculating until Azanor can comment.  If it is true that we are being encouraged to use decanting golems, they will need to be able to dump their contents into the world, and in multiple location.  As of now they are attached to a single tank.

**Comment by Azanor** [comment]
I've had a bit of a dig through the code and it seems to be something in the bucket code itself that is preventing the liquid from being placed - the golem is successfully right-clicking the bucket, but a check in the bucket code is preventing the liquid from actually being placed.
In short: nothing much I can do about it at the moment. I will fiddle with it again once I start moving the code over to 1.8

**Comment by ma7hatter** [comment]
Thanks for the reply Azanor, keep up the good work!
