### ISSUE TITLE
suggestion . A config option for Harder Recipes(Arcane, Infusion, Crucible...)

### ISSUE THREAD

**Issue by Dream-Master** [Azanor/thaumcraft#1539]
I am sorry when i asking again but if i cant change the Recipes from the Wand i would to ask if you can add harder Recipes wich can be switched on or off via config. I try to make a hardcore Private Modpack and i make many Recipes much mor harder with Modtweaker/Minetweaker. Only this few Recipes(Wands) i cant change. I love your Mod but it is so powerful that i need to make it much more harder to get the good stuff. Ideas for Recipes i think i have enough(I can make recipes suggestions too). I change a bunch of Stuff in other Mods already try to balancing everything to make thr perfect Modpack (for me and i hope for others too). But i am far away from done. So if it is possible to customize more things I would be very happy. Thanks in advance.

**Comment by Azanor** [comment]
That is the sort of thing you won't be able to do with a simple config file. You will need to create an addon mod to change recipes and such.
