### ISSUE TITLE
Crash with Waila

### ISSUE THREAD

**Issue by leSamo** [Azanor/thaumcraft#1541]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 21.1.2015 15:17
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.minecraft.tileentity.TileEntity.func_145838_q(TileEntity.java:176)
	at net.minecraft.tileentity.TileEntity.func_145828_a(TileEntity.java:223)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:105)
	at thaumcraft.client.renderers.block.BlockTableRenderer.renderInventoryBlock(BlockTableRenderer.java:42)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderInventoryBlock(RenderingRegistry.java:125)
	at net.minecraft.src.FMLRenderAccessLibrary.renderInventoryBlock(FMLRenderAccessLibrary.java:59)
	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8145)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at mcp.mobius.waila.overlay.DisplayUtil.renderStack(DisplayUtil.java:70)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:78)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:40)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickRender(WailaTickHandler.java:54)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_281_WailaTickHandler_tickRender_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:988)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.tileentity.TileEntity.func_145838_q(TileEntity.java:176)
	at net.minecraft.tileentity.TileEntity.func_145828_a(TileEntity.java:223)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:105)
	at thaumcraft.client.renderers.block.BlockTableRenderer.renderInventoryBlock(BlockTableRenderer.java:42)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderInventoryBlock(RenderingRegistry.java:125)
	at net.minecraft.src.FMLRenderAccessLibrary.renderInventoryBlock(FMLRenderAccessLibrary.java:59)
	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8145)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)

-- Item being rendered --
Details:
	Item Type: thaumcraft.common.blocks.BlockTableItem@6c8f48b5
	Item Aux: 2
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at mcp.mobius.waila.overlay.DisplayUtil.renderStack(DisplayUtil.java:70)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:78)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:40)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickRender(WailaTickHandler.java:54)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_281_WailaTickHandler_tickRender_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['leSamo'/160, l='MpServer', x=43,12, y=77,62, z=259,94]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-444,64,709), Chunk: (at 4,4,5 in -28,44; contains blocks -448,0,704 to -433,255,719), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 2022301 game time, 2313153 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 30 total; [EntityTFNagaSegment['unknown'/517, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/518, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/519, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/520, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/521, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/522, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/523, l='MpServer', x=0,00, y=0,00, z=0,00], EntityBlock['unknown'/779, l='MpServer', x=48,25, y=74,00, z=261,25], EntityTFNagaSegment['unknown'/524, l='MpServer', x=0,00, y=0,00, z=0,00], EntityBlock['unknown'/780, l='MpServer', x=13,25, y=26,01, z=222,25], EntityTFNagaSegment['unknown'/525, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/526, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/527, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/528, l='MpServer', x=0,00, y=0,00, z=0,00], EntityItem['item.item.ItemCrystalEssence'/163, l='MpServer', x=45,50, y=81,13, z=261,50], BlueSlime['Blue Slime'/164, l='MpServer', x=37,29, y=146,00, z=256,24], EntityClientPlayerMP['leSamo'/160, l='MpServer', x=43,12, y=77,62, z=259,94], BlueSlime['Blue Slime'/166, l='MpServer', x=34,19, y=146,00, z=251,19], BlueSlime['Blue Slime'/167, l='MpServer', x=32,59, y=146,00, z=253,88], EntityBoat['Boat'/168, l='MpServer', x=27,25, y=63,43, z=294,75], EntitySheep['Sheep'/169, l='MpServer', x=2,84, y=63,00, z=283,53], EntitySkeleton['Skeleton'/170, l='MpServer', x=-14,50, y=64,00, z=256,50], EntitySheep['Sheep'/171, l='MpServer', x=30,56, y=65,00, z=210,66], EntitySpider['Spider'/172, l='MpServer', x=-17,72, y=64,00, z=256,03], EntityMinecartChest['entity.MinecartChest.name'/173, l='MpServer', x=101,50, y=32,50, z=269,47], EntityBat['Bat'/174, l='MpServer', x=-30,25, y=41,09, z=275,25], EntitySheep['Sheep'/175, l='MpServer', x=110,72, y=63,00, z=279,50], EntitySheep['Sheep'/176, l='MpServer', x=80,97, y=70,00, z=221,06], EntityZombie['Zombie'/178, l='MpServer', x=111,00, y=33,00, z=207,56], EntitySkeleton['Skeleton'/180, l='MpServer', x=-32,59, y=31,00, z=203,88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_11, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 307590416 bytes (293 MB) / 880279552 bytes (839 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 36 mods loaded, 36 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.3.1} [BuildCraft] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.3.1} [BC Transport] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.3.1} [BC Silicon] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.3.1} [BC Factory] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	additionalpipes{3.4} [Additional Pipes] (additionalpipes-3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1034-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AWWayofTime{v1.3.0b} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0b-3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.3.1} [BC Builders] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.3.1} [BC Energy] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	extracells{2.1.34} [ExtraCells] (ExtraCells-1.7.10-2.1.34bnull.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FastCraft{1.16} [FastCraft] (fastcraft-1.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.2.660-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.660-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inpure|core{1.7.10R1.0.0B7} [INpureCore] (INpureCore-[1.7.10]1.0.0B7-19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.3} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	VersionChecker{1.1.7} [Version Checker] (VersionChecker-1.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3316, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [F32-1.7.10.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MalkContent** [comment]
any info on what you were doing at the time of crash?  
also update waila to 1.5.8a and see if it persists

**Comment by leSamo** [comment]
I have latest version of waila and thaumcraft. I was loading the world.

**Comment by MalkContent** [comment]
does this happen everytime now i.e. is the world unplayable?

**Comment by leSamo** [comment]
I tried it 4 times and it always crashes.  removed waila and it's working.

**Comment by Azanor** [comment]
So that would make it a problem with Waila, wouldn't it?

**Comment by Havanacus** [comment]
I encountered this exact issue recently.  I know the issue is closed, but though it may help future Googlers to know that my issue was fixed by disabling Waila through it's configs. This allowed my to connect to the server without crashing.
I believe the crash was triggered by a Crystal Cluster placed on the surface of a Research Table with Notes in it.

**Comment by leSamo** [comment]
I think it is caused by CV charging relay on top of the arcane workbench

**Comment by Mozirilla** [comment]
Update Waila manually to 1.5.9. Seems to fix the problem. Hope this helps!
