### ISSUE TITLE
suggestion The font is too small to read

### ISSUE THREAD

**Issue by TehporP** [Azanor/thaumcraft#1542]
Well as you can see,the font is too small
Can you add a option in config.yml to increase font size?

**Comment by TehporP** [comment]
![qq 20150122155024](https://cloud.githubusercontent.com/assets/8299221/5852221/65de1480-a24e-11e4-8528-5cedeb282d7f.png)
Here the image

**Comment by dmb1881** [comment]
My recommendation is changing your gui scale to to large if you cant see it. Its not really a bug, but I can see how it can be hard to read. Hope this helped.

(Press escape, go to options, go into video settings it should be somewhere in there.)

**Comment by Azanor** [comment]
Unfortunately there isn't any easy way to change the font size without breaking the GUI - MC doesn't handle font scaling very well. I will fiddle with it a bit to see if I can improve things for the 1.8 update, but for now I'm going to have to close this.
