### ISSUE TITLE
Travelling trunk despawns when commanded to stay put

### ISSUE THREAD

**Issue by ramonmaruko** [Azanor/thaumcraft#1543]
Is this intended? I was thinking that they have the same behavior as the vanilla pets (i.e. wolf, ocelot), when asked to stay put, they would still be there when I revisit the chunk. The travelling trunk however is gone

I also noticed that on creative, whenever I teleport away using the tp command, they are gone when I come back to the chunk. For example:

1. Current coordinate is (800, 4, -39)
2. Spawn tamed wolf and travelling trunk
3. /tp 0 4 0
4. /tp 800 4 -39

Result: tamed wolf is still there, travelling trunk is gone; regardless if commanded to stay put or to follow.

Naming the traveling trunk (e.g. using a Name Tag) prevents it from despawning.

Environment:

Minecraft 1.7.10
Java 1.8.0_25 x64
MCP v9.05
FML v7.10.85.1286
Minecraft Forge 10.13.2.1286
Optifine Optifine_1.7.10_HD_B4

Mods:

* CodeChicken Core
* Not Enough Items
* bspkrsCore
* ArmorStatusHUD
* DamageInidicators
* DirectionHUD
* StatusEffectHUD
* AppleCore
* Batty's Coordinates PLUS
* Baubles
* Biomes O' Plenty
* Chicken Chunks
* Extrabiomes XL
* Inventory Tweaks
* Thaumcraft
* Thaumcraft NEI Plugin

**Comment by Azanor** [comment]
oops
