### ISSUE TITLE
Infernal Furnace ignores Ignis Jars.

### ISSUE THREAD

**Issue by Moorleiche2k** [Azanor/thaumcraft#1545]
Ignis isnt fed to Infernal Furnace. Used all types of Jars including voids within front of the Furnace in a distance below 5 blocks. Filled them from Ignis Phials. Version 4.2.3.0

**Comment by TheMadmanofChaos** [comment]
The furnace can no longer pull essentia through the air, and as a result you need to pipe it in via essentia tubes or use ignus CV.

**Comment by Moorleiche2k** [comment]
Hey thanks,

i was fiddling with the furnace for several hours and couldnt find a 
clue of how to make it working. But what is Ignus CV? A Node?

Best regards

Am 23.01.2015 um 23:01 schrieb TheMadmanofChaos:

**Comment by TheMadmanofChaos** [comment]
Cv was a fairly recent addition, found in the thaumergy tab. It effectively lets you turn an aura node into a power source.

**Comment by netmc** [comment]
There is a new hole located in the bottom of the furnace specifically for piping in ignis vis prior to being able to set up a node power system.
