### ISSUE TITLE
Feature Request: Void Metal Blocks (and maybe a Golem)

### ISSUE THREAD

**Issue by Durpady** [Azanor/thaumcraft#1547]
Void Metal is an ingot, like Thaumium.  Why does it not have a block form?  Not something vital to gameplay, but it makes sense to me to add it.

While we're at it... there are Eldritch additions to Thaumaturgy (Wand Caps, Primal Focus and Staff), Alchemy (Reservoir) and Artifice (Void Thaumaturge Robes).  What about a Void Metal Golem?  It would essentially be a better Tallow Golem - the latter is "average" in all areas, the former would be "good" (but not "great" unless balance isn't an issue) in them, and it'd be able to hold 2 upgrades (like Tallow and Thaumium).  If you want to get creative, it could have three eyes or something else befitting its Eldritch nature.

**Comment by MentalMouse** [comment]
Following the lead of the equipment, it should have low HP but rapid healing, and guard attacks should inflict Weakness.  Some upgrades might not work on them.
