### ISSUE TITLE
Use Golem not winding Clockwork Engine from Forestry

### ISSUE THREAD

**Issue by Durpady** [Azanor/thaumcraft#1548]
Title sums it up.  Forestry's Clockwork Engines are powered by the player right-clicking them, so they should be power-able by a Use Golem, right?  Apparently, though, they're not.

On the other hand, since that's essentially infinite free RF, I'm not entirely sure this is a bug.

**Comment by netmc** [comment]
Many mods go out of their way to make sure fake players can't use items that are designed to be used manually by players.  I would say this probably falls under working as intended category.

**Comment by Azanor** [comment]
Yup, as far as I know those engines are specifically coded not to be automatable.
