### ISSUE TITLE
Feature Request: Crystallized Essentia Blocks

### ISSUE THREAD

**Issue by Durpady** [Azanor/thaumcraft#1549]
Crafted from 9 of a given type of Crystal, they'd be for storage and decoration.

I know the Thaumic Infusion Add-On adds Essentia Blocks, but those are made via Arcane Crafting with Phials, as opposed to the already-solid-and-begging-for-a-use Essentia Crystals... and from what I understand, they're block entities, which means they could cause problems in large numbers.

From what I've seen of the block data in this mod, you're still constrained by the 16-metadata-states issue.  That means that, assuming no "variants" like Stone Bricks, you could contain all the aspects in exactly three block ID's, with a fourth being available for things like Forbidden Magic to populate.
Not something vital to the mod, but like the Banners it'd be a neat addition.

**Comment by MentalMouse** [comment]
I wouldn't go from 9 of those little crystals to a placable block, I'd have an intermediate form corresponding to ingots, say a "crystal mass". That is, each block would represent 81 points of essentia.
