### ISSUE TITLE
Looks like I'm still getting the warded blocks recursion error, despite upgrading to 4.2.3.3

### ISSUE THREAD

**Issue by Preladon** [Azanor/thaumcraft#1550]
Hello Azanor.

Playing the Automata modpack which has had reports of this problem.  I've just had it, and upgraded to the latest release (4.2.3.3) of Thaumcraft to fix it.  However, I'm still getting the same problem.

Prior to the upgrade, the view window was not being generated (it was just black) before I was dumped back to the FTB launcher.  Now, I get the view screen okay, and it seems to continue to run as long as I am alt+tabbed into a different window, but actually *running the game* locks it up as unresponsive until I get dumped back to the launcher.

Crashlog is here: http://pastebin.com/CLkdpLqq

It may, of course, be a mod interaction from Automata - I've posted on the modpack forum (http://forum.feed-the-beast.com/threads/1-7-10-beta-automata-%E2%80%94-rpg-hqm-reputation-systems-custom-ore-gen-mystcraft-ages.56432/page-12#post-893373) as well.

**Comment by Preladon** [comment]
As an update.  Setting my render distance all the way down to 2 blocks and moving away from the warded stone that makes up the castle in this mudpack enabled me to get back in to the game.

**Comment by MalkContent** [comment]
do you have some kind of chunkloader in use?

**Comment by Preladon** [comment]
I don't believe so.  The automata map is pre-generated in the local area though, so it might be hidden somewhere.  Having said that, it uses Journeymap, and the only loaded chunks that show up are the ones that surround the player, so I guess not.

**Comment by MalkContent** [comment]
hm. I had that crash when I was rejoining and in my home base with lots of warded blocks. then i stopped chicken chunks chunkloader from loading my chunkloaders chunks when i was offline and that worked. not sure how that worked, but it did.

**Comment by Preladon** [comment]
I've returned to the area that has the warded blocks since, and I haven't experienced any further crashes.  I wonder if it is just an issue that occurs on first load of the new TC (4.2.3.3) if there are existing warded blocks in the player view / render area?

**Comment by Azanor** [comment]
Unlikely, but stranger things have happened. I haven't changed anything with warded blocks for quite a few updates.

**Comment by Preladon** [comment]
Strange.  According to the Automata forum, 4.2.3.3 fixes the cyclical error that leads to a crash with warded blocks.  That I was still having the problem was the reason I posted here.  Is that not the case then?

**Comment by Azanor** [comment]
I think they are mistaken - the cyclical error isn't an easy one to fix since something is causing the warded blocks to think it looks like a warded block instead of whatever block was warded in the first place. Currently the only way I know to fix it would be to not make warded blocks look like their original blocks.

**Comment by Preladon** [comment]
Aha.  Then that probably means that the original title text I used for this bug doesn't make very much sense!

As I say, I haven't had this error again since upgrading Thaumcraft, but hopefully the data in the original crash log may prove useful in some way.

**Comment by Azanor** [comment]
related: https://github.com/Azanor/thaumcraft/issues/1604

**Comment by BBoldt** [comment]
On Thaumcraft 4.2.3.5: https://gist.github.com/BWhite1/2d65075bd191b7da0b17

**Comment by MalkContent** [comment]
Huh. didnt see that crash without waila 1.5.8 yet. Try reverting Waila to 1.5.9, maybe a new bug got introduced. If it happens with 1.5.9, too, it's a new bug.

**Comment by BWhite1** [comment]
I made a mountain then I cut it from the world, then I started warding the entire outside of it.
So it's a floating mount 52 blocks tall, and 20 blocks of air
The entire bottom is warded. and most of the side I am working on, 2 sides are unwarded, one is about 3/4 warded, Inside of that is a warded 23x23x17 warded box containing a t6 blood altar, ontop of that is 
an energize node that was hungy (same mod dunno if it applies) all of this is loaded in front of me, but behind walls of warded arcane brick.

**Comment by MalkContent** [comment]
and you are telling us that why exactly? ^^

**Comment by BBoldt** [comment]
I told him to come give as much information as possible regarding his setup and what may have lead to this crash.

**Comment by MalkContent** [comment]
a. well. it's a gigantic shitton of warded blocks. what kind of super computer are you even running this on :D ?

**Comment by MalkContent** [comment]
anyways. you also have a gigantic shitton of mods. it wouldn't surprise me if one of them has the same kind of hickup Waila 1.5.8 had

**Comment by BWhite1** [comment]
its an i7-4790K but it still lags :( 

http://i.imgur.com/6oCj2bw.png is with 2 chunks loaded around me

**Comment by Azanor** [comment]
The current warded blocks system is just not set up to handle that many warded blocks. They are all tile entities atm so errors like this along with craploads of lag is to be expected.
Either way, warded blocks will change or go away in 1.8 so closing this since I'm not working on the 1.7.10 branch anymore.

**Comment by MalkContent** [comment]
also doesnt help that they aren't opague :P
if you wanna leave them non opague, just make a should render side thing.
atm all sides of a warded block render, always

**Comment by MalkContent** [comment]
which also causes warded blocks behind warded blocks to render, btw
