### ISSUE TITLE
[Enhancement] Unprocessed Items in Advanced Alchemical Furnace should not Despawn

### ISSUE THREAD

**Issue by Xirema** [Azanor/thaumcraft#1551]
Given that the whole point of the Advanced Alchemical Furnace is to allow huge quantities of essentia to be processed simultaneously, it feels frustrating that pushing the furnace too far can cause large stacks of items to vanish simply because it took so long for the furnace to process everything, especially since this isn't a risk with the regular Alchemical furnace.

So I would propose that one of two things happens to improve Advanced Alchemical Furnaces:

* Make it so that items which are input into an Advanced Alchemical Furnace have like 1000x the lifespan (or some other absurdly high number that you can realistically assume they'll never despawn)
* Store the items input into the furnace into a Tile Entity associated with the furnace.

I was under the impression that the Infernal Furnace operated under conditions that I've just described (i.e., it appears that they get stored in a temporary buffer while they get processed); it should be possible to duplicate the basic functionality here.

**Comment by forsaken1111** [comment]
So... working as intended?
