### ISSUE TITLE
Greatwood planks do not transmit redstone

### ISSUE THREAD

**Issue by netmc** [Azanor/thaumcraft#1552]
A redstone signal is not transmitted through greatwood planks.  Not sure if other thaumcraft blocks have the same issue or not as I've decorated my base with greatwood planks.  I've attached 2 examples.  One using a regular piece of cobblestone, an another in the same setup with greatwood planks.

![2015-01-25_19 43 59](https://cloud.githubusercontent.com/assets/10328528/5894416/56833274-a4cc-11e4-8bb1-2d42b8c8a4bc.png)
![2015-01-25_19 44 40](https://cloud.githubusercontent.com/assets/10328528/5894417/5684fc80-a4cc-11e4-8f39-65feec54b871.png)

**Comment by MentalMouse** [comment]
It's a known bug; Greatwood and silverwood planks are transparent blocks.  Fixing it would entail terrible destruction, with much wailing and gnashing of teeth, so it's been put off at least until the possible 1.8 release.
