### ISSUE TITLE
Unable wand focus??

### ISSUE THREAD

**Issue by dyw1014** [Azanor/thaumcraft#1553]
I would like to use the ' focus ' , Silver Wood Wand is Entering the 'F' is not equipped with a ' focus '.

How do I fix it?

**Comment by forsaken1111** [comment]
Do you have another mod also using the F key?

**Comment by ThePB** [comment]
Also, if you have just upgraded from a very old version or simply have watched an outdated video tutorial, you now need to hold the F key to make the foci selection wheel.

**Comment by MalkContent** [comment]
Go into the options and make sure your wand focus key is actually F. Then take the wand in hand and hold the key to open the selection wheel.
Please use the forums or irc for this kind of questions.
