### ISSUE TITLE
Eldritch Crabs deal damage during death

### ISSUE THREAD

**Issue by Boingboingsplat** [Azanor/thaumcraft#1554]
I've noticed that Eldritch Crabs can still deal damage to you if they are latched onto your head during their death animation. (When they are red and tilting over before turning into smoke.) They can even latch onto your head during this animation.

Thaumcraft 4.2.3.3, Forge 10.13.2.1277

**Comment by MentalMouse** [comment]
Consider it cinematic badassery. :)

**Comment by Azanor** [comment]
Yup, they are just that nasty.
