### ISSUE TITLE
Arcane Spa can be used to bring water to the Nether

### ISSUE THREAD

**Issue by ThePB** [Azanor/thaumcraft#1556]
As title :D
It was an issue reported on the thread that was possibly missed :D
Just place the Arcane Spa in the Nether, have a bucket of water, place the water in the spa, select the "use just the fluid" mode for the spa. You now have a stationary full block of water. A block update near the water itelf will make it flow and work as normal water. It can also be used in couples to create infinite springs.

TC 4.2.3.3, forge 1231 and 1291 tested.

**Comment by Stepan1404** [comment]
Fix This plz
