### ISSUE TITLE
Aspect Colors

### ISSUE THREAD

**Issue by VicenteRD** [Azanor/thaumcraft#1558]
Not really an issue and I'm sorry about it, didn't know where else to ask.

Is there any way to know the hex color code for each of the aspects? I'll be using this on a ComputerCraft program I'm working on (If you want, I can share later)

**Comment by chentao807** [comment]
I think you can get more information from Thaumcraft API code.
Aspect class's constructor has color parameter.
for example, AIR aspect, hex 0xffff7e.
https://github.com/Azanor/thaumcraft-api/blob/master/aspects/Aspect.java

**Comment by Azanor** [comment]
Yup, that is exactly where you will find them.

**Comment by VicenteRD** [comment]
Thank you!
... And sorry

**Comment by VicenteRD** [comment]
Thank you!
... And sorry
