### ISSUE TITLE
Warp effect causes terminal glasses from OpenPeripherals to go black until mc restart

### ISSUE THREAD

**Issue by michael-3-141** [Azanor/thaumcraft#1560]
I've been having this issue with the terminal glasses for a while now, but now I saw that when the screen goes dark on the sides because of the warp, it for some reason makes the terminal glasses go completely black, but only if there are any boxes drawn on them. I don't know on which side it is (thaumcraft or openperipherals) so I'm posting this on both, just in case.

**Comment by michael-3-141** [comment]
May I ask why was this closed? was it fixed? is it not on thaumcraft's side?

**Comment by Azanor** [comment]
I doubt this is an issue on the TC side.
