### ISSUE TITLE
Progressive server performance hit on long vis relay chain

### ISSUE THREAD

**Issue by justicesays** [Azanor/thaumcraft#1561]
Decided it would be nice to have a recharge point in my sinister node room so I could lightning bolt zombies without worrying about vis in my staff.
So I added a chain of about 16 relays from my energized node down to the room. This worked fine and I didnt see any immediate impact. 
However, after running the server overnight, I noticed regular humps in the tick time, pushing close to the 25 ms limit (about 8-10 extra ms every 2 seconds or so)
When I went and removed the relays, the tick time went back down to a steady 15s. 
Nothing was connected to the relays, they just dead ended so I could stand around wearing a vis amulet.
Oddly I didnt see any entity timings using opis that would implicate the vis relays, but  removing them resolved the issue.
Some of the chunks involved are loaded via chickenchunks. such as the energized node itself, but not the end of the relay chain.

**Comment by justicesays** [comment]
I'm running:

fastcraft-1.16.jar
Thaumcraft-1.7.10-4.2.3.4.jar
sampler-1.16.jar
Automagy-1.7.10-0.18.jar
ChickenChunks-1.7.10-1.3.4.16-universal.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
extrautilities-1.2.1.jar
MobiusCore-1.2.3_1.7.10.jar
NewDungeons-0.3(1.7.10).jar
Opis-1.2.3_1.7.10.jar
twilightforest-1.7.10-2.3.2.jar
1.7.10
AdminCommandsToolbox-0.0.2a_1.7.10.jar
AM2-1.4.0.006.jar
AnimationAPI-1.7.10-1.2.4.jar

./1.7.10:
Baubles-1.7.10-1.0.1.10.jar
CodeChickenLib-1.7.10-1.1.1.99-universal.jar

**Comment by justicesays** [comment]
The network was connected it's full length when I disconnected it , all nodes were lit.

**Comment by Azanor** [comment]
In regards to both this and any other vis-relay related issues:
They are going away in the 1.8 version of Thaumcraft and for the most part I have stopped working on the 1.7.10 version. So, I'm going to close this.
