### ISSUE TITLE
TileEntity ignored log spam

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft#1564]
Since the upgrade from tile entity to block based light glimmers my servers lag is much improved. However, when the map areas that have arcane lamps are first loaded the log fills with 10'000s  lines of spam telling me the game is ignoring the tile entities.

Perhaps the tile entities need to be re-registered, such that they are loaded, but registered in such a way that they delete the tile entity and clean up existing worlds with thousands of these things.

**Comment by MalkContent** [comment]
Dude, what did you expect. The save files hold these "10'000" of tile entities which they now can't load anymore because the blocks don't return them and the classes are missing (I think). The log entries are not tc's fault but mc's and tbh they got a good reason to be there.

**Comment by chrisbecke** [comment]
Hence my suggestion / hope that it is possible for a TC update to re-add the classes necessary to load the tileentities - but change them to delete themselves.

**Comment by MalkContent** [comment]
A, okay. But imo that would just be junk code with the sole benefit of having a neater looking log in old saves. I mean even the number of times that can occur is finite, not like it's a permanent bother.

**Comment by Azanor** [comment]
I also want to add that those invalid tile entity entries are supposed to be removed automatically. I did several tests to make sure of the fact and you should only ever get that message once per invalid tile entity. Are you getting the log spam for the same area over and over between world loads?

**Comment by chrisbecke** [comment]
Yes. Each time I load my world. I had ~64 arcane lamps that (according to opis) has created about 12k tile entites. Each time I load my world and go to this area the log fills with messages again. Once visited I can come and go with no repeat messages even though the area shows as unloaded.

It was my understanding that minecraft deleted blocks - and presumably tile entities - that were no longer registered so I was(am) confused too.

**Comment by Azanor** [comment]
Those chunks might not be saving properly. You might want to try an trigger a save by placing some blocks in all the chunks or doing other stuff.
Is this on a server running cauldron or something like it?

**Comment by chrisbecke** [comment]
Right now the save game is being played in SSP.
If tile entities being changed don't count as a block change and force an update it is quite possible that they are simply not saving. Ill drop a dirt block in each chunk and try again. Well. later. at work. As you should be!?

**Comment by Azanor** [comment]
Yup

**Comment by chrisbecke** [comment]
Ok. Well. Without even trying, all the tile entity ignored messages have finally ceased.

**Comment by MalkContent** [comment]
:) hooray. maybe it was random updates or entities getting saved in the chunks.
