### ISSUE TITLE
Aspects are missing

### ISSUE THREAD

**Issue by ArbiterofTruth** [Azanor/thaumcraft#1572]
I just encountered a bug: After launching and starting up my world my jars, phials and items which had compound aspects had question marks when I hovered over them or said "Unknown essentia". I looked at my Thauminomicon and my research table and only had the primals, but when I looked at something through my Thaumometer everything was already scanned.

**Comment by Azanor** [comment]
Somehow your RP had gotten reset. If you have access to the console commands you might just want to give yourself some rp.
