### ISSUE TITLE
Smart Moving. Arcane Levitator. Doesn't drop down

### ISSUE THREAD

**Issue by anion155** [Azanor/thaumcraft#1573]
In Smart Moving Sneaking re implemented. One of the changes was: you can't sneak in the falling, flying, etc. So when you are levitating above Arcane Levitator you can't actually sneak, I mean isSneaking() method of PlayerEntity isn't work in this situation.

Can you change this for checking is sneak key pressed instead of using isSneaking method?

**Comment by chrisbecke** [comment]
According to posts on the MCF thread, TC is now checking for "shift" directly rather than the key bound to sneak.

**Comment by MalkContent** [comment]
Is this really hardcoded to shift now?
