### ISSUE TITLE
Thaumic Tinkers Crashes

### ISSUE THREAD

**Issue by Pyromaster1334** [Azanor/thaumcraft#1575]
I get this message every time I try to use the Osmotic Enchanter from thaumic tinkers (I know that the mod belongs to Pixlepix). Heres the messages:
https://paste.ee/p/8wAWG

**Comment by Stepan1404** [comment]
Тебе нужно обновить ThaumicTinkerer с Jenkins

Update Thaumic Tinkerer (2.5 1.7.10-x) from Jenkins
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/

**Comment by Azanor** [comment]
Yup, it looks like you have and outdated version.

**Comment by Pyromaster1334** [comment]
well that links busted for me
