### ISSUE TITLE
repair enchantments cant be used in anvil

### ISSUE THREAD

**Issue by JokerReaper** [Azanor/thaumcraft#1578]
ive been using thaumcraft in my personal mod pack, & one of the other mods (evilcraft) allows the ability to remove an enchantment from one tool/weapon into a book to use on another, but when i put the book into an anvil i am unable to add it to the tool/weapon, i do not know if it is the same with the other enchantments from thaumcraft. i was able to add all other vanilla enchantments to whatever i chose. so im wondering is it a restriction to only be used with the rituals or is this simply a bug?

**Comment by chrisbecke** [comment]
I think you are trying to add repair to an item that already has unbreaking. This is not allowed.

**Comment by JokerReaper** [comment]
ahh ok, i didnt know that, sorry for the false report
