### ISSUE TITLE
Can't Runic Augment Focus Pouch

### ISSUE THREAD

**Issue by Sheenus** [Azanor/thaumcraft#1579]
Not sure if this is a real issue, but seems odd so I'll mention it anyway; I can't seem to perform the Runic Augmentation infusion ritual on the Focus Pouch. Seems odd since it doubles as a belt bauble.

For reference, a gif of me attempting the ritual in creative [here](http://i.imgur.com/HJbyRy6.gifv) (via imgur). Using Thaumcraft 4.2.3.3 and baubles 1.0.1.10.

**Comment by Azanor** [comment]
Its not intended to be able to accept runic augmentation - pouches aren't known for their defensive capabilities :p
