### ISSUE TITLE
Request for Reinstatement of Old Functionalities

### ISSUE THREAD

**Issue by TBBW2001** [Azanor/thaumcraft#1585]
1) The new functionality of Infernal Furnaces and Lamps requiring piping/relays seems theme-breaking (and looks odd). Please reinstate Essentia Mirrors and direct Jar-sucking for these magical machines. Or, please offer a switch to allow this in config. (Edit Note: Essentia Mirrors now have only one use, too, since only one machine can pull essentia via this method.)

2) Jar wobble functionality was removed for visual problems; can it be reinstated yet? Can it be turned on by config switch?

**Comment by MentalMouse** [comment]
While you're at it, can you please restore the old functionality for the Shovel of the Earthmover?

**Comment by ThePB** [comment]
> While you're at it, can you please restore the old functionality for the Shovel of the Earthmover?

Guess you didn't try the latest fixes to the shovel... it's amazing right now. Old functionality + NEW functionality...

**Comment by chrisbecke** [comment]
No. not its not amazing. None of the mode switch modes allow for platforms / walls to be extended in the way 4.1 allowed.

**Comment by ThePB** [comment]
.... yes it does?

**Comment by MentalMouse** [comment]
The key point about the 4.1 SotE was that it let you extend walls, floors, and ceilings in the same plane, *without* having to get out in front of the forward edge (to "point the side").  Now, AFAICT, no variation of the "undigging"  will let you do that..  Instead, the new SotE makes it easy to suffocate yourself with a single careless click (say, on a cobblestone ceiling).

**Comment by TBBW2001** [comment]
I appreciate the interest, but the if you'd really like to chat about the Shovel, open a new thread. :) 

Back on topic, this is about restoring functionality to Essentia Mirrors, Jars, Infernal Furnaces, Lamps, and more. :)

**Comment by forsaken1111** [comment]
In any case, I believe this issue tracker is for bug reports only and feature requests go in the forum thread.

**Comment by Azanor** [comment]
Yup, this is for reporting bugs. In any case the functionality was changed for a reason and will once again change a bit in 1.8 so I'm closing this.
As for the shovel: Get used to it. I've changed it 3 (or 4?) times now at players request and each time someone else finds a reason to dislike it. I'm done messing with it.
