### ISSUE TITLE
I think something is wrong with SotE bonemeal function...

### ISSUE THREAD

**Issue by ThePB** [Azanor/thaumcraft#1586]
...if you change the mode by pressing "g" to change the shape to a vetical wall and then you use it to bonemeal grass. Not "dirt grass", but actual grass, the item.

![2015-02-06_11 42 21](https://cloud.githubusercontent.com/assets/5775528/6078070/9ec272b6-adf5-11e4-8a96-abdd256a331b.png)
![2015-02-06_11 41 52](https://cloud.githubusercontent.com/assets/5775528/6078072/a1dff932-adf5-11e4-999d-5d70a3706e67.png)

TC 4.2.3.4, Forge 1291, nei 1.0.3.56, chickencore 1.0.3.26, baubles 1.0.1.10

This installation of minecraft had other mods added and removed until only the listed ones are present, the world that this is happening was created after the other mods removal, with only a couple of TC updates applied if this makes a difference.

**Comment by Azanor** [comment]
Firstly: SotE doesn't have a bonemeal function. Right click places more blocks like the one you are clicking on if you have them in your inventory.
Secondly: You seem to be in creative. In creative mode you don't need items in your inventory - it just places whatever you click on.

**Comment by ThePB** [comment]
... I'm an idiot :D
