### ISSUE TITLE
Impossible to craft Void Aspected Primal Staff

### ISSUE THREAD

**Issue by twothe** [Azanor/thaumcraft#1591]
Even with a Void Aspected Silverwood Scepter it is impossible to craft a Void Aspected Primal Staff as the Vis required is just too high.

![viscost](https://cloud.githubusercontent.com/assets/1131621/6094121/0cf5c238-af1d-11e4-88fe-18831763c683.jpg)

If you attempt to craft a primal scepter (i.E. with gold caps which is possible), the result cannot be placed on an Arcane Table, because it is considered to be a staff for crafting purposes (and a scepter if you try to attach a focus, which then fails).

I would have expected to be able to put the primal scepter on the crafting table at least.

_Edit:_ Tried again in maximum vis reduction setup, still not enough.

**Comment by igoutta** [comment]
Crafting the Uncrafteable https://www.youtube.com/watch?v=BqEy8CQN-5U

**Comment by twothe** [comment]
You are using a bug to craft the staff by using a dropper to force a staff into the crafting table which would normally not be possible.

**Comment by forsaken1111** [comment]
#1024

**Comment by KlutzLament** [comment]
What you have crafted is a staff-scepter, it can neither be placed in an arcane workbench or be used with wand foci. It is only good as a vis battery or to craft in-world structures. #1519

**Comment by twothe** [comment]
I see this has been resurrected a few times already, didn't find that bug when I searched GitHub. ;)

Maybe if this is intentional it would be a good idea to add a short line to the description text saying something like "You might not have the power yet to craft the most powerful staff and wand cap combinations you can think of."

**Comment by MentalMouse** [comment]
This has been a known limit since the primal staff core was released.  Azanor has occasionally hinted about future developments that would make it possible, but given he's turning his attentions to 1.8, it's liable to get bumped to that.
