### ISSUE TITLE
Crucible Issues

### ISSUE THREAD

**Issue by commonsensei** [Azanor/thaumcraft#1593]
Player on my server is able to duplicate buckets in a crucible. He let's the water get down to about 1/3 of volume and simply right-clicks it with a bucket. This gives him an extra bucket. I attempted to reproduce the bug in my crucible with no success but another player also has mentioned his excess of buckets.

Second, as of 4.2.3.4, right-clicking my empty crucible with a bucket fills the crucible as expected, but also produces a source block of water on top of the crucible.

Note: I also switched the server over to Cauldron so that may also be the cause.

Edit: I'm on forge 1291 if that matters. The server is on forge 1240.
Edit 2: Seems it'll work even time, regardless of the fullness of the crucible. Just hold right-click on the crucible and it gives you another bucket.
Images
![minecraft_1 7 10_2015-02-07_18-56-01](https://cloud.githubusercontent.com/assets/9263219/6094859/a5117f02-aefb-11e4-87c5-3b5298c79ca8.png)
![minecraft_1 7 10_2015-02-07_18-56-03](https://cloud.githubusercontent.com/assets/9263219/6094858/a510bc70-aefb-11e4-92ec-884bc3ef3800.png)

**Comment by MentalMouse** [comment]
IIRC, that's a known and somewhat infamous Cauldron bug.

**Comment by OJwithC** [comment]
Not sure if my server uses Cauldron, but yes, I get the water source block when filling a crucible and extra buckets if there is an empty space in my hotbar.

**Comment by commonsensei** [comment]
Hmm. I'll flip through all the config files and see if I can't find something.

**Comment by Azanor** [comment]
Known cauldron issue.
