### ISSUE TITLE
Crash after covering all faces of an amber block

### ISSUE THREAD

**Issue by Tuhljin** [Azanor/thaumcraft#1597]
If you place an amber block on the ground and then cover it on all sides with a solid, opaque block like grass or cobblestone, the game crashes upon covering its last face and attempting to load the world will also result in a crash. I was able to replicate the problem on a world with no mods besides Thaumcraft, Baubles, and CodeChickenCore.

http://pastebin.com/aSCKWG0M

**Comment by Tuhljin** [comment]
I just realized that test instance was using an older version of Thaumcraft. However, the same problem occurs with the latest release. Also, I've managed to place things over the amber with it not crashing sometimes. For a reliable crash, generate a flat world, place the amber directly on top of the grass, then cover it its other sides (including the top) with cobblestone or grass.

**Comment by Nentify** [comment]
Seems these crashes are fairly common in 1.7.10... Is this a recent change in Forge or something causing this? Had issues in Tinkers & Chisel fixed which had the same crash issue with completely covering transparent blocks.

https://github.com/TheCricket/Chisel-2/issues/200
https://github.com/SlimeKnights/TinkersConstruct/issues/1362

**Comment by Xfel** [comment]
See also https://github.com/MinecraftForge/MinecraftForge/issues/981. Note that an actual fix has been submitted as PR but was ignored.

**Comment by Tuhljin** [comment]
I thought the latest version of Thaumcraft fixed this, and my tests after it came out seemed to confirm that, but suddenly I'm now seeing the same crash again. To reproduce, create new world, dig a one-block hole in the ground, put amber in it, cover the amber block with a grass block. It doesn't seem to crash absolutely anywhere you dig the hole, but repeating this a few times around spawn always found a spot where it did for me.

http://pastebin.com/KC4VtebH
