### ISSUE TITLE
Two issues with Thaumcraft

### ISSUE THREAD

**Issue by galaxy119** [Azanor/thaumcraft#1598]
I'm running on Resonant Rise 3 Modpack minecraft version 1.7.10

I'm relativly new to minecraft and thaumcraft so if this is some kind of obvious mistake please point it out nicely..

I have an infusion altar, that I have used successfully several times (I have my thaumium capped silverwood wand, alchemy and sorting golems, etc). I tried crafting the Girdle of Runic Shielding and it won't start the infusion. I've ensured all required items are on the pedastals, I've made sure all the required essentia is in void jars nearby. I literally used the altar 5mins ago to make the alchemy golem, I haven't even put him to use yet, nothing else has changed, yet when I click the matrix with my wand, nothing happens at all.

I tried doing another infusion with is after failing to start the girdle one, and it worked perfectly fine. (I did a Wand Focus: Uprising infusion)

Second subject, not so much an issue as a request.. Can you make the Alembics pull from the furnaces faster? If you use say, greatwood to get magic essentia for thaumium ingots, you get such an excess buildup of arbor that even with a void jar attached to each alembic stack just for the arbor to drain into, the furnace stacks up with is so much that it took me 7hrs to make 25stacks of Thaumium with my golem setup, where it only took me 35mins to make 50 stacks of nitor

**Comment by galaxy119** [comment]
Side Issue I just noticed.. The Wand Focus: Uprising, doesn't do anything if you right-click. nothing at all. wand doesn't even shake.

**Comment by galaxy119** [comment]
None of the Runic Charge infusions work for me at all, i've tried all 3 (neck, ring and girdle) and none of them worked. They don't do anything at all

**Comment by OJwithC** [comment]
Are your scribing tools freshly made, or just refilled?

Have you tried using alumentum to burn things in the Alchemical furnace?

And Uprising is from Thaumic Tinkerer. (Though assuming you have the vis, you /should/ be able to hold right click to fly in the direction you are facing.)

**Comment by galaxy119** [comment]
Freshly made scribe tools, I only use alumentum as fuel for furnaces etc. the mundane girdle is fresh aswell, never worn so no durability loss.

For the wand, I have 100 aer vis (is says it takes .25 per cast) when I right-click, shift right-click or any other click, nothing happens

**Comment by MentalMouse** [comment]
Did you retry the girdle infusion after doing the other one?  

Regarding essentia speed: For bulk infusions like greatwood, it may be worth labeling the Arbor alembic and piping it to a void jar.  With a little more technology, a bank of powered crystallizers can drain a furnace stack surprisingly quickly, and essentia reservoirs would be even faster.

That said, I usually don't worry much about speed, because my pattern is to dump stuff in the input hopper, hook jars up to the centrifuge, and go do other stuff while the golems deal with it.  Also I try to keep up stocks ahead of time, thinking ahead to what I'll be making soon.

**Comment by MentalMouse** [comment]
Considering the altar thing:  Missing essentia would not prevent the infusion starting ... *unfortunately*.  

If it's still just that recipe, the issue has to be with the items.  Could one of the items (gold ingot?) be a ringer from another mod?  Try stashing the unstackable components in a chest somewhere and try with a freshly-made set.

**Comment by shobu9** [comment]
@galaxy119 Reasonant Rise has some personal configs and scripts to make multiple mods work together, So alot of bugs and little baubles happens it is not an issue realted to thaumcraft itself

**Comment by galaxy119** [comment]
Ok sorry for lack of responses. update.

Apparently it was some kind of glitch because I used EMC made scribing tools. I have re-made them the normal way and it worked fine. Yet using EMC'd scrib tools hasn't interrupted any other infusions thus far, only that specific one.

As for the essentia thing - It is all automated with golems, i put the materials needed for the construct in 1 of 3 chests depending which furnace/construct it goes into and golems take care of the rest. I will look into the crystalized stuff, aswell as digital and figure all that out, it was just taking an absurdly long amount of time for my golems to make Thaumium Ingots because of that bottleneck.

And for the Uprising focus, I've written it off as a lost cause, between the thaumostatic harness (rarely used) and the sword of the zephyr I have what little flying/hovering I need taken care of. It's likely something Resonant had to disable to keep other mods happy. Or perhaps maybe because so many servers disallow flying anyways? idk. 

IMO We need a teleport focus more than a flying one, what should be a thing.

**Comment by ThePB** [comment]
> And for the Uprising focus
... i find it strange that nobody pointed out that it's from Thaumic Tinkerer and not from Thaumcraft....

**Comment by Zsashas** [comment]
OJwithC pointed out that it's from TT in a previous comment.

Forbidden Magic adds a Blink Focus, but I can't remember whether that's in the current RR...

Also TT Foci are buggy in general due to lack of updates for the current TC.
