### ISSUE TITLE
Crimson Cult Banner

### ISSUE THREAD

**Issue by T4ge** [Azanor/thaumcraft#1600]
Mainly just more of a heads up if you plan to use the same banners as for 1.7.10 in 1.8 when you get to updating
I would suggest making them go down instead of up, just because.. idk seems more reasonable to me honestly.
And do a check if there's actually room for it.

![image](https://cloud.githubusercontent.com/assets/8440488/6109835/14da4cf0-b07e-11e4-9838-ed038f5a9ab4.png)

**Comment by igoutta** [comment]
Same problem with Nevermine. Problem? one block hitbox height. Excuse my english.
