### ISSUE TITLE
Client crash when connecting to Cauldron server

### ISSUE THREAD

**Issue by the-ible** [Azanor/thaumcraft#1601]
The client logs off the server with no errors or crash.
When the client attempts to log back onto the server we see logs like the following two examples.
http://pastebin.com/xA7KvqMr
http://pastebin.com/hYGBCSym

I decided to create the issue here rather then on the Cauldron issue tracker because the crash logs always list a Thaumcraft item.

By deleting the player's Playerdata file named after their UUID the player is then able to get back on the server.
It seems that somehow the world playerdata file is getting corrupted when the player exits the game.
I am not saying this is a Thaumcraft issue as the root cause. But Thaumcraft items are named in the crash log.

Please look over the attached playerdata files and if this is not a Thaumcraft issue at least you could indicate what is getting corrupted in the playerdata file and I'll create a Cauldron issue.
https://dl.dropboxusercontent.com/u/51194434/Minecraft/CorruptPlayerData/56dfbce8-3f48-498f-a2f5-20798264957a.dat
https://dl.dropboxusercontent.com/u/51194434/Minecraft/CorruptPlayerData/96c798a6-741f-43d1-9b04-b44f38a22e29.dat
https://dl.dropboxusercontent.com/u/51194434/Minecraft/CorruptPlayerData/e02e1758-6712-47f3-b65b-df8abb85f1b9.dat
https://dl.dropboxusercontent.com/u/51194434/Minecraft/CorruptPlayerData/e210c089-3533-46d7-8319-b06b8e6c11e0.dat

**Comment by ThePB** [comment]
You can just disable waila in the client and it should be able to connect...
Unless the issue i'm linking it's not related at all :D

https://github.com/Azanor/thaumcraft/issues/1541

**Comment by the-ible** [comment]
Similar issue reported on Waila Issue Tracking system
https://bitbucket.org/ProfMobius/waila/issue/148/crashing-when-loading-world

**Comment by Azanor** [comment]
Looks like it will be fixed in the next release of Waila.
