### ISSUE TITLE
Essence Berrys & Harvest Golem not picking anything up.

### ISSUE THREAD

**Issue by benten2000** [Azanor/thaumcraft#1603]
Checking if this is a possible bug with either Thaumcraft / CompactMachines mod or a bit of both with this problem.

I have a TinkerConstruct XP essence berry farm in a CompactMachine (which is technically a new age/world of sorted DIM#) with a wood golem using the harvest core to pick up the fully ripe Essence Berries.

He goes through the motion of it but no berries appear like that do normally.
For a test to see if it was possibly CompactMachines that has the problem I tried with an autonomous activator underneath the bushes to see if the berries appear which they did so unsure what mod could be causing this bug.

Using MC 1.7.10
Forge 10.13.2.1307
Thaumcraft 4.2.3.4
CompactMachines 1.17
Tinkers Construct 1.8.2

**Comment by Azanor** [comment]
Does the golem work in the overworld?

**Comment by benten2000** [comment]
Yeah it works in the overworld and in a void age.

**Comment by Azanor** [comment]
The issue is more than likely related to the way CompactMachines works. You might wish to report it there as well.

**Comment by benten2000** [comment]
Will do, just wanted to be sure and post a report on both mod issue page to be safe.

Thank you for your assistance Azanor
