### ISSUE TITLE
Crash-report

### ISSUE THREAD

**Issue by MrHelp** [Azanor/thaumcraft#1604]
http://pastebin.com/jM1L0Qq8

**Comment by ThePB** [comment]
Duplicate of this? https://github.com/Azanor/thaumcraft/issues/1550

**Comment by MrHelp** [comment]
I think no. We have 4.2.3.4 verison ThaumCraft and this crash has when people create too much warned block in one chunk. I delete this blocks and they can login again.I don't know how it work but..

**Comment by Azanor** [comment]
It is the same error. Closing this and referencing it in the other report.
