### ISSUE TITLE
Alchemy Golems do not transport essentia from the whole stack of alembics when attached to a alembic

### ISSUE THREAD

**Issue by RAnders00** [Azanor/thaumcraft#1605]
TC 4.2.1.4
Forge #

The Thaumonomicon says they are able to do that, the reality is different (they cannot).

I am not able to test with the newest versions. I guess it would only take you a few minutes to test it on the latest versions, so please, kindfully test it for me on the newest versions.

**Comment by OJwithC** [comment]
Try attaching the golem to the alchemical furnace, not the alembic.

**Comment by RAnders00** [comment]
It says in the Thaumonomicon that that should be possible. I am aware that attaching it to the Alchemical Furnace works.

**Comment by Azanor** [comment]
I'll take a look.
Just curious, but for what reason do you want to attach it to an alembic instead of the furnace?

**Comment by Azanor** [comment]
Just tried it myself and it works fine for me. Could you post a screenshot of your setup showing the golem link lines?

**Comment by RAnders00** [comment]
They pull from the one they are attached, yes, but it says in the thaumonomicon that they pull from the entire stack of alembics, but they do not pull from the entire stack!

Demonstrated in a video: https://www.youtube.com/watch?v=5nHt5bGyC8I&t=50s
I also show that I only use the latest thaumcraft and forge.
(TC 4.2.3.4 Forge #1291)

On my server (cauldron) they do not even extract essentia from the one attached to. I'm going to assume that you do not support cauldron, that's why I'm not focusing on that anymore.

**Comment by Azanor** [comment]
It will pull from the entire stack only if placed on the furnace. It may not be clear in the text, but that is what is implied.
