### ISSUE TITLE
Alchemy Golem not working with void jars

### ISSUE THREAD

**Issue by Nighthawk08** [Azanor/thaumcraft#1608]
So yesterday I had a working Alchemy Golem working on unlabeled Warded Jars. But I don't like to deal with ten plus jars of Arbor, so I usually upgrade the jars to Void Jars. After much time recharging wands and waiting on nodes to refill, my golem is not depositing essentia to unlabeled void jars. I attached a picture of the golem holding some Cognito aspect and the rows he is supposed to deposit it to.
![golem issue](https://cloud.githubusercontent.com/assets/10984739/6179289/9b242100-b2cc-11e4-9782-d44e26e04fc5.png)

**Comment by ThePB** [comment]
It's intended. you have to either label the void jars with the aspect that you want to void or fill them directly from an alembic of with a vial (even a single point is enough). The golem will then work.
This way the golem will know that you actually want to get rid of that particular aspect.

**Comment by OJwithC** [comment]
Did that not change in 4.2.2.0? (Honestly haven't played with them since before that, but the change log says "Alchemy golems will now fill empty void jars as their lowest possible priority." )

**Comment by ThePB** [comment]
Uhm, you are right about the changelog. So accustumed to answering like that that i've not noticed that entry :/ Sorry :D

**Comment by Nighthawk08** [comment]
Oh, it looks like Direwolf20 pack is outdated then. I am still on 4.2.1.4 so that's why it isn't fixed yet.
