### ISSUE TITLE
Client Crash - IndexOutOfBoundsException - potionHelper/Aspects/Confused

### ISSUE THREAD

**Issue by Labs4077** [Azanor/thaumcraft#1610]
Not sure if this is reported somewhere already, if it was I was unable to find it. Client crashes on startup 9 out of 10 times with this crash report. Happens with version 4.2.3.0 and 4.2.3.4.

Crash Log
https://gist.github.com/Labs4077/0187d1cdc00cdf4a3c62

Client Log
https://gist.github.com/Labs4077/488fa90ffd3225713e78

**Comment by TheMadmanofChaos** [comment]
Odd, this looks to be a potion ID error, caused by having an effect with an ID over 127(The hard coded limit). Mind removing thaumcraft, opening a test world,  and creating an NEI data dump for potions?

**Comment by Labs4077** [comment]
I have several addons in my pack for Thaumcraft so removing it would be a bit of a task. So what I did was remove Brewcraft - a mod with many many potions. According to its config here are the ID's it uses for potions: 

    I:"'Angelic' Effect ID"=40
    I:"'Combustion' Effect ID"=42
    I:"'Eternal Flame' Effect ID"=46
    I:"'Fire Eater' Effect ID"=47
    I:"'Fireproof' Effect ID"=45
    I:"'Flight' Effect ID"=41
    I:"'Frozen' Effect ID"=44
    I:"'Immunity' Effect ID"=43
    I:"'Poison' Effect ID"=48
    I:"'Regeneration' Effect ID"=50
    I:"'Wither' Effect ID"=49

Here is the NEI Dump for potions minus brewcraft:

https://gist.github.com/Labs4077/4e9465218d23bb3029eb

There is a large amount of unused ID's so now I am very confused.

**Comment by TheMadmanofChaos** [comment]
Looks like the brewcraft ID"s would be conflicting with witchery ID's, and you have a few out of bounds. You need to shift the botania, biomes o plenty, and minechem ID's down bellow 127. Fix these, and then see if it still crashes.
