### ISSUE TITLE
when i launch minecraft my game crashes

### ISSUE THREAD

**Issue by THEVOLCO** [Azanor/thaumcraft#1611]
here is the crash report:

http://pastebin.com/7uc2gUmK

**Comment by TheMadmanofChaos** [comment]
First bet is on an add on causing this with an outdated API. Red flag is the DragonAPI, so see if it has an update or go with the other solution of opening that mod's folder and removing/deleting a file named "Thaumcraft". Should fix this in theory.

**Comment by Azanor** [comment]
Yup, that is more than likely the issue.
