### ISSUE TITLE
Node bullying problem

### ISSUE THREAD

**Issue by Hazado** [Azanor/thaumcraft#1612]
I have started using Automagy for its vis reader and sometimes when a node bullies another it adds a point of vis to the base vis, but not to the current vis. This causes the node to never grow any vis for that particular vis. The problem with this is automagy's vis reader sees this base vis and thinks there is vis there and waits for it to grow when it will never grow. Depending on the settings of vis reader this causes problems.

Problem is its not assigning the vis to the current vis correctly.
You can check this with nbtedit in game.

**Comment by Hazado** [comment]
Here is a screenshot of the issue
![untitled](https://cloud.githubusercontent.com/assets/416114/6201272/0dc931ea-b454-11e4-8054-8c5a10707116.png)

**Comment by Azanor** [comment]
That is exactly how node bullying works, so I don't see what the problem is.
