### ISSUE TITLE
Crucible causes crash

### ISSUE THREAD

**Issue by Double26** [Azanor/thaumcraft#1615]
I've run into a bug that I believe is caused by the crucible. My world crashed when I accidentally walked on top of it while it had some essentia in it. I was wearing free runners from mekanism which caused me to step on top of the crucible. Every time I load it, it would reply with "Shutting down internal servers". I removed thaumcraft and it fixed the problem since I was no longer on top of the crucible.

http://pastebin.com/aQzJ4dH4

Thaumcraft Version
4.2.3.4 & 4.2.3.3
Forge Version
10.13.2.1277

**Comment by ThePB** [comment]
> ---- Minecraft Crash Report ----
// Oh - I know what I did wrong!
Time: 2/14/15 9:52 PM
Description: Unexpected error
java.lang.NullPointerException: Unexpected error
at eu.ha3.mc.presencefootsteps.mcpackage.implem.AcousticsManager.playStep(AcousticsManager.java:56)

i'd go to report to presencefootsteps this crash, if i were in you. And while you are at it, avoid stepping on crystals clusters too.

**Comment by Azanor** [comment]
Yup, that is not a TC crash. It seems it is trying to play a sound that does not exist.
