### ISSUE TITLE
Golems can replant unnaturally far

### ISSUE THREAD

**Issue by soundlogic2236** [Azanor/thaumcraft#1617]
I have a bunch of golem farms which are each 9x9 with a harvest golem with replant in the middle of them. Each farm is seperated by a 3 wide space of wood. Despite this, the harvest golems are somehow managing to contaminate each other's farms. Not only does it seem odd that they would be able to replant through a 3 wide space of wood, they are replanting outside the area they can normally interact with at all. 

EDIT: I have done additional experimentation, and it seems that the golems are pulling from other farms when replanting, not spreading it themselves. Also, it is able to work through a distance of 5 blocks. I have not yet tested with 6. This seems very problematic for setting up focused golem farms, which is very disapointing

EDIT 2: They are also able to do it through two thick four high solid wood walls, which is sort of impressive I guess.

**Comment by Azanor** [comment]
More than likely seeds are falling close enough to another farm for the harvest golem to pick it up when it attempts to replant.

They way this code works will change in 1.8 so you will have to live with it for now.
