### ISSUE TITLE
golem not moving 

### ISSUE THREAD

**Issue by brownie720** [Azanor/thaumcraft#1633]
i have a straw golem with the alchemy on and bound to an alchemical furnace he takes the essence out but dose not move to the marked jars

**Comment by ThePB** [comment]
Thaumcraft version? Single player? multiplayer? Modlist? screenshots?

General Know Causes:
If you are on Version earier than 4.2.2.0 and using void jars, you have to either label the jars or "prime" the same jars by filling them with some essentia.
If using a later version, check the config file for the I:golem_delay line. 5 is default value, some users have reported weird behaviours from golems if the value has been set > 20. Note, on a server is the server config that counts.

**Comment by brownie720** [comment]
I'm on a sever using Thaumcraft version 4.2.3.5 and it was the config settings the I:golem_delay line was set to 60 for some reason. Thanks
