### ISSUE TITLE
Thaumcraft Dev

### ISSUE THREAD

**Issue by yesimwearingpants** [Azanor/thaumcraft#1636]
I was looking for a thaumcraft dev build and found this https://github.com/Azanor/thaumcraft/issues/786 but thats a little out dated. Where can I go to get a newer one?

**Comment by ThePB** [comment]
For this kind of questions it's better to go directly to the minecraftforums thread. That, btw, should also contain the files that you are looking for in the first page, right after the normal version :D

**Comment by yesimwearingpants** [comment]
Thanks
