### ISSUE TITLE
Vis Relay Losing Connection On Unload

### ISSUE THREAD

**Issue by commonsensei** [Azanor/thaumcraft#1641]
I have no other vis relay connected to this energized node. For whatever reason, the first relay loses connection with the second and I have to replace it to fix the issue.
![minecraft_1 7 10_2015-02-24_19-56-15](https://cloud.githubusercontent.com/assets/9263219/6364155/8b45116c-bc5f-11e4-971e-82407914afdb.jpg)
![minecraft_1 7 10_2015-02-24_19-56-32](https://cloud.githubusercontent.com/assets/9263219/6364156/902a0638-bc5f-11e4-8ad8-b2b1ea3a23b4.jpg)
![minecraft_1 7 10_2015-02-24_19-56-42](https://cloud.githubusercontent.com/assets/9263219/6364157/92a54a58-bc5f-11e4-8df3-d17350907846.png)
![minecraft_1 7 10_2015-02-24_19-55-52](https://cloud.githubusercontent.com/assets/9263219/6364158/9414dc14-bc5f-11e4-9e4e-f7fbe1177626.jpg)

Off-topic suggestion: it would be neat if there was a block version of pipes so we can have flush walls. It is unsightly seeing into the room over.

**Comment by Azanor** [comment]
Known issue reported a million times. See the others issues for my response.
