### ISSUE TITLE
Client Crash Help

### ISSUE THREAD

**Issue by DrakeBD** [Azanor/thaumcraft#1645]
I have the log form a client crash on our server from one of the players hope you can help with this
https://dl.dropboxusercontent.com/u/38820381/crashlogs/Lucas%20Thaumcraft%20client%20crash.txt

**Comment by TheMadmanofChaos** [comment]
There is a config option named "glowing_taint=true ". Change that to false, then see if this still happens.

**Comment by DrakeBD** [comment]
Ok thanks for the info I shall try that
