### ISSUE TITLE
1.7.10 too small, unreadable font in thaumonomicon

### ISSUE THREAD

**Issue by NoX-programer** [Azanor/thaumcraft#1647]
Can't see amount of essence needs for crafting craft/infuse stuff: http://i.imgur.com/pXWzk6w.png
Can u make font size configurable or just bigger?

mods&versions:
forge-1.7.10-10.13.2.1291-universal.jar
Thaumcraft-1.7.10-4.2.3.5.jar

**Comment by robmart** [comment]
I tested this and it works just fine for me

**Comment by NoX-programer** [comment]
Glad for you.

**Comment by Azanor** [comment]
Try a different UI scale.

**Comment by NoX-programer** [comment]
If the problem was solved so simply, I would not have written here. I do not know why but my GUI is not scaling when I switch to Large and to Auto - it's same as Normal. I do not know what to blame - screen resolution (1024x768 and 1280x1024 have this problem) or Forge version or modpack, but one problem generates another, and so I ask to do something with your (only one which problematic) font.

**Comment by oldjunyi** [comment]
Try this: http://pan.baidu.com/s/1hqh9spe#path=%252FUnicode%2520Font%2520Fixer
This is a small mod to enlarge some text size for Unicode font user.
It works on current version of Thaumcraft, Forestry and several other mods.
