### ISSUE TITLE
Thaumcraft 4.2.3.4 Harvest Golem Order Core Issue

### ISSUE THREAD

**Issue by AryuSyrius** [Azanor/thaumcraft#1648]
So I have this tower of farms. One each layer is a different crop, from the Magical Crops mod. The layers are separated by 5 air blocks. Somehow, the harvest golem, is getting the seeds from the farm above/below it. This of course throws of my production rates. The farm layers are completely sealed off from on another. Any idea how the golems would get getting seeds from the other farms? Are they able to reach that far?

**Comment by Azanor** [comment]
When they replant they look for dropped seeds with a certain radius. Some seeds may be dropping close enough for the "wrong" golem to pick it up.
