### ISSUE TITLE
Changing name resets research

### ISSUE THREAD

**Issue by jilleJr** [Azanor/thaumcraft#1653]
Title speaks for itself.

Mojang recently introduced a way to change your in game minecraft name, and if you do so your thaumcraft research gets reset.
More precicey it thinks youre a new player and so it creates a new save for the research.

This happened when on a server, don't know if it does in single player.

**Comment by Azanor** [comment]
Just rename the old research file to your new name.

**Comment by jilleJr** [comment]
The point was that on some servers you might not be able to do that. So if you would switch from using username to the user id or something that would be great

**Comment by forsaken1111** [comment]
It has been reported several times. Search closed issues next time

**Comment by jilleJr** [comment]
@forsaken1111 Well excuse me. Will keep in mind

**Comment by forsaken1111** [comment]
If you had searched you'd have seen that your suggestion has been considered and rejected, and for what reason. This pops up again and again. I didn't mean anything negative towards you personally, just suggesting that it may save you time to search previous issues.

**Comment by forsaken1111** [comment]
#1581
#1518

in case you are curious :)
