### ISSUE TITLE
Flux Scrubber causing weird VisNet errors

### ISSUE THREAD

**Issue by rfox90** [Azanor/thaumcraft#1657]
Hi,
Thaumcraft-1.7.10-4.2.3.4

I'm one of the admins from @Nentify 's server.

We're experiencing intermittent crashes with the following crash log: http://pastebin.com/Z8uPfA6q

Looks quite bothersome as an infinite loop

Based on the coords and block name from the log It seems to be a Flux Scrubber.

Here's an image on the area in question:
![Flux Scrubber Area](http://ahref.co.uk/u/r/CBs0C.png)

We can provide any other info you need :)

**Comment by Azanor** [comment]
Sorry, but since I'm not updating the 1.7.10 version anymore and the visnet is going aways in the 1.8 version you are stuck with this. Maybe avoid using the scrubbers for now.
