### ISSUE TITLE
Primal crusher not working with UB rocks.

### ISSUE THREAD

**Issue by Pelemesh** [Azanor/thaumcraft#1659]
When using crusher on any UB stone it doesn't mine 3*3, only one block like pick does.

**Comment by Azanor** [comment]
UB?

**Comment by Adaptivity** [comment]
https://github.com/mallrat208/UBC-Ore-Registrar

**Comment by Pelemesh** [comment]
Underground Biomes mod*

**Comment by Pelemesh** [comment]
Also, link to this mod. Im using version from jan 29'th.
http://minecraft.curseforge.com/mc-mods/72744-undergroundbiomesconstructs/files

**Comment by Pelemesh** [comment]
Got no answer, needs info tag is still here.

**Comment by Azanor** [comment]
The crusher only mines similar blocks in a 3x3 area (similar internally). Looks like the UB blocks don't count as that. Not much I can do about it.
