### ISSUE TITLE
Corrupted Recipe

### ISSUE THREAD

**Issue by Carbon-Key** [Azanor/thaumcraft#1662]
Hello,

Hopefully this is a non-issue, just wanted to post this here on the off chance that it would be helpful.  A pastebin of log excerpts can be found at http://pastebin.com/UuRPNSME.  If you are curious about what mods are also installed http://pastebin.com/igU63Sjy should be a modlist.

I was running Thaumcraft 1.7.10-4.2.3.5 alongside Hardcore Ender Expansion (HEE) 1.7.1 when HEE stopped the initialization stating that "A defective recipe has crashed the game! Another mod is creating recipes with non-existent blocks or items, which is a serious error that will cause item or even world loss when crafting these recipes. Corrupted recipes have been saved in the log with tag [HEE-ORB], please try to find which mod they belong to and report them to the respective modder."  I found it odd that the mod author of HEE took it upon himself to add such an exception but I looked at the log file and saw that the recipe contained [Thaumcraft]item.ItemResource/6, which I believe is Amber? The recipe did not jump out at me as one I recognized, nor was it one I could find in the Thaumonomicon. I also didn't know what [minecraft]tile.cloth/32767 was supposed to be.  I tried out wool and carpet in the configuration below but it did not seem to be a recipe.
![2015-03-07_04 41 51](https://cloud.githubusercontent.com/assets/10481639/6540886/5417957a-c484-11e4-9242-2f00f0acab7d.png)

If you think it is nothing then I will just continue playing with the HEE exception disabled and assume it was a false alarm.  If you'd like any more information from me, please let me know.  Thanks for the awesome mod!

**Comment by Azanor** [comment]
Yeah, that is not a TC recipe I know. 
It is indeed a bit presumptuous on the author of HEE's side to stop the game loading because of that - many mods add recipes in funny ways which could cause false positives.

**Comment by Carbon-Key** [comment]
Thank you for your response! I will inform the HEE author that I've apparently gotten a false positive on that and in the meantime i'll just keep his exception disabled.  Loving Thaumcraft by the way, keep up the awesome work! :D

P.S. Just out of curiosity, did you happen to know what the cloth item was? Was I correct in assuming that it was wool/carpet?  Just thought it would be nice to know if I ever encounter it again. :P

**Comment by chylex** [comment]
It's not me purposefully stopping the game from loading, it's vanilla code crashing on ItemStack.getItemDamage() when HEE goes through the recipes, so I made it generate a user-friendly error and logged the crashing recipe. If you can't identify the recipe, it's probably from some TC addon.

**Comment by OJwithC** [comment]
Found what the recipe is for. Using wool blocks in a normal crafting bench should make a Thaumaturge's Backpack from the Magic Bees mod.
