### ISSUE TITLE
Greatwood planks interact oddly with redstone

### ISSUE THREAD

**Issue by justicesays** [Azanor/thaumcraft#1665]
redstone dust interacts oddly with greatwood planks compared to other wood
![2015-03-09_01 00 29](https://cloud.githubusercontent.com/assets/10358888/6548654/e140cea2-c5f7-11e4-9d7c-ab0c4275db61.png)
![2015-03-09_01 00 29](https://cloud.githubusercontent.com/assets/10358888/6548655/ea46e40a-c5f7-11e4-929c-ea8ecb617465.png)

Redstone connects to greatwood planks without any redstone on top, but it doesn't transmit the redstone signal from the button to the adjacent redstone. Unlike dark oaks planks, which don't connect redstone but do transmit the redstone signal
![2015-03-09_01 05 05](https://cloud.githubusercontent.com/assets/10358888/6548667/7b4c0e76-c5f8-11e4-8943-81401a9bf7dd.png)

**Comment by Azutte** [comment]
See also: rednet cables

**Comment by Azanor** [comment]
This is an old, known issue that will be fixed in the next version.
