### ISSUE TITLE
Translucent hand bug.

### ISSUE THREAD

**Issue by LuanCenation** [Azanor/thaumcraft#1667]
when I get close to something created by thaumcraft ( 4.2.3.5 1.7.10 ) , the hand of Steve becomes transparent .

**Comment by LuanCenation** [comment]
![2015-03-10_20 03 35](https://cloud.githubusercontent.com/assets/11411737/6587308/606932ae-c761-11e4-9fcd-653a5affa6b1.png)

**Comment by MalkContent** [comment]
can you give your modlist?

**Comment by LuanCenation** [comment]
I already tested only with thaumcraft but continued the same thing, do not think the problem is with the battle gear because I used them together in other versions .
ps: sorry for any errors but I am Brazilian and use the google translator .
![2015-03-12_13 15 07](https://cloud.githubusercontent.com/assets/11411737/6623722/9383c0ce-c8c3-11e4-9e08-1a2f2ee8464a.png)

**Comment by LuanCenation** [comment]
![2015-03-12_14 36 35](https://cloud.githubusercontent.com/assets/11411737/6624012/528c12d6-c8c5-11e4-8bdb-e476f6a24a01.png)

**Comment by MalkContent** [comment]
So absolutely no other mods at all? If so: weird.

**Comment by LuanCenation** [comment]
finally discovered , was projectred 's fault.
