### ISSUE TITLE
Breaking blocks with the Awakened Ichorium pickaxe

### ISSUE THREAD

**Issue by Decrepitdoors** [Azanor/thaumcraft#1670]
I'm Playing on the FTB Infinity Pack with some of my friends and we found a strange bug where breaking blocks with the AIP resets the meta data of some blocks, we found it on Thermal Expansion energy cells, tanks and strong boxes to no data so they turn into the creative equivilents.

**Comment by TheMadmanofChaos** [comment]
First, that pickaxe is added by thaumic tinker and not thaumcraft itself. Second, that has already been fixed in the thaumic tinkerer jenkins builds, found here: http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/
