### ISSUE TITLE
Infused Ores and Arcane Elevator render issue

### ISSUE THREAD

**Issue by Murlocking** [Azanor/thaumcraft#1672]
Using Colored Light Core (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445251-1-7-10-beta-wip-colored-light-progress-and) and Thaumcraft 4. 

Infused ores & Arcane Levitator render properly when viewed in NEI, but when placed in world the colored cracks in the Infused Ores render very dark.

**Comment by forsaken1111** [comment]
"When I use this beta work-in-progress mod it breaks thaumcraft rendering. Fix it!"

**Comment by Azanor** [comment]
Exactly

**Comment by Murlocking** [comment]
Though this was the place to report issues..
Other mod authors already implemented changed and fixed some of those rendering issues so both mods can be compatible. 
And if you're gonna quote me to make me sounds like I'm begging for a fix you can take your fingers and stick them to your butthole.

**Comment by forsaken1111** [comment]
So you didn't want it fixed, you were just letting Azanor know that an unrelated mod that alters the minecraft render also has issues with his mod?

**Comment by CptSpaceToaster** [comment]
Hi there, sorry for the trouble.  

CLC will stay in Beta until I can work on the rendering side of things and get them to a state where I can definitively state what needs to occur.  My goal is to intrude as little as possible, however I don't think I can maintain all of the vanilla rendering assumptions when I try to pass color-data through to my shader.

My worry is that I'll end up at a point, where I can't fix issues on my end anymore, and force other modders to play by a new set of rules.  I hope to minimize this effect as much as possible, and I apologize for the noise.  I'll change my OP and release pages to indicate not to bother other devs with my bugs.

Have a nice day.
