### ISSUE TITLE
Crimson Clerics don't drop armor

### ISSUE THREAD

**Issue by Fjolsvin** [Azanor/thaumcraft#1680]
By now I killed tens of Crimson Clerics, but still I don't have any single piece of Crimson Cleric armor (while I have many chests full of Crimson Knights armor). Could be something wrong with the drop rate of Crimson Cleric armor? I would believe it's just a misfortune after 10th Cleric, but not after 50th one.

**Comment by Azanor** [comment]
The droprate is the same for both. How are you killing them? They only drop their "rare" loot like armor when killed by a player, just like vanilla mobs.

**Comment by Fjolsvin** [comment]
I'm killing them the same way as the Knights, i. e. by sword (looting III). Well, they're only 4 per obelisk, but I wiped out 20 of them around obelisks and about 30 others in the Outer lands and as I said, having tons of Knight's armor, I have no single piece of Cleric's armor. I'll try to find another Portal in the Outer lands, kill some more and let you know.

**Comment by tschallacka** [comment]
We have multiple players running around with cleric armour. The thing is you only get 4 clerics per altar and we needed to kill about 50 of them to get a full set.

**Comment by Fjolsvin** [comment]
I've killed about 50 of them, as I mentioned above. No single piece of armor yet.

**Comment by Azanor** [comment]
It might just be the random number generator hating you. I just confirmed it is working fine for me.
