### ISSUE TITLE
Eldritch portal transparency glitch

### ISSUE THREAD

**Issue by Fjolsvin** [Azanor/thaumcraft#1681]
The Eldritch Portal has a transparency glitch, so any Eldritch Capstone behind it looks like it's actualy in front of it, see the image.
![eldrport](https://cloud.githubusercontent.com/assets/8334597/6677032/bc069988-cc2c-11e4-9cfa-1052e09493d1.png)

**Comment by Azanor** [comment]
Just MC rendering being MC rendering. Not much I can do here.
