### ISSUE TITLE
Not getting aspects when scanning, also can't combine them

### ISSUE THREAD

**Issue by N-kay** [Azanor/thaumcraft#1685]
Even though I believe this to be a cauldron-related issue, I thought I'd try to get some help here, maybe you can help me find a solution to this. Feel free to delete this though, as it's obviously against your guidlines.

Thaumcraft worked fine on the DW20 1.7.10 1.0.3 version, but I updated my server to 1.1.1 and now the aspects seem broken.
- Scanning items with a Thaumometer does not give aspects
- Combining aspects in the research table does nothing

Other than the fact that the mod works fine in singleplayer, I have nothing to point me to a specific cause. Please tell me if there's a way to get some useful info on this issue so I can post it here.

General info
Modpack: DW20 1.7.10 v1.1.1
Thaumcraft version: 1.7.10-4.2.3.5.jar
Tested with: 
cauldron-1.7.10-1.1236.05.212-server.jar
cauldron-1.7.10-1.1307.06.218-server.jar (unofficial fork)

**Comment by Azanor** [comment]
You should take this to the Modpack's help forums (or whatever) first. More often than not it is a issue on their side - especially since nothing like this has been reported before and that version of TC has been out for ages.
