### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xJon** [Azanor/thaumcraft#1686]
Is this crash is Thaumcraft's fault or Fastcraft's fault?
http://pastebin.com/jWHpQNMc

**Comment by Azanor** [comment]
Not sure - did you give yourself loot urns/crates using console commands or something similar? The game seems to be crashing when trying to render one with invalid metadata.

**Comment by xJon** [comment]
Well, it's not my crash, so I can't really know. But as I understand I guess that it's not really a bug. Anything you can do?

**Comment by Azanor** [comment]
Not really, no.

**Comment by xJon** [comment]
Okay.
Thanks for answering that fast.
Have a nice day! [:
