### ISSUE TITLE
Naturally Placed Greatwood Leaves cause framerate drop/chunk loading issues

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft#1687]
Going into areas with greatwoods (say ~6) in them takes a really long time to load, accompanied by big framerate drops.
Even after finally finishing loading, the framerate is still noticably lower.

This is apparently caused by the leaves, after removing them, the issue stops (won't vouch for it, though).
Artificially placed leaves do not cause this problem.

Tested in superflat creative, TC 4.2.3.5

**Comment by Azanor** [comment]
Its a complex issue, but their rendering will be 100% the same as vanilla leaves in 1.8 so this should be fixed. Silverwood leaves causes even more issues since they emit light, which I will also be doing away with in 1.8.
