### ISSUE TITLE
Vis relays triggering looping crashes with aura cascade

### ISSUE THREAD

**Issue by GreatOrator** [Azanor/thaumcraft#1689]
So I reported this to pixelpix, but he says it is not an issue with his mod so reporting here.

http://pastebin.com/iGfUwfCS

When placing one of aura cascade blocks near relay it crashes the client and/or server and in the case of a server with auto start, goes into a looping startup then crash until the block is mcedited out or chunks removed.

This is on latest thaumcraft version and version 279 or aura caacade.

Issue reported to pixel here: https://github.com/pixlepix/Aura-Cascade/issues/39

**Comment by Azanor** [comment]
Reported several times already. The short answer is: I'm not updating 1.7.10 TC anymore and since relays won't exist in 1.8 TC the problem is technically "solved".
