### ISSUE TITLE
Golem placing not following click conventions

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft#1690]
The general rule is that when you make a simple right-click on a block you can interact with, you interact with it, no matter the item in hand, and use the item/block in hand when you shift-right-click. With golems it's the other way around for no apparent reason.

**Comment by Azanor** [comment]
Use golems specifically use "something" on "something else" - that is their purpose. Any other behaviour is simply coincidental (like having them click on noteblocks with something).

**Comment by MalkContent** [comment]
I mean when a player places a golem. :|

**Comment by Azanor** [comment]
Ah, that makes more sense. I've tried to get golems to work like normal items, but they simply refuse and give me threatening looks. I'm scared to push the issue.

**Comment by MalkContent** [comment]
Hm. Well. Okay, but. Hmmm. Okay. Well. *dips another fez in chloroform* don't wanna disturb anyone fhtagning
