### ISSUE TITLE
Taint converts sand to dirt.

### ISSUE THREAD

**Issue by talonos2** [Azanor/thaumcraft#1694]
Currently, when sand is tainted, it turns into tainted soil. When tainted soil is cured, it turns into dirt. Thus, if you taint and then cure a desert, it becomes covered with dirt instead of sand.

Any chance you could make another taint block with a different metadata so tainted soil can "remember" it used to be sand and transform back correctly? I have a modpack that features a world completely covered in taint, and my players report confusion when cured deserts manifest as giant fields of dirt.

**Comment by dmportella** [comment]
Indeed that would be amazing. Is there a way to contribute to the mod pack?

**Comment by talonos2** [comment]
Depends on what your skills are. At the very least we could always use more players who are skilled at reporting bugs! But this isn't the place to talk about my modpack. Stop by the forum thread: http://bit.ly/1w1ytla and we can talk there. :)

**Comment by dmportella** [comment]
OK sounds good on regards to contributions I will have a chat with you on the forum thread.

**Comment by Azanor** [comment]
The way taint works will be changing in 1.8 so indirectly this will be fixed :)

**Comment by dmportella** [comment]
cool i am glad to hear.
