### ISSUE TITLE
Greatwood and Silverwood Slabs Uncraftable

### ISSUE THREAD

**Issue by MagmaFyre** [Azanor/thaumcraft#1697]
NEI shows the recipes for silverwood and greatwood slabs, but when attempted the recipes produce oak slabs. Is it possible the old recipe is overwriting the new one?

**Comment by MalkContent** [comment]
Shouldn't, unless you have something else recreating the old recipe. Maybe this is an issue with forge derping. Silverwood slabs are after all wooden planks and oak slabs still have the "3 planks of <any> kind" recipe, which of course includes 3 of the same kind. Oredict recipes should get overwritten by regular recipes though.
Check with NEI if silver wood planks have TWO recipes for sw planks to oak slabs.

**Comment by MagmaFyre** [comment]
Both have a recipe reading for oak planks and one for their own planks. The oak recipe comes earlier when scrolling through NEI if that helps. I'll try reinstalling Thaumcraft, the addons, and I'll generate a new config.

**Comment by MalkContent** [comment]
but you only have one recipe for silverwood->oakslabs, not two, yes?

**Comment by MagmaFyre** [comment]
Yes. Updating Bibliocraft solved the problem.

**Comment by MalkContent** [comment]
huh. okay then.
