### ISSUE TITLE
Water & bucket duplication

### ISSUE THREAD

**Issue by Radviger** [Azanor/thaumcraft#1699]
Hi, Azanor!
On my server I noticed that players can duplicate buckets when they filling crucible.
When I right-click with full water bucket on crucible it fills, but also the water places and I got a second empty bucket. It's really terrible! Can you fix it please?
Thanks!

**Comment by forsaken1111** [comment]
Is your server running on cauldron?

**Comment by forsaken1111** [comment]
#1593 #1278 #1098 #701 #1098
It saves a lot of time if you do a quick search of old issues and make sure yours isn't already reported.

**Comment by Radviger** [comment]
Thanks! But there is no way to fix it on my server?

**Comment by forsaken1111** [comment]
If your server is running on Cauldron then it's a known issue with Cauldron and you'd have to speak with them about fixing it.

**Comment by Radviger** [comment]
I know that Cauldron was abandoned by developers

**Comment by Radviger** [comment]
It's pain

**Comment by forsaken1111** [comment]
Sorry to hear that friend, but as far as I know this bucket duplication bug has nothing to do with Thaumcraft.

**Comment by Radviger** [comment]
Maybe I can fix that in cauldron's code. Can you say at least what method cause this bug happen?

**Comment by Radviger** [comment]
It's really hard ir impossible to use another method to fill crucible? For us there is no way to fix this, because, as I said - cauldron is abandoned

**Comment by Meegooo** [comment]
Actallly, it's very easy to fix using very simple bukkit plugin. You just catch PlayerBucketEmptyEvent and cancel it if blockClicked is crucible.
That's what I did for my server and it works.

**Comment by Radviger** [comment]
Thanks! Very helpful for me!
