### ISSUE TITLE
Eldritch portal leads to the void

### ISSUE THREAD

**Issue by ViciousVinnyD** [Azanor/thaumcraft#1701]
On my first and second portals the outer lands worked fine. However on my third portal 3 sections were missing but the boss and key were intact, and on my fourth the entire world was missing and I fell into the void.

I'm using DireWolf20 v1.1.1

**Comment by MalkContent** [comment]
since what version of tc are you playing the same world? there was an issue of the obelisks being to close at one point. if the fourth was generated during that time, void it is

**Comment by Azanor** [comment]
This sometimes happens if you try to enter through a portal that was generated before the eldritch dimension was added. Try and find an altar in unexplored terrain and it should work correctly.
