### ISSUE TITLE
Mod integration

### ISSUE THREAD

**Issue by masonpinder** [Azanor/thaumcraft#1708]
Would it be possible to make some type of variable that other mods could read, for the aura nodes. Like, so my computercraft programs can read how much aura is in one specific node. Or possibly Steve's factory manager. I was thinking if making a small build, where I had a computer show me how much my aura node held, but then couldn't think of any way to read its storage... Or even percentage of how full... Even a comparator thing to read how FULL it is, would be HELPFUL, but computercraft variable where it can read how much it could store, and how much it is storing, would be extremely useful. Sorry if this is a bad idea.

**Comment by masonpinder** [comment]
Nevermind on the thing about computercraft. I just found out that the peripherals proxy from the new remake of misc. peripherals can handle it. But, I still say that it would be neat to measure the percentage and things, without HAVING to use those mods. Or maybe steve's factory manager.

**Comment by MalkContent** [comment]
Other mods /can/ read the contents of aura nodes. They just have to support it, not the other way around. The best TC could do is add a redstone comparator readable value and that is not gonna be super helpful, considering there's a really big bunch of things you might want to read.
