### ISSUE TITLE
Mining focus not working in gamemode 2

### ISSUE THREAD

**Issue by Nexey** [Azanor/thaumcraft#1709]
Hello, this focus isn't working in gamemode 2. Now if you react as Chisel's dev, you'll not give a single fuck about it, thus you don't need to continue reading this and you can close this conversation.
GregTech has a hardmode config allowing us to play in gamemode 2, that way one can only break blocks with the right tools (Shovel for dirt, Pickaxe for Stone, Crowbar for nodes / taint, etc..).
I've noticed that because of the way the adventure mode works, this focus is only usable for the mining bore. Can you please apply a fix for this regarding TC4 ?

**Comment by Azanor** [comment]
Its specifically blocked for mode 2 since that is the way it is supposed to work. Sorry. 
Just because GT allows something doesn't mean that is the way it is supposed to work. That is more than likely why the chisel dev ignored this issue.

**Comment by Nexey** [comment]
As far as I know, I'm the user here, I'm not Greg, I'm the one willing to play a game harder, yet Greg adds many hard tweaks to the game.
I'm surprised people react over Gregtech, whereas I'm the first concerned by this suggestions.
Saying that "because GT allows something doesn't mean that is the way it is supposed to work" is ironicly the same sentence as "Water is wet". I don't have a single clue about what you've attempted to explain here.
Though, if you want it to be blocked for gm2 because it is supposed to work like that, fine, but than am I allowed to suggest a config option to allow one to use it in gm2, since I see no point of having such a tool blocked ?

**Comment by Azanor** [comment]
I'm not refusing to change it because of Gregtech - I'm refusing to change it since you are not supposed to be able to break blocks in mode 2. *shrug*

**Comment by Nexey** [comment]
Well you confused me on that point >.<
And we're supposed to, given the right tools, and that's vanilla. One can make a stone shovel mine dirt, a diamond shovel mine sand, and so on.

**Comment by Azanor** [comment]
You actually made me go into adventure mode to try it out, and no - no combinations of tools allowed me to mine anything, unless I am missing something fundamental.

**Comment by Nexey** [comment]
Than my knowledges on vanilla aren't as good as the one in researches, I thought that in vanilla you needed the correct tool.

**Comment by Azanor** [comment]
Specific items can be given a special tag allowing them to destroy certain types of blocks - that has to be put in by hand though (by the mapmaker or server admin). I am assuming greg is adding it automatically for some tools. 
Adding that tag to a wand should actually allow it to break whatever blocks it is allowed to, but that is up to the map maker/admin.

**Comment by Nexey** [comment]
That's true for 1.8, that's false for 1.7.10. In 1.7.10 you need the correct tools and you have the ability to place blocks.

**Comment by Nexey** [comment]
Confirmed : You've made your test in a 1.8 version of Minecraft, whereas TC4 is for 1.7.10 and in said version you need the correct tool in gamemode 2.

**Comment by SpwnX** [comment]
So the old #825 is still present :P

Everything that nexey said is true, btw.
Adventure mode on 1.7.10 is a different story from 1.8's
Pickaxes can only break stone-ore like blocks, Shovels can only break dirt-sand-gravel like blocks and so on. You can also place blocks freely just like gamemode 1.
The fun thing about adventure mode is that if you lose your items, or run out of a tool in the middle of nowhere, you're screwed {and that is pretty much true "realistically", you can't just punch your way to victory}.

**Comment by Azanor** [comment]
Indeed, I only looked at it in 1.8. However since I'm not working on the 1.7.10 version of TC anymore I guess the point is moot.

**Comment by hanakocz** [comment]
Wait, you work on 1.8 version of TC? So TC is the one from thousands, who updates to 1.8? All main other mods stay on 1.7.10 as I know. 
Well, it can only push the things forward, but still... :)
