### ISSUE TITLE
Aura Node Duplication

### ISSUE THREAD

**Issue by Radviger** [Azanor/thaumcraft#1713]
Hi, dear Thaumcraft developers!
On my server players found duplicate glitch:
(It wroking only with mobGriefing=false)
1) Put aura node into jar
2) Place jar
3) Break jar and blow up creeper nearly at the same time (Jar drops, but remains in the same place)
4) Done! You have two jars with aura nodes

**Comment by Radviger** [comment]
On which side is the problem?

**Comment by Azanor** [comment]
Not working on 1.7.10 version anymore and due to changes this problem will go away in the 1.8 update, so closing this.
