### ISSUE TITLE
Warded Blocks Not Retaining Their Sounds

### ISSUE THREAD

**Issue by SixOnTheBeach** [Azanor/thaumcraft#1716]
Warded blocks seem to not retain sounds such as breaking, or walking on. Not a huge bug, but can be annoying when you pick a specific block for the sounds.

**Comment by MalkContent** [comment]
They are frozen in time, so "walking on hard surface" sound is probably the way to go ;)

**Comment by Azanor** [comment]
I'm not currently working on the 1.7.10 branch of TC anymore and this problem wont exist in the 1.8 version so closing.
