### ISSUE TITLE
Hungry Node Physics

### ISSUE THREAD

**Issue by Shirolol** [Azanor/thaumcraft#1717]
It was my mistake to get too close to the node. I flew in, but that made me aware of some problems:

1. I don't know whether the effect when going near the node is supposed to be a sucking effect or a gravitational effect, but I assume it is supposed to be sucking. While the node can't destroy obsidian, it continues to suck and if it is not completely surrounded by 26Blocks of Obsidian destroy items(even if it won't remove blocks anymore). If it is supposed to be a sucking effect that makes no sense, because the obsidian should lock the node up and keep it from sucking in more air from the outside. This is more of a logic problem than a real bug, I'll just destroy them or research some fix for them next time. (I know that even if this is not how it's supposed to be it will be hard to fix)

2. This should be considered an actual bug I think : The way Minecraft handles falling you can still escape a hungry node by destroying it if you fall in, but after that you will be instantly killed, because all the time spent flying around the node is considered falling.
I can imagine someone falling over and hitting himself somewhere, when he gets thrown around by a node, but if the node is 2blocks above the ground and you get pulled up, make a little circle around it and then fall down again and instantly die it's pretty silly. It might be an idea to reset falling frequently when stuck in a node so this doesn't occur.

3. I once had an obsidian wall in front of an overpowered hungry node, got too close and was pinned to that wall. At that point there was literally nothing I could possibly do other than to break the obsidian wall to commit suicide (which would have taken at least 5minutes). The issue mentioned in 2. Would have instantly killed me if I got out of this situation anyway. This is just a result of the way hungry nodes work.

Thaumcraft is one of the most immersive mods out there, so things like this are especially annoying.

**Comment by Shirolol** [comment]
OOps I forgot:

Forge: 10.13.2.1291
FML: 7.10.85.1291

Thaumcraft: 4.2.3.5

**Comment by justicesays** [comment]
TBH, 2 and 3 can be solved by wearing a thaumastatic harness when dealing with Hungry nodes, which I highly recommend when trying to capture them, so probably just your fault for getting too close without taking the appropriate precaution.
 
As regards 1).
Would you prefer a constant gentle pull at long range, warning you of the presence of a node, or walking around a corner in a tunnel directly into close proximity to a newly generated node and getting sucked in with no warning?
Especially given that it's very possible people don't always have goggles of revealing (on some of the big mod pack servers for instance)

**Comment by Shirolol** [comment]
Yeah. Like I said. It was my stupidity that brought me into this situation, but I still think instant kill by falling damage as a result of bening pulled up 2meters for s few seconds is pretty silly.

And about 1) again: Well you can still have some clues about a hugry node being nearby without being pinned to the wall as soon as you approach it. Like some ominous sound effect or slight shaking...I dunno. It's just that you can't contain them if you are not a high-level thaumcraft player already.

I didn't try to bottle the node up, I just wanted it to stop eating my world away.

**Comment by MalkContent** [comment]
2.) is a valid thing am pretty sure that it could be resolved more or less easily
3.) is not or related to 1.)
1.) is a valid thing, i guess, and would be a pita to solve gracefully and if it gets solved would likely produce quite a bit of cpu load

Hungry nodes are very rare and very powerful things and i guess their being this dangerous is somewhat justified. My best guess: 2.) could get fixed in the near future, 1.) and subsequently 3.) probably not, simply because it would be a great lot of effort for very little gain, considering that the mod doesn't exactly revolve around the hungry nodes.

**Comment by forsaken1111** [comment]
On 3, could give any entity who has been immobile for x time a small kick away from the hole allowing escape?

Or simply vary the hungry node to sometimes push as its an unstable/flawed node anyway. Would allow escape if pinned to a wall but you'd have to wait and think about your mistakes and then be quick to use the push.

**Comment by MalkContent** [comment]
hungry nodes already spit you out eventually. i think you shouldnt be stuck to the wall in the first place because of 1, but ultimatively, if you built the thing around the super dangerous thing and didn't do it properly, I can't shake the feeling that it's kind of the players fault :P

**Comment by Shirolol** [comment]
Yeah 2 is really the issue that bothered me. 1) confuses me and 3 couldn't be fixed without altering the concept of the hungry node.

If I have armor and get stuck on a wall next time, I might throw an Alumentum at the wall. :) Bad idea, but better than being stuck forever.

**Comment by MalkContent** [comment]
why don't you just bring an ender pearl or two ;)

**Comment by forsaken1111** [comment]
or a wand of uprising, or a staff of travel, or any of a dozen other mobility items from various common mods :P

**Comment by MalkContent** [comment]
but y'know. everyone's got enderpearls

**Comment by Azanor** [comment]
I'm not currently working on the 1.7.10 branch of TC anymore and this problem wont exist in the 1.8 versionso closing.
