### ISSUE TITLE
java.lang.ArrayOutOfBoundsException - Crash On World Opening

### ISSUE THREAD

**Issue by xWTyrone** [Azanor/thaumcraft#1722]
Crash Log PasteBin: http://pastebin.com/UXnzYrDL

The crash happens whem I'm trying to open my world.
Started happening after updating to latest version.
I will try older version to see if works.

**Comment by T4ge** [comment]
I would attempt to remove fastcraft

**Comment by xWTyrone** [comment]
Was trying to do so... Waiting for MC to load...

**Comment by xWTyrone** [comment]
Seems that removing FastCraft does the trick... Since I couldn't open the world successfully after that, I'll leave this issue opened for now. Still have to check if it's solved.

**Comment by xWTyrone** [comment]
Works with 4.3.2.4! What a hell happened?

**Comment by T4ge** [comment]
Im not entirely sure, but i do believe there was a change to the urns due
to issues somewhere. And with fastcraft installed some functions are
changed to be more efficient. Im not entirely sure and quite tired. Your
error is the rendering of the urn.. Sadly you don't need to be a rocket
scientist to know that xD

**Comment by xWTyrone** [comment]
Let's see. Thaumcraft isn't the only mod I have with rendering issues.
Probably the combination is causing some errors.
I'll have to try a lot of things.

**Comment by T4ge** [comment]
Are you using optifine? I know a lot of people who are using fastcraft
need/prefer it in their packs. And optifine is known to cause rendering
issues. I can try to help you properly later if no one more skilled doesn't
come by if you can't seem to get it working properly. Also you can always
just read thaumcrafts changelogs, if the changes for the later versions
doesn't effect you much,  you can always just not update. However, the 2
last ones were mainly bug fixes. So it depends on the severity of the bugs
fixed.

**Comment by xWTyrone** [comment]
I don't need Optifine. FastCraft gives a visible help on the laggiest part of MC. Rendering is no big deal.
AE2 also crashes the game with render issues. AS far as I can tell this is a strange problem of sorts.
I'll see if any other mod may be messing with render, and if it is or not a fastcraft issue.

**Comment by MalkContent** [comment]
issue is old waila. update it
