### ISSUE TITLE
Infusion Alter Not Working.(Taking the some essentia but not continuing) 

### ISSUE THREAD

**Issue by AJKproductions** [Azanor/thaumcraft#1727]
Hello Everyone,
I am having a problem with my infusion alter, i have crafted a few items with this alter before hand (and a lot more advanced things too). I am running the FTB Infinity modpack, i added the mekanism mod as well. The alter set-up/space is 15x15, that is where the alter is positioned and all the essentia jars are contained inside. 

I am trying to create the Fishing Golem Upgrade thing and this is what would happen: I would lay the items out on the stands (puffer fish, fishing rod, raw salmon and  war fish). When i right click the Runic Matrix the process would work normally, it will take all the aqua. Then however it stops it won't take any of the other two essentias (Messis and Meto). 

Here is some screenshots i took:
https://drive.google.com/file/d/0Bx6XDTCq9x7ZWUF1R1ZGR2RkRG8/view?usp=sharing

https://drive.google.com/file/d/0Bx6XDTCq9x7ZOTdTSVFySTExa1E/view?usp=sharing
(The red circles are the essentia jars that are in use, and they were near full when i started the infusion. And the alter was properly formed, i.e. the Runic Matrix is in its proper position)

Any more information just ask. Thanks for reading, i wrote this at while i was half asleep sorry for any misspellings.

**Comment by MalkContent** [comment]
it needs bestias, not messis.

**Comment by OJwithC** [comment]
Pretty sure the jar has Bestia. It didn't have the right color for messis.

**Comment by justicesays** [comment]
A useful view would show the essentia demand of the runic matrix, as seen with goggles of revealing.
Was there instability signs, like purple lighting etc. when the infusion stopped?

**Comment by KlutzLament** [comment]
You really should label your jars so you can easily identify what's in them. Labels are cheap, removable, and reusable.

**Comment by AJKproductions** [comment]
Okay i can tell you that all the necessary types of essentia are there, I will upload some more screenshots later to show you what's happening, I am currently running low on slime balls so can't craft any more labels....
btw, I used the infusion alter earlier and it worked fine, i will have to retest to see if it works now....

**Comment by AJKproductions** [comment]
The alter just started working, this might be because i quit the game or maybe when i crafted another item then tired it again, but anyway it works now, thanks for commenting
