### ISSUE TITLE
Pech mage & stalker despawn

### ISSUE THREAD

**Issue by busterGR** [Azanor/thaumcraft#1729]
Not sure if this is intentional, but I assume it isn't: pech mages and stalkers seem to despawn when I go too far from them(chunks still loaded though) while foragers can stay where they are indefinitely(I've had one in my potato farm for ages). This also happens when I befriend them.

Also, when spawned by ExtraUtilities cursed earth they randomly despawn even when I am right next to them(again onlythe mages and stalkers).

Edit: I forgot, I'm running thaumcraft 4.2.3.5 and several other mods, however there should be no conflicts.

**Comment by T4ge** [comment]
I may be mistaken, but I'm pretty sure it's intentional. They act as normal
mobs. The Extra Utilities.. I am not quite sure, either intended for the
sake of not making them farmable or just an error on one of the sides.

**Comment by Azanor** [comment]
Yup, they can despawn like normal mobs. The only exception is if you name them, or if one of them has picked up something from the ground.
