### ISSUE TITLE
Links to hidden research

### ISSUE THREAD

**Issue by Akxe** [Azanor/thaumcraft#1733]
EDIT:
As we found out, I haven't got all needed things, but the point is that the missing research made me think, that it was a bug, rather than my bad... It may worth hiding links going from nowhere

I found a bit disturbing thing, I have researched everything (, but wands & staff sub types, iron golem, transmutation and purification) and I have missing research.
**Missing research**:
![missing research](https://cloud.githubusercontent.com/assets/2001798/7079471/cf7a2754-df24-11e4-988c-7082e07a4efe.png)
**Sanity**:
![sanity](https://cloud.githubusercontent.com/assets/2001798/7079472/cf7efc16-df24-11e4-8a5e-ba47a1f7fdc8.png)

Minecraft: 1.7.10
Forge 10.13.2.1352-1.7.10
Thaumcraft 4.2.3.5.jar

**Comment by OJwithC** [comment]
Not everything then. Looks like you need to find some Eldritch mobs/structures. (Possibly more warp too. Making Flesh golems, brain in a jar, etc. or eating brains give warp.)

**Comment by Akxe** [comment]
Well usually there aren't the lines going from nowhere... Warp is shown so you can see how much do I have & I have scanned the altars, the crimson cultists (both), and all about taint.
And if it is supposed to be hidden, till I find something, shouldn't the links be hidden too?

**Comment by OJwithC** [comment]
Have you read the Crimson Rites and scanned an Eldritch Eye?

**Comment by Akxe** [comment]
No... But as I mentioned, is there supposed to be visible the links to not even grayed item?
