### ISSUE TITLE
Bucket of Water destroying aura node/

### ISSUE THREAD

**Issue by Lusaphor** [Azanor/thaumcraft#1734]
I'm building a super node, and was using a bucket of water near one of my feeder nodes, and the bucket of water managed to destroy the node and place the water, without any drops or any other issues. Not sure if intended, but rather annoying to lose the ordo node...

**Comment by Akxe** [comment]
Lava does it too, so I guess it is all liquids
Minecraft: 1.7.10
Forge 10.13.2.1352-1.7.10
Thaumcraft 4.2.3.5.jar

**Comment by Azanor** [comment]
I'm not currently working on the 1.7.10 branch of TC anymore and this problem wont exist in the 1.8 versionso closing.
