### ISSUE TITLE
Small request about aspects

### ISSUE THREAD

**Issue by zHawky** [Azanor/thaumcraft#1735]
Aspect request for vanilla modded mobs, there are;
Primitive mobs
Grimoire of Gaia
and some Chocolate Quest mobs

**Comment by MalkContent** [comment]
tc compatibility should be one the side of the secondary mods

**Comment by zHawky** [comment]
Yeah that i mean, default configs for aspects, TC mob aspects mod is so outdated and working only for Twilight Forest

**Comment by Azanor** [comment]
Yeah, adding aspects to mod mobs is either the job of that mods author, or via an addon mod. I can't possibly account for all the mods out there.
