### ISSUE TITLE
Taint swarm + Morph mod... Unremovable particles forever?

### ISSUE THREAD

**Issue by masonpinder** [Azanor/thaumcraft#1737]
I killed a taint swarm, and then turned into it using morph for fun, just to see what I looked like, and after morphing back to human, the particles were there. forever... Any way to fix that? Possibly just add some command to remove all particles from them or something?

**Comment by OJwithC** [comment]
https://github.com/Azanor/thaumcraft/issues/1576
https://github.com/Azanor/thaumcraft/issues/1577
Perhaps go to Morph instead.

**Comment by Azanor** [comment]
Indeed, that is not really an issue on my side, but closing the game should make them disappear.
