### ISSUE TITLE
Thaumcraft Aspect Cost Text

### ISSUE THREAD

**Issue by AngelKairi** [Azanor/thaumcraft#1739]
With some minor texture packs, it becomes increasingly difficult to read the aspect cost text while on normal GUI settings. I was wondering it was /possible/, if it's not.. that's fine, if we could get an option to increase the size of the Aspect Cost text size.

Normal GUI example Screenshot (1600x900?)
![rsndyvj](https://cloud.githubusercontent.com/assets/4471184/7129014/9f0a9c14-e228-11e4-8e77-9e6fcdfeb88c.png)

Large GUI example Screenshot (1600x900?)
![sdfasd5fa](https://cloud.githubusercontent.com/assets/4471184/7129015/9f0cc8fe-e228-11e4-9b01-e03df68e11a5.png)

**Comment by Azanor** [comment]
There is not much I can do about that a custom font added by a texture pack.

**Comment by Azanor** [comment]
Having said that, I may add a config option if I get the time. Making no promises though :p

**Comment by AngelKairi** [comment]
I'll still look forward to it. <3 It's not major, just a minor annoyance really. c: (Goodjobonthemodthough,itsreallyfun)
