### ISSUE TITLE
Confusing links

### ISSUE THREAD

**Issue by Akxe** [Azanor/thaumcraft#1740]
You may remember this image from a post about missing research. I'm now aware it is not a bug, but intentional, but I think the links to nowhere may be a bit confusing and therefore maybe hidden. Just a thing to consider. 
**Missing research**:
![missing research](https://cloud.githubusercontent.com/assets/2001798/7079471/cf7a2754-df24-11e4-988c-7082e07a4efe.png)

**Comment by Azanor** [comment]
Yup, I will try and fix that for the next major release.
