### ISSUE TITLE
Performance issues with Hungry Nodes

### ISSUE THREAD

**Issue by mSt3in** [Azanor/thaumcraft#1742]
Nodes in general are bad for server performance.  They are always at the top of Opis's list of time-sucking tile entities.

Some are worse than others, depending on how close it is to chunk boundary or the combination of blocks/fluids it spawned near.

Hungry nodes, in particular, are very problematic.  I'll be flying around doing some world gen, and I'll know when a new one was spawned in the area, TPS on the server goes into the toilet.

Some players have discovered they could use Mek's cardboard box to "make" hungry nodes.  They start making their own personal farm of them, and...needless to say this trashes the server.

The mechanics of the hungry node are really cool, but I don't think the performance cost is worth it in the long run.  I'm begging you to redesign this node completely.

OpenBlock's Vacuum Hopper has a similar problem.  It sucks in items in a 3x3x1 area, and so it must scan that area every tick.    The Hungry node scans a much larger area, and does that physics stuff to boot.  Ouch.

**Comment by Azanor** [comment]
Nodes in their current form are going away for 1.8 so... fixed I guess?

**Comment by Azanor** [comment]
Just adding in case you didn't know: I'm currently halted all development on 1.7.10 TC.
