### ISSUE TITLE
Taint performance in servers

### ISSUE THREAD

**Issue by DavidMetcalfe** [Azanor/thaumcraft#1753]
Over time, I've come across a number of publicly facing servers with Thaumcraft as part of the pack that have explicitly disabled taint spreading, citing performance issues. I would like to know from the developer(s) whether this is a legitimate concern, or if this is a misguided belief and performance hits are coming from other mods, etc.

**Comment by Azanor** [comment]
Not that I'm aware of. Taint should not have much more of a performance hit than vanilla grass.
