### ISSUE TITLE
Magical Forest (Silver wood forest) Very laggy

### ISSUE THREAD

**Issue by sonicbrandyn** [Azanor/thaumcraft#1754]
Soooo, I was looking around my world in creative (No particular reason i was just bored :P)
And i came across a silverwood forest and my fps dipped from 300+ to 80
please see these images: http://prntscr.com/6xnnkp and http://prntscr.com/6xnozp

**Comment by sonicbrandyn** [comment]
The mod actually lags my game in general but its especially bad in the silverwood forest

**Comment by MalkContent** [comment]
greatwood/silverwood leaves eat fps like cream puffs, and there's like to be a couple of those around :)

**Comment by sonicbrandyn** [comment]
Why though?

**Comment by sonicbrandyn** [comment]
I cant play my modpack until i get a fix because on my server i live in a silverwood forest and it will mess up if we remove thaumcraft because of the lag

**Comment by forsaken1111** [comment]
80fps sounds pretty playable still...

**Comment by sonicbrandyn** [comment]
Yeah, but not pleasent

**Comment by sonicbrandyn** [comment]
If this isnt fixed im forced to remove thaumcraft

**Comment by sonicbrandyn** [comment]
Because even when im away from the silverwood forest my fps isnt pleasent

**Comment by sonicbrandyn** [comment]
My fps is still terrible with thaumcraft while just playing normal modded minecraft on my server no where close to a silverwood forest http://prntscr.com/6xxzj6

**Comment by MalkContent** [comment]
then drop tc and see if that helps
and unless you have one of those fancy 144hz monitors, it's virtually impossible to notice any fps drops up until 60 (screen tearing aside).
in any case, it's a pretty mean drop and should be considered an issue of some sort. people with less capable computers might really struggle with that sort of thing

**Comment by sonicbrandyn** [comment]
I dont have a bad pc I have 2 monitors both good and what i dont understand is when i play FTB infinity i dont get these lag spikes and lag, but when i just play normal minecraft with tc i lag and get lag spikes + Im using the same version, I havent edited the configs

**Comment by sonicbrandyn** [comment]
And i love Tc

**Comment by MalkContent** [comment]
so you have lag spikes/periodical fps dips?

**Comment by sonicbrandyn** [comment]
Yes all the time

**Comment by MalkContent** [comment]
well that would be a bother. 80 fps is probably just a median and in truth you had a brutal lag and then it reassumed regular behavior again.
got anything tc build nearby? golems?
and try disabling tain spread in the config, see if that makes a difference

**Comment by sonicbrandyn** [comment]
I have no tc build (It happens in brand new worlds)

**Comment by MalkContent** [comment]
try disabling tain spread then. it's the only thing i can think of that could be ticking.
that or nearby greatwood and silverwood leaves

**Comment by sonicbrandyn** [comment]
I didnt disable taint spread but i removed mariculture and some thaumcraft addons and my fps got allot better the lowest im getting is 100 But im noticing allot of screen lag

**Comment by MalkContent** [comment]
does the lag vanish when you kick tc?

**Comment by forsaken1111** [comment]
Be methodical about this. Create a world with ONLY thaumcraft and see what you get, then remove thaumcraft and test again.

**Comment by sonicbrandyn** [comment]
Yes

**Comment by sonicbrandyn** [comment]
I only get lag spikes and lag in silverwood forests with JUST thaumcraft

**Comment by sonicbrandyn** [comment]
Here i made a video of me flying around with only thaumcraft: https://www.youtube.com/watch?v=jFKb_sfN2DM&feature=youtu.be

**Comment by MalkContent** [comment]
do you get the spikes far away from silverwoods/greatwoods, too?

**Comment by sonicbrandyn** [comment]
Watch the video?

**Comment by MalkContent** [comment]
cant

**Comment by sonicbrandyn** [comment]
Why?

**Comment by MalkContent** [comment]
as i said: private video

**Comment by sonicbrandyn** [comment]
You didnt say private video o_O Whys it private! I will fix this!

**Comment by sonicbrandyn** [comment]
https://www.youtube.com/watch?v=jFKb_sfN2DM

**Comment by MalkContent** [comment]
pretty sure those fps drops are just from the world being generated.

**Comment by sonicbrandyn** [comment]
Doesnt happen without thaumcraft

**Comment by MalkContent** [comment]
maybe tc has a second layer of worldgen running that adds the magical biomes over the regular ones. that could explain that. but i dont know enough abouth this.
try a superflat world. that stuff has nothing to generate that should affect anything

**Comment by sonicbrandyn** [comment]
No lag at all

**Comment by forsaken1111** [comment]
Just watched your video. That looked pretty smooth other than a few small stutters. Mods are going to cause lag, no matter what you do. Live with it or don't use it. I don't think there is a magical cure for small lag spikes when doing worldgen.

**Comment by sonicbrandyn** [comment]
D:

**Comment by twothe** [comment]
As far as I can tell this stuttering is caused by massive chunk updates related to magical leaves. See #1772

**Comment by AnrDaemon** [comment]
Enable VSync already.
