### ISSUE TITLE
Crash with Gany's surface

### ISSUE THREAD

**Issue by cbcercas** [Azanor/thaumcraft#1756]
When I add Gany's Surface 1.11.0 on my server I get this crash http://pastebin.com/17Gp6g0H
Version 1.10.0 work

I open the same issu on Gany's [#46](https://github.com/ganymedes01/Gany-s-Surface/issues/46)

**Comment by ganymedes01** [comment]
This is the only bit of code I have that references anything thaumcraft: https://github.com/ganymedes01/Gany-s-Surface/blob/master/src/main/java/ganymedes01/ganyssurface/integration/ThaumcraftManager.java

All it does is add aspects to the various items/blocks that my mod adds

**Comment by ganymedes01** [comment]
The only thing that's changed from 1.10.0 to 1.11.0 is that I added aspects to more items that didn't have them before.
