### ISSUE TITLE
Loot Bag control

### ISSUE THREAD

**Issue by bookerthegeek** [Azanor/thaumcraft#1758]
Me again.

Config request for one of the following:
* Disable loot bags from champion mobs.
* An ability to modify what comes in the loot bags.

Thank you for your time in this.

**Comment by Yulife** [comment]
Modtweaker2 will soon have the ability to customize Loot Bag drops =)

**Comment by jaredlll08** [comment]
I remember doing this in 0.8.1...

**Comment by bookerthegeek** [comment]
Love the fact that loot mod tweaker 2 will have the ability. Is this going to be the official way to modify the loot bag drop?

Don't worry @yulife, I'll be visiting you soon. :)

**Comment by jaredlll08** [comment]
This can be closed. modtweaker has had this function for many versions now.

**Comment by bookerthegeek** [comment]
Thank you.
