### ISSUE TITLE
Tainted mobs might not be despawning naturally

### ISSUE THREAD

**Issue by Nagapito** [Azanor/thaumcraft#1760]
I am playing a pack(Hubris) where the world is all tainted(except oceans/rivers/beach) and as time passes, my world gets filled of tainted creepers. Even if I get more then 128 blocks away from them, they will not despawn. 

I made a dark room for normal mob spawning so I could farm mobs, at 180 height, over the ocean, so when I am closer to it all other mobs should despawn and normal mobs spawn inside it. But... that does not happen. I have to use /cofh killall so the 60-80 tainted creepers get despawned and normal mods spawn there.

When I get down to a normal level, all kind of mobs start spawning normally, but over time, they die to the taint, creepers get converted into tainted creepers and they start filling the mob cap again. My base is like 60 blocks away from the shore, so, even the tainted creepers should randomly despawn, which doesnt happen. I see the same creepers over time on the same spot, idling since they are more then 32 blocks away.

The pack also has Special Mobs, Infernal Mobs and MobProperties mods, not sure if they could be the cause of this issue. Strange enough this only happens with tainted creepers. I dont get other kind of tainted mobs when I kill them all with the console.

**Comment by KD0BPV** [comment]
I'm having a similar issue in my Direwolf20 world. There are two separate taint biomes near my base, and they have TONS of mobs in them, to the point that normal mobs won't spawn unless I travel at least 1 KM away from my base. If I do /xu_killmobs or /cofh killall, I'll start getting normal mobs as expected again, but only for about half an hour before the mob cap is saturated by the taint biomes again.

**Comment by Azanor** [comment]
Tainted mobs do no despawn.
