### ISSUE TITLE
Arcane Levitator is hardcoded to use the shift key

### ISSUE THREAD

**Issue by BarbasTheDog** [Azanor/thaumcraft#1764]
If you remap your sneak key to something else, the levitator doesn't take that into consideration, so you'll still need to press shift in order to descend. This is specially annoying for people who have mapped shift to something else or just in general don't use the shift key for crouching.

It's nothing big, just an annoyance that I thought I should report, considering it's an easy fix.

**Comment by OJwithC** [comment]
https://github.com/Azanor/thaumcraft/issues/1573

**Comment by Azanor** [comment]
I will be changing this back to check for sneaking in the next update.
