### ISSUE TITLE
(TC 4.2.3.5) Thauminomicon Carrying Capacity Reached

### ISSUE THREAD

**Issue by duhadventure** [Azanor/thaumcraft#1768]
When I have more Thauminomicon tabs than It can hold, and they overlap each other and only allow you to use one of them.

![](http://i.imgur.com/HvqTWQH.png)
In the above picture on the top right side the AOBD (Another One Bites the Dust) and Thaumic Tinker tabs have merged together and I can now only use the thaumic tinkerer.

Thaumcraft Addons Installed (That add tabs)
Automagy (Latest Version)
Railcraft (latest)
Essential Thaumaturgy (Latest)
Another One Bites The Dust (latest)
Thaumic Tinkerer (Build 164 aka latest)
Forbidden Magic (Latest beta release)
Magia Naturalis (latest)
Magical Decorations
Thaumic Energistics
Thaumic Exploration
Thaumic Horizons
Thaumic Infusion
Witching Gadgets (Adds search bar and other things)
Magistics

Addons with no tab:
Nodal Mechanics
TC Node Tracker

The only thing I could figure out to fix this is to make it so tabs can go on bottom/top, add pages like creative menu, or a scroll bar.

**Comment by forsaken1111** [comment]
Searching issues is your friend.

Reported several times, fixed for the new version in 1.8.

**Comment by duhadventure** [comment]
But not 1.7....

**Comment by forsaken1111** [comment]
Correct... he's working on 1.8. I wouldn't expect any changes to the 1.7 versions at any point.

**Comment by forsaken1111** [comment]
for reference:

#1249 #1369 #1654
