### ISSUE TITLE
Galacticraft compatibility - please set golems not to die

### ISSUE THREAD

**Issue by radfast** [Azanor/thaumcraft#1770]
Hi @Azanor we haven't communicated before but as you may know I'm one of the Galacticraft developers, lead developer now that micdoodle8 has moved on to other things.

Please on your golems can you implement this from our API:
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/entity/IEntityBreathable.java#L12

and return true on canBreathe().  It will allow players of both mods to use Thaumcraft golems in space dimensions.

If you're aware of any other compatibility issues which we can help with on our side, please do let me know.  We have a current push to improve Galacticraft's compatibility with everything.  As you may know, we have allowed for Thaumcraft wild node worldgen on Galacticraft planets.  I am also currently looking at how to add Thaumcraft aspects to Galacticraft items, see here: http://forum.micdoodle8.com/index.php?threads/any-thaumcraft-players-here-your-views-needed.5252 though I must confess to being a TC noob as I don't have time to play much.

**Comment by shobu9** [comment]
@radfast You could always make an air bubble for them...

**Comment by Azanor** [comment]
I have already set golems to not need "vanilla" air. Maybe you can check that?

**Comment by radfast** [comment]
@Azanor  I don't understand.  You're suggesting I rewrite the whole of Galacticraft to check air differently, instead of you implementing 2 lines from our API?
