### ISSUE TITLE
awakened ichorium pickaxe breaks warded blocks.

### ISSUE THREAD

**Issue by convict-vx** [Azanor/thaumcraft#1771]
if u have a wall of warded blocks it is impossible to break the blocks with the pickaxe.

But when u make a wall and ward the blocks, then place 1 block unwarded in front of the wall and use the awakened ichorium pickaxe in line mode it breaks the warded block behind the non warded block.
Also if u make a square and keep 1 block in there unwarded and u mine in square mode it will mine all blocks around the non warded blocks within range of the pickaxe.

version: 4.2.3.5 (in dw20 1.3.1 update)

Did look on the issue page and didn't find anything, either not reported yet or i'm a bad searcher. :D

**Comment by OJwithC** [comment]
The I chromium pick axe is from Thaumic Tinkerer.

**Comment by convict-vx** [comment]
o dang, true, my bad. :s
