### ISSUE TITLE
Thaumcraft causes way too many chunk updates and is lagging the game

### ISSUE THREAD

**Issue by twothe** [Azanor/thaumcraft#1772]
I have noticed that Thaumcraft is the cause of severe lag in my game. With Thaumcraft active my FPS drop significantly while the game stutters thanks to never ending block updates. If Thaumcraft is removed the issue is gone immediately.

According to observation of profiling of the game, the source is definitely related to the magical trees, most likely related to the leaves. Something there is causing tons of chunk updates, which will make the game stutter even on a fast machine.

**Comment by Azanor** [comment]
This is a known issue and will be addressed in the next update.
