### ISSUE TITLE
Loading The Outer Lands

### ISSUE THREAD

**Issue by Fjolsvin** [Azanor/thaumcraft#1774]
I don't exactly know what can be done with this, if anything, but what I've just experienced is not funny at all:

Exiting The Outer Lands, there were two or three Eldritch Guardians following me. Nothing I can't handle with my full enchanted void armor, about 45 runic shielding, etc. Nevertheless, going back to The Outer Lands, while still watching the loading screen (!), I was attacked already (heard the sounds of being hit) and at the very first milisecond the world loaded and I could react I found myself already with 2 hearts left and pushed into the void corner of the central room only to see myself die immediately and lost all the items in the void at the same moment. Practically I was thrown into the Outer Lands already dead.

If there is no possibility to solve the problem mobs are attacking while there is still loading screen or if they can't be despawn everytime when leaving The Outer Lands I only can suggest to remove the void corners from the immediate distance from the spawn point. Otherwise there is probably only one solution, to enter The Outer Lands in peaceful mode only to prevent being killed while the world is still loading and switch the difficulty on once The Outer Lands are loaded.

**Comment by Azanor** [comment]
What you describe is not a TC issue. I have no control over how quickly MC loads a world, or what buddies you leave behind for your next visit.
The corners however will probably be going away in the next update since I will be changing some of the structural stuff.
