### ISSUE TITLE
Can't craft Golem Bell

### ISSUE THREAD

**Issue by Time6628** [Azanor/thaumcraft#1776]
I can't craft a golem bell in my world. When I try to it becomes "Unnamed -1" then disappears. :tongue:. Thaumcraft: 4.2.3.5
Forge: Latest version

**Comment by Azanor** [comment]
When you say latest version of forge, do you mean the latest 1.7.10 version?

**Comment by Time6628** [comment]
Yes.

**Comment by SeriousCreeper** [comment]
Are you using Thaumic Horizons in your pack? Cause this is a known issue with Thaumic Horizons as well, not Thaumcrafts fault as far as i know.

**Comment by Time6628** [comment]
@SeriousCreeper Yes.

**Comment by SeriousCreeper** [comment]
@Time6628 Known issue, can be found here too: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2361575-thaumic-horizons-v1-1-1-thaumcraft-4-addon?comment=217 

So just wait till Thaumic Horizons releases a new version :)
