### ISSUE TITLE
regarding retro-generation

### ISSUE THREAD

**Issue by bookerthegeek** [Azanor/thaumcraft#1777]
Hello again.

So we had to turn on retro- gen structures into the world. This worked just fine. The issue comes into play when a player tries to enter an obelisk. They are not spawning inside of the structure, but outside of it. 

I have no idea on how to solve this. the only thing that I can think of to do is to delete the dim folder to allow it to regenerate, but I don't know if that would fix it or not. Either way I thought I would bring this to you attention.

How to reproduce:
 * Generate a world with thaumcraft.
 * Run retro-generation.
 * Enter into one of the NEW obelisks.
 * Fall to your death.

We are running the latest version of the mod-pack regrowth in a non-pure forge environment. But the issue is reproducible on a pure forge server.

**Comment by Azanor** [comment]
You could try deleting the labyrinth.dat and save dimension data for the eldritch dimension from your save files. That should fix the issue.
