### ISSUE TITLE
1.7.10 Crash with  Thaumcraft.Pech (thaumcraft.common.entities.monster.EntityPech)

### ISSUE THREAD

**Issue by KaneHart** [Azanor/thaumcraft#1778]
Been getting these dozens of times. Can't get onto the server because the loaded chunk crashes us all.
http://pastebin.com/xAfN9wWM

**Comment by Azanor** [comment]
The problem actually seems to be with cofh. It changes something with entity AI that causes the issue.

**Comment by KaneHart** [comment]
Thank you. I will close this and I'm pretty sure it's cofh tweaks. They do touch mob AI in some sort of way. I will see if @skyboy from it will look into it.
