### ISSUE TITLE
Nodes "technical" name

### ISSUE THREAD

**Issue by notchriss** [Azanor/thaumcraft#1789]
Hello, I'd like to include nodes into the list of items that are ignored when assembling Archimedes' Ships ship. The list in config goes in format of Mod:Item, i.e. Thaumcraft:Somenode, I'd guess. Where could I find a list of 'technical' names for all the different thaumcraft nodes, so they won't be attached to  the ships, which makes Thaumcraft's node moving system pointless? Sorry for laymen terms I hope you get what I am asking for ;)

**Comment by Azanor** [comment]
If it is block names you require you can try "blockAiry"
