### ISSUE TITLE
Graphical Error wth Nodes on Ubuntu 15.04

### ISSUE THREAD

**Issue by CoderK4b6** [Azanor/thaumcraft#1790]
So I was playing my minecraft on a new laptop that I installed Ubuntu 15.04 on. and one of the nodes started doing this, I don't know if this is a LWJG problem but I thought I would post it here just in case

![2015-05-26_23 48 22](https://cloud.githubusercontent.com/assets/7905316/7829129/3f933a14-0403-11e5-94a5-e448c50a2a06.png)
![2015-05-26_23 49 04](https://cloud.githubusercontent.com/assets/7905316/7829130/3f9bde1c-0403-11e5-9bca-7780c073e1be.png)
![2015-05-26_23 49 06](https://cloud.githubusercontent.com/assets/7905316/7829131/3f9faa4c-0403-11e5-938a-a736cdbe7e86.png)

as you can see It seems that the transparency on nodes is being not rendering properly, and instead of rendering white it is creating this weird black color with zero's and one's. I doubt this intended and just thought it was a little weird.

**Comment by Azanor** [comment]
I'm pretty sure that is not a thaumcraft node - I don't sue the ender dragon rayline effect on them at all and it also seems to be a bit too high up - my nodes don't spawn more than 3-4 blocks above the ground.
