### ISSUE TITLE
Runic Shielding Occasionally Stops Regenerating

### ISSUE THREAD

**Issue by AranaiRa** [Azanor/thaumcraft#1804]
I'm playing on a multiplayer server, and every so often when my shields are emptied, they just never refill. Un-equipping and re-equipping, even with a relog in between, does not solve the issue. The shields can stay down for hours at a time before starting to regenerate again.

**Comment by TheMadmanofChaos** [comment]
Do you happen to have a source of vis in your inventory? Recharging Runic shielding needs terra and aer vis per point, so at the times it wasn't recharging you most likely ran out of vis or had no wand in your inventory.

**Comment by AranaiRa** [comment]
God I feel stupid. I never once noticed that you had to have vis to refill them. Closing this testament to poor reading comprehension.
