### ISSUE TITLE
Vanila fence won't connected to wareded glass

### ISSUE THREAD

**Issue by ZZaphodd** [Azanor/thaumcraft#1806]
Vanila fence won't connected to warded glass.

green ==> connected fence(expected)
red ==> warded glass(not connected)

![image](https://cloud.githubusercontent.com/assets/8099421/8148645/4c46ce5a-12e1-11e5-91b3-39f831cb4675.png)

**Comment by ThePB** [comment]
i'd say not a bug?
Fences do not connect to vanilla glass too, so i suppose they do not connect with any transparent block at all....

**Comment by ZZaphodd** [comment]
Oh my bad,
