### ISSUE TITLE
ArrayIndexOutOfBoundsException on crafting Golemancer Bell

### ISSUE THREAD

**Issue by ruifung** [Azanor/thaumcraft#1831]
http://puu.sh/j5PWa/0ae8f0cada.txt

**Comment by Akxe** [comment]
Mod list, TC version etc...

**Comment by ruifung** [comment]
If you would read the log, most of the commonly asked for information is already included in it like mod list and TC version.

```
UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
```

**Comment by Zsashas** [comment]
By any chance, did you try making it in something other than the normal Arcane Workbench? Either the Automagy Crafting Focus or the Thaumic Energistics Arcane Crafting Terminal? What kind of wand or scepter did you use? What dimension?

This is why as much detail as possible is helpful.

**Comment by SyncStelar** [comment]
I am the one who got this crash. I used the normal arcane workbench using the gold banded greatwood wand without a focus in overworld. When crafting the bell, it gives me a bell with the item id -1. Upon attemptibg to craft, minecraft crashes.

**Comment by OJwithC** [comment]
Sounds like the recipe might be disabled somehow?

**Comment by ruifung** [comment]
Now that I've had some time to actually investigate it, it doesn't appear to be a issue with thaumcraft. Some other mod is adding a second golemancer's bell entry in NEI (with the exact same ID too!) and somehow when using a server, it fudges it into a -1 ID which causes a client crash.
