### ISSUE TITLE
C-Vis Beams Renders weird

### ISSUE THREAD

**Issue by Gallahorn** [Azanor/thaumcraft#1835]
Im sorry if this issue been up before but i couldnt find any similar issues other then a post on FTB forums of a guy with the same issue.

Link to the thread on ftb forums with the same issue: 
http://forum.feed-the-beast.com/threads/thaumcraft-4-rendering-issue.95697/

Im using DW20 (the server im playing on using 1.5.0 its the version that curse client reports) + iguana tinker tweaks and today some of the cvis beams started to render weird. Been using this pack for the last 2-3 weeks if not longer and have never seen this issue before.
See screenshots:
![2015-07-26_02 33 00](https://cloud.githubusercontent.com/assets/13502434/8891999/020cc018-3340-11e5-91b3-6711ea0f315c.png)
![2015-07-26_02 36 37](https://cloud.githubusercontent.com/assets/13502434/8892000/04610ca2-3340-11e5-936b-1a513e74c9b8.png)

Relog will fix the issue till i start putting down more vis relays and after a couple it will start rendering like the SS I linked.

Edit 1: After some testing I can replicate this issue and its related to the arcane bore when it pulls cvis from the network and you place down new vis relays while the bore is running. but as soon as you turn of the arcane bore and places new vis relays the issue comes back tried some other cvis devices but this far it seems like its the arcane bore thats making the cvis beams mess up.

Edit 2: You need to break the redstone signal to the arcane bore for the cvis network to return to normal. Its not enough if you break the vis flow to them. The beams are messed up even if the arcane bores arnt getting feed some vis. It seems to be enough to have a arcane bore running while placing new vis relays going to test this a bit more

Edit 3: After some more testing its clear that the arcane bore dont even need to be connected to the vis network for the bug to happen. It enough that you have the bore running in a couple of chunks range. If I setup a new node and new vis network out of view range. It works normal again till I leading the vis network in to vision of the bore then the bug happens again. Atm Im running at 8 chunks DD. And I have replicated this bug in 4 different worlds now. 3 different test worlds and 1 on the server where it happend the first time. Going to see if a friend can replicate it too when he gets online.  If you are intrested I can show and replicate the bug on stream for you. Dont have the space on my HDD atm to record a video.

**Comment by T4ge** [comment]
Yes this is a known problem, I don't believe it's a fix for it, your behind
on updates. However Azanor does not work on 1.7 and C-vis is being removed
from the 1.8 update from what I've caught.
