### ISSUE TITLE
Peremant Black Screen, Deadly Gaze

### ISSUE THREAD

**Issue by Zandorum** [Azanor/thaumcraft#1837]
On my game I got a the Deadly Gaze effect, It did the overlay but I couldn't see through it. Once the effected ended the screen stayed black, I killed my character to see if I could do that to get it to go away however it stayed on Respawn. I tried to restart my world to see if that would fix it temporarily and it's still there. It seem's to get my world back my only option is to delete Thaumcraft.

Here's my Log:
https://www.mediafire.com/?w4a2jb8fvg5yga6
Pastebin kept freezing and ATLauncher wouldn't Upload it.

**Comment by Zandorum** [comment]
I seem's restarting the game actually fixed the Black Screen.

**Comment by Azanor** [comment]
It might be a shader issue - you might want to turn them off in the Thaumcraft config.
