### ISSUE TITLE
Mangled Latin for "Opening the Eye"

### ISSUE THREAD

**Issue by MentalMouse** [Azanor/thaumcraft#1838]
The Latin given for "Opening the Eye", is "Apertis Oculis", but that actually translates as "Eyes Wide Open".  Consulting a Latin expert elsewhere yielded the following:

"Aperiens oculum" means 'opening an/the eye' ("aperiens oculos" would be 'opening some/the eyes'), but "aperiens" is a verbal participle, so it is more what you would find in a sentence like 'opening an eye, [I then did X]'.  If you want it as a translation of a concept in isolation, something like "apertio oculi" ('opening of an/the eye'), using two nouns, might be better.

**Comment by Vexatos** [comment]
See [here](https://github.com/Azanor/thaumcraft/commit/2814d60a530755d6c233def1ed6b76c09f4acdfd#commitcomment-8039543).

Azanor didn't really care.

**Comment by Azanor** [comment]
The crimson cult doesn't speak latin, just something that loosely resembles it. 

:p   that is my excuse and I'm sticking to it.
