### ISSUE TITLE
Infusing a stone with a feather and Aer essentia does not result in a light stone

### ISSUE THREAD

**Issue by flarn2006** [Azanor/thaumcraft#1839]
From the Thaumonomicon:

> Infusion crafting is the process of infusing a single object with mystical energy and the properties of other objects. You could, for example, infuse a stone with Aer vis and a feather and it would result in a very light stone.

I decided to try this myself, but it worked with neither cobblestone nor smooth stone. I'm assuming it's supposed to say "essentia" instead of "vis" by the way.

I know it's intended as a basic example of how infusion works, and you can't possibly program a result for every set of items someone might try, but if it specifically gives an example of a use infusion has, it shouldn't then not *actually* be something you can use infusion for.

**Comment by T4ge** [comment]
This is from Thaumic Infusion, which is not an issue of thaumcraft

2015-08-01 21:38 GMT+02:00 flarn2006 <notifications@github.com>:

**Comment by flarn2006** [comment]
Regardless of whether or not a separate addon adds such a recipe, the fact remains that the quoted part of the Thaumonomicon is from vanilla Thaumcraft. As such, the recipe it refers to should be possible without needing to install a third-party addon.

**Comment by T4ge** [comment]
Oh sorry, my bad. I think that would simply be an example of how it in
theory should work. However items do not have weight so it would not
exactly do anything. Merely an way of saying that Aer vis and a feather
negates weight much as if you had Thaumic Infusion infusing with water
would cause it to have water-y properties. Maybe as this have been brought
up now, we can hope to see something minor like this in the future.

2015-08-03 1:37 GMT+02:00 flarn2006 <notifications@github.com>:

**Comment by flarn2006** [comment]
So does that mean you added it? I figure if you didn't you would have posted a comment saying why you didn't want to.
