### ISSUE TITLE
Advanced Alchemical Furnace Stops Working

### ISSUE THREAD

**Issue by CaptiveCreeper** [Azanor/thaumcraft#1841]
From time to time my Advanced Alchemical Furnace does not output essentia on one or more of the output sides and i have to destroy one of the blocks of the structure and use wand again to reassemble it losing all essentia in the furnace still.  This occurs around once a day and I don't know the cause.  Any help is appreciated.  

I am using Thaumcraft version 4.3.2.5 for Minecraft 1.7.10

**Comment by justicesays** [comment]
Did you try an essentia resonator on one of the output pipes on the AAF?
It's likely this is related to #1596
