### ISSUE TITLE
Thaumcraft client 4.2.3.5 crashes on potion effects on Forge 1448

### ISSUE THREAD

**Issue by shadowc** [Azanor/thaumcraft#1844]
I'm not sure if you are aware of this issue, but it seems Thaumcraft is broken on the latest recommended forge version (forge-1.7.10-10.13.4.1448-1.7.10-universal). Every time one of my players receive a potion effect form Thaumcraft, his client crashes and he cannot log in anymore until I remove the effects from his player data file.

Crash report: https://gist.github.com/shadowc/1703f165fd2b4190be99
And: https://gist.github.com/shadowc/536c49573d58554966b5

For now Thaumcraft is unusable in my server. I'd appreciate any help (may be it's a fault on my end?).

Thanks!

**Comment by evknucklehead** [comment]
Does it happen with vanilla potion effects or effects from other mods? Does it happen with any Thaumcraft effect, or only specific ones?

I don't see anything in the crash report that specifically mentions Thaumcraft, other than it being present.

**Comment by shadowc** [comment]
It only happens with Thaumcraft. We've identified that the client crashes when the user enters one of those state of sickness due to "forbidden research".

**Comment by evknucklehead** [comment]
Okay, next question: Is there another mod that is using the same potion IDs as Thaumcraft, possibly overwriting them?

**Comment by shadowc** [comment]
Hm, how could I find that out? Can you tell by the list of mods that are present in my crash reports? May be dig Forge start up logs?

**Comment by evknucklehead** [comment]
Was in the middle of updating the above comment when you replied. Check there for the info.

**Comment by shadowc** [comment]
Thanks man! Any idea where NEI drops their files? I can't find a /dumps folder (as indicated by the log left in my chat) in the root ftp folder... I hope it's no server permissions issues, since then I'll be forced to wait for help from my hosting company :(

**Comment by shadowc** [comment]
Oh, stupid me, it's client side ... sorry

**Comment by shadowc** [comment]
Ok, so I have these 8 Thaumcraft potions in order:

24	potion.fluxtaint	thaumcraft.api.potions.PotionFluxTaint
25	potion.visexhaust	thaumcraft.api.potions.PotionVisExhaust
26	potion.infvisexhaust	thaumcraft.common.lib.potions.PotionInfectiousVisExhaust
27	potion.unhunger	thaumcraft.common.lib.potions.PotionUnnaturalHunger
28	potion.warpward	thaumcraft.common.lib.potions.PotionWarpWard
29	potion.deathgaze	thaumcraft.common.lib.potions.PotionDeathGaze
30	potion.blurred	thaumcraft.common.lib.potions.PotionBlurredVision
31	potion.sunscorned	thaumcraft.common.lib.potions.PotionSunScorned

Then a huge list of witchery potions, and the last Thaumcraft potion is on:
76	potion.thaumarhia	thaumcraft.common.lib.potions.PotionThaumarhia

Would you like me to post the entire csv file?

**Comment by evknucklehead** [comment]
No need, as that tells me that since all 9 are present, that's not where your problem is coming from. However, try to get one or more of your other server members, particularly ones that are having trouble, to give you their own dump files, to make sure they match. Normally, the configurations from the server should override the local configurations, but that might not be possible due to the way Forge allocates potion IDs.

Getting the list from the server itself would also help shed some light on whether this is the problem, but that's a bit trickier since NEI doesn't have a GUI to work with on the server. I'll see if anything in your list mod list has a way to generate the list from the server, but that will take a bit more research.

**Comment by shadowc** [comment]
Thanks, will do! Just finished a stream, so next time I join the server I will ask him!

**Comment by shadowc** [comment]
Hey, I just got a potions dump from the user that was having these issues, and his CSV file is exactly like mine... Any ideas? 

Don't want to insult coding practices or anything :) but wondering if there is any place in the code in which you might be working with potion ids instead of the potion names (not sure if it's possible). In such case a potion.id++ might return a wrong potion while looking for that 9th potion that is several ids below.

**Comment by evknucklehead** [comment]
Sorry, I'm not the coder. Didn't mean to give you that impression. I'm just a guy who likes helping people troubleshoot their problems. I've also been working on putting a mod pack together, so I've run into problems with all sorts of ID collisions between the various mods. That's how I know about how some mods are able to work around other mods' poor design choices.

That said, there is something you can try. In the witchery.cfg on the server and clients, try changing the potion at ID 32 to another ID that is open. This should let Thaumcraft realign its IDs, assuming something else doesn't swoop in. If this somehow fixes the problem (which it probably won't), then your comment about the method of identifying potion IDs would be correct and something Azanor could probably fix.

**Comment by shadowc** [comment]
Thanks for all your help, man! Apreciated! Any idea how can I contact this guy Azanor in a more direct way? I'll try tieh potion id config in the mean time.

Should this config setting be server side? Would it override client config settings? Or should I make everybody adopt a new config in their PCs?

Thanks again!

**Comment by evknucklehead** [comment]
Make the change server side then get a new dump to see if the changes propagated to the client.

As for contacting him, let's make sure it's really a Thaumcraft issue before bugging him about it, but we can usually directly reference him in a comment by putting an @ in front of his name. This tells github to send him a notification that he's been referenced in a comment.

**Comment by shadowc** [comment]
Ok, so if having all potion ids straight fixed this, the we can do the @ ritual :p I'll let you know :)
