### ISSUE TITLE
Research Problem when connecting via BungeeCord

### ISSUE THREAD

**Issue by Rearth** [Azanor/thaumcraft#1852]
So, we are using Thaumcraft 4.2.3.5. There is an unmodded Hub Server, which you join first and from this you connect to the modded Server. Since this is used this way, Thaumcraft is broken. When you scan Things, the research Points Show up, but when u go to the research table, the research points dont get added. After relogging, the same thing is scannable again. Its also not possible to pull the research Points which you have from the begin in the research field, they are just not there when you pull them there

**Comment by bookerthegeek** [comment]
I know that if you direct connect to the server  thaumcraft is not broken. The issue also exist with multiworld. 

Only because we have the same isaue
