### ISSUE TITLE
My home is in a tree, and Vertigo killed my golems

### ISSUE THREAD

**Issue by blaisen** [Azanor/thaumcraft#1854]
When the player gets struck with vertigo from warp, it removes the blocks around the player, whereupon the player falls. The blocks then reappear, preventing fall damage... ideally. I live in a Natura redwood (approximately 150 blocks tall), and when the floor vanished because of my warp-induced vertigo, my golems (which were tending to my alembics and alchemical furnaces, which, coincidentally, were also screwed up by being removed and replaced) fell to their deaths below. Is this the intended result of this warp effect?

EDIT: Just as a side note, what do you think of including in the config an option to disable Warp side effects on a case-by-case basis, rather than simply disabling warp entirely?

**Comment by MalkContent** [comment]
vertigo isn't a vanilla thaumcraft warp effect afaik

**Comment by blaisen** [comment]
My mistake!
