### ISSUE TITLE
Infusion is not working

### ISSUE THREAD

**Issue by SonicSparkleBoom** [Azanor/thaumcraft#1855]
I have the infusion set up and all the items there but when I activate it it won't use the aspects.

**Comment by forsaken1111** [comment]
Could you provide a screenshot of your setup and which item you're trying to make?

**Comment by SonicSparkleBoom** [comment]
![2015-08-23_11 28 33](https://cloud.githubusercontent.com/assets/13930569/9428846/22188418-498a-11e5-83dc-ece0ede87ffc.png)

**Comment by SonicSparkleBoom** [comment]
the hoe of growth

**Comment by forsaken1111** [comment]
Usually when an infusion won't start it means the recipe isn't recognized. Is the thaumium hoe fully repaired?

**Comment by SonicSparkleBoom** [comment]
yes

**Comment by SonicSparkleBoom** [comment]
brand new

**Comment by OJwithC** [comment]
How far away are your jars?

**Comment by SonicSparkleBoom** [comment]
I put them right next to the altar and it did nothing I even tried to start it again with them next to it and it still did nothing.

**Comment by forsaken1111** [comment]
as far as I know the ritual should activate if you have the right items even if your jars aren't nearby. Double check the items you're using are correct

**Comment by SonicSparkleBoom** [comment]
ok it was the missing aspect that was the problem it needed Meto and I had Messis however it wouldn't even take the other two for some reason.
