### ISSUE TITLE
Shovel of the Earthmover does not correctly sync in multiplayer.

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft#1857]
Using the  TC4.2.3.5 in the Direwolf20 1.3.1 pack for MC 1.7.10:-

In server games, using the shovel of the earthmover does not update other clients when adding blocks.

To replicate:
Be in a server game with other players. 
Have a goodly amount of, say, cobblestone on hand.
Place some cobblestone, and use the Shovel of the Earthmove's build function to extend a large platform.
Ask the other players if they can see anything.

**Comment by Zarzuf** [comment]
I confirm this issue: in multiplayer only the person using the shovel is able to see and break the blocks placed with the right click. All others will be unable to see and target the block and, if trying to pass through them, will be glitched in the blocks and take soffocation damage

**Comment by Azanor** [comment]
Fixed in TC 5
