### ISSUE TITLE
[Feature Request] Ability to disable aspect orbs in config

### ISSUE THREAD

**Issue by jpearson24** [Azanor/thaumcraft#1858]
Aspect orbs from mob farms are a cause of significant lag on our server (we have had upwards of 3000 orbs in one chunk at times). Being able to disable these to help with the lag that's occurring would be appreciated.

**Comment by chrisbecke** [comment]
Orbs persist for ~5s and mobs don't have all aspects typically, so if you kill one mob per second you would have ~25 orbs persisting.

So, I put it to you: kill less than 150 mobs PER SECOND to reduce your orb count.

**Comment by jpearson24** [comment]
Mob farms. Generally chunk-loaded. On a server with an excess of 20 players active at once, most with mob farms? Not exactly doable. 

The orbs don't despawn without a player present, not even with a Fake Player like a Killer Joe.

So your suggestion, while possibly accurate, isn't applicable to this situation.

**Comment by chrisbecke** [comment]
If its ok for players to chunkload mob farms on your server then you have other problems.

**Comment by jpearson24** [comment]
1. We have rules regarding spawners and farms that we police firmly.
2. A chunk-loaded mob farm, no matter how long it runs for, will NEVER produce 3000 mobs.
3. Having an entity that spawns and will not despawn unless a player is around, regardless of whether it's been used or not, is a bit silly. I haven't started Thaum yet, ergo I have no wand, yet they still disappear. Clearly they've been told to persist unless there's a player around. I don't see why we can't have an option to either disable all orbs or at the least deny persistence if no one is around.
4. When Opis is telling you there's 3000 entities in a chunk, that are all aspect orbs? Clearly this is something that needs to be changed.
5. Running the spawners themselves doesn't cause anywhere near as much lag as an excessive number of entities in the chunk. See #4.

**Comment by chrisbecke** [comment]
Well then we have a clear idea as to the actual bug report:

aspect orbs as dropped by mods don't despawn when there is no player around.

**Comment by MalkContent** [comment]
Just limit aspect orbs to drop only when killed by players, just like xp. There probably is a hook for that already.

**Comment by jpearson24** [comment]
No, there isn't.
