### ISSUE TITLE
Server crashloop with Gany's Nether

### ISSUE THREAD

**Issue by Saereth** [Azanor/thaumcraft#1861]
Seems like a strange interaction with Thaumcraft from the logs, but reporting to both mod developers.

If I change nearly any setting in the Gany's Nether config (although in this particular instance I set withershrubs to false, no other changes were made) The server hard crashes every boot until I change it back.

forge 1448, latest thaumcraft 4.2.3.5,  Gany'sNether 1.8.1

Here is the entire crashlog

http://pastebin.com/m94GqDkS

**Comment by Azanor** [comment]
You might want to report it to that mod author. Something makes my itemstacks illegal.
