### ISSUE TITLE
Crash while scanning TiC "Tool Forge (flatversion)" with Thaumometer

### ISSUE THREAD

**Issue by gilfort** [Azanor/thaumcraft#1862]
Used mods: Thaumcraft 1.7.10-4.2.3.5
Tinkers Construct 1.7.10-1.8.7

reproducable: yes

crashlog: http://pastebin.com/h1SEKULR

The games crashes when you're trying to scan the tool forge (i only know the crash for the flat version, don't know if the normal version also crashes) from TiC.

**Comment by Azanor** [comment]
Known bug. Will be fixed in TC 5
