### ISSUE TITLE
Harvest golems destroy HarvestCraft fruit tree blocks

### ISSUE THREAD

**Issue by roothorick** [Azanor/thaumcraft#1864]
TC 1.7.10-4.2.3.5 / Forge 7.10.99.99(?) / HarvestCraft 1.7.10i

The way the fruit trees in HarvestCraft work, left-clicking on a ripe fruit drops the fruit and leaves the block in place, resetting it to 0% growth.

Harvest golems are smart enough to recognize when the fruit is ripe, but when a golem harvests the fruit, the block is destroyed entirely. Order upgrade doesn't change behavior.

This poses a bit of a problem as the only way to create these blocks is to grow a whole new tree.

**Comment by Azanor** [comment]
The Harvescraft author can actually prevent this from happening by defining that the block should be clicked instead of broken via my API. You might want to go let him/her know.
