### ISSUE TITLE
Eldritch world Chunks in overworld

### ISSUE THREAD

**Issue by Darkstuffs** [Azanor/thaumcraft#1866]
While working on a server a player notified me of thaumcraft corruption
Upon investigation I encountered this

https://gyazo.com/ababf9bacbaaedfeece8dbd3fa97f202
https://gyazo.com/2f0e67d505b3ffde5eac339d17d996df

Upon looking at the blocks they stated they were the portal blocks used in the eldritch dimension
And Trying to descend into the open spaces resulted in to damage

I was able to restore the chunks with world edit

Used Thaumcraft version
4.2.3.5

**Comment by chrisbecke** [comment]
If you dump your biomes you will see that the thaumcraft biomes being found in the overworld are exactly 128 higher than an EBXL (or other biome mod) biome.
