### ISSUE TITLE
Repair Enchantment does not work, even with /enchant

### ISSUE THREAD

**Issue by MastaC729** [Azanor/thaumcraft#1868]
I have been trying to get Repair on my Goggles of Revealing for the past few days with no luck. I enchanted about 20 different googles, and none of them had Repair. I just tried using the vanilla /enchant command with the id 151 that NEI said was the registered enchantment ID for Repair. It claimed that there is no such enchantment with ID 151. Any idea on what the issue might be?

**Comment by T4ge** [comment]
I suggest that you at least go into your thaumcraft.cfg and check the ID
it's set there. (However if you are playing on a server, delete the config
and create a new one, if of course you haven't edited it before)
I'm sure someone more knowledgeable would be able to assist you if that's
not the issue.

2015-09-03 11:01 GMT+02:00 MastaC729 <notifications@github.com>:

**Comment by Azanor** [comment]
No update on this so closing.
