### ISSUE TITLE
Outer lands structures not generating

### ISSUE THREAD

**Issue by mcsnetworks** [Azanor/thaumcraft#1869]
Hello,

Having an unique issue on our server which I've spent around 10 hours researching.

Issue:  When users attempt to use the portal to the Outer lands dimension they are spawned into the correct dimension but the structure doesn't generate.

Oddity:  Our server's original world is quiet aged which appears to be part of our issue.  Deleting DIM-42 and labyrinth.dat didn't seem to fix the issue.  Deleting the entire world folder and letting everything re-generate did seem to fix the issue.  Problem is that our servers original world was started in 2011 and we can't exactly delete it and re-generate.

I've isolated this to the point where I am 100% certain it isn't another plugin / mod causing a conflict.  Thaumcraft will cause this issue by itself if it is used in combination with our old world files.

Normally I would fork the repo and work on providing a PR to resolve this issue but it appears your repo is considered private.

Myself, the senior developer of Sponge and a few others have looked into this issue and our hands are died because we cannot see a deobfuscated version of the code itself to try and solve this issue

https://www.github.com/AlmuraDev
https://www.github.com/SpongePowered/

Any information you could provide us in solving this issue would be greatly appreciated.

**Comment by TheMadmanofChaos** [comment]
The issue outlined here is caused by minor differences between how obelisks were first spawned, before the Outer lands was fully implemented, and now. Effectively, the obelisks have spawned far too close together and as a result can block each other from forming labyrinths. Using the current generation methods, the obelisks ensure enough space is put between them that this isn't an issue.

You can keep your old world, and still open portals to the outer lands, just be cautious to open the portals a few hundred blocks apart.

**Comment by mcsnetworks** [comment]
I have tried this as well.  I generated a new world of a different name and then tried to go through the portal and still it did not generate the structures.

**Comment by mcsnetworks** [comment]
FYI:  I am currently testing this generation wise between worlds by simply pulling the Portal block out of NEI's creative menu.  As long as I have new worlds I can place these portals anywhere and they all go to the intended destination with no issue.

**Comment by mcsnetworks** [comment]
Another addition is that Thaumcraft was added to this server in its current version.  Therefore all of the generated obelisks are from the latest versions of Thaumcraft.

**Comment by TheMadmanofChaos** [comment]
Try creating a new world, and opening the portal in the intended fashion(the ritual "Opening the Eye". ) I have not looked at the code myself, only going off information from old issues opened and answered by the Dev, but it may be that the "Opening" of the portal is what spawns the labyrinth and not walking through the portal.

**Comment by TheMadmanofChaos** [comment]
I did further testing in a creative world. From the looks of it, the obelisks spawning and labyrinth spawning are connected on world generation. By this I mean if an obelisk spawns in the overworld, it will spawn a labyrinth relative to it in the Outer lands. Just placing a portal where ever you like will always lead to void unless an obelisk is within a set range(Range unknown). So a normal player would never have this issue, as the only way into the outer lands is via a portal which is only made at an obelisk which should always be at a relative location to a portal inside the outer lands to drop off the player.

**Comment by mcsnetworks** [comment]
I went to a new area of the world and found an obelisk tried placing a portal right in the area it would normally go and still nothing, I still spawn in the void.

**Comment by mcsnetworks** [comment]
Ok, I did find the root cause of this and it was not Thaumcraft related.
