### ISSUE TITLE
Easy iron dupe with Iron Cap

### ISSUE THREAD

**Issue by skzskormz** [Azanor/thaumcraft#1871]
Iron Cap gives 15 metallum while its been made from 5 iron nuggets (5 metallum).
With that I can drop it with 7 iron nuggets to gather 21 nuggets back, a win of 14 nuggets and a loss of 1 metallum if im using a crucible.

**Comment by justicesays** [comment]
A base Thaumcraft iron cap has 3 metallum , something must be affecting the figure on your side. Possible something has ore-dicted iron nuggets as ingots and TC is calculating the value from a "5 ingot" recipe equivalent.

**Comment by skzskormz** [comment]
Oh, interesting, I was sure the aspects for thaumcraft items to be a fixed value from the author himself.

**Comment by Azanor** [comment]
Yeah, I think this is an oredict derp by another mod.
