### ISSUE TITLE
Permission Request

### ISSUE THREAD

**Issue by Speiger** [Azanor/thaumcraft#1872]
I am making a Mod and add a little feature to it.
Custom Decorative Signs, and my texturer made also a Thaumcraft one.
And what i want to ask can i use that in my mod?
(Just permission wise i want to be sure that i can put it in)
If you want to see one then just ask. I am not showing it here just permission wise^^

**Comment by GirafiStudios** [comment]
Just to clarify, i'm not the mod author, or anyone who can give your permissions to do anything.
But you can surely make a Thaumcraft inspired sign. As long as you don't use any textures which are exactly the same as in Thaumcraft.

**Comment by T4ge** [comment]
Seeing as it's just inspired there should be no issue. I usually just try
to fetch Azanor himself if in doubt, best chances are usually IRC. But
honestly, there should be no issues

**Comment by Speiger** [comment]
I mean when someone promotes my mod i kind of want to know what it is and have a actual choice. Thats why i am asking.

**Comment by T4ge** [comment]
Unless i misunderstood, you can use any self made texture inspired by
thaumcraft. Just don't copy paste and call it your own. Give credits where
credits are due. As long as you do that, you're good in most cases.

**Comment by Speiger** [comment]
Ok thanks
