### ISSUE TITLE
[Feature Request] Reveal all item aspects after using creative thaumonomicon

### ISSUE THREAD

**Issue by Silly511** [Azanor/thaumcraft#1876]
I have noticed that in creative worlds, after using the creative thaumonomicon to unlock all the entries, I cannot shift-hover over items to see their aspects. So what I was thinking that you could make it where when you use the creative thaumonomicon, not only does it unlock all the entries, but it also reveals the aspects of all items.

**Comment by bookerthegeek** [comment]
Not what he is looking for.

O.P. is askin that the aspect count of all items be revealed when using the creative thaumanumican. That command only revels the aspects to players, it does not tell me how much lux a torch has.

**Comment by Zsashas** [comment]
Oh ok. I thought he meant just unlocking all the aspects.

**Comment by Azanor** [comment]
Does not apply to TC5 so closing.

**Comment by Zsashas** [comment]
If you have the Thaumic Horizons add-on, the Scholar Lens slowly scans what you're looking at, automatically. It makes it s bit easier to scan stuff while doing something else.
