### ISSUE TITLE
Minefactory Reloaded Thaumcraft Compatibility Crash 

### ISSUE THREAD

**Issue by Happy4077** [Azanor/thaumcraft#1877]
I repeatedly get this crash when trying to start a new world with these two mods downloaded. I do not know why this issue arises, as there are many packs that have these two mods included. I do not have Optifine or fastcraft, but I do have BetterFPS. Here is the startup log for creating a new world: 
http://pastebin.com/hmseMuna
Mod List: http://pastebin.com/y75AE1dw
I noticed that people have reported crashes similar to this, but I am not aware of this issue ever getting fixed. I will post this on CoFH's Github as well.

**Comment by vActSwift** [comment]
I have this issue too: [FML/]: Caught exception from MineFactoryReloaded|CompatThaumcraft
Full crash logs: http://pastebin.com/2CtMLeY8

I have narrowed it down to: a combination of 6 mods + their core-mods 
Full mod list: http://pastebin.com/7qUGcgzQ

The error will always say MineFactoryReloaded|CompatThaumcraft, however removing any mod from my list will stop this error, it's the very combination of them all that cause it for me.

**Comment by RoloEdits** [comment]
I/m getting the same crash with Flaxbeards steam power.

[21:32:41] [Client thread/ERROR] [FML/]: Caught exception from Steamcraft

http://pastebin.com/ZWWaqJBc

**Comment by RoloEdits** [comment]
I also believe I had a similar problem with the Dense Ores mod from I believe RWTema, I ended up removing it.

**Comment by bookerthegeek** [comment]
One mod somewhere most likely has an outdated api. You could try on those mods only to open up and delete the thaumcraft folder.
