### ISSUE TITLE
Crimson Praetor Armor Chestplate (and some others) Not Equivalent to Diamond

### ISSUE THREAD

**Issue by Agalyon** [Azanor/thaumcraft#1878]
Most high end thaumcraft armor seems to be on par with diamond, except for the chestplate of any given set. I have read a previous issue where Azanor stated that this is intended for fortress armor because it has a hidden set bonus that does not display on the armor bar, and for void armor because of its other bonuses. 
Still, what about Crimson Praetor Armor? I don't really understand why it would be missing that one point, unless it too has a hidden set bonus. Its a colossal pain to farm, and if it doesn't have diamond equivalent, I would be very disappointed. This also leads me to ask, what exactly is the set bonus? Is it just enough to cover that one point, or does it do more, perhaps to compensate for the lack of equivalent boots? Thanks in advance.

**Comment by Azanor** [comment]
You made some good points so I will fiddle with the numbers for TC5.
