### ISSUE TITLE
Configuration request

### ISSUE THREAD

**Issue by bookerthegeek** [Azanor/thaumcraft#1883]
Hello great Azanor! I have a simple request for you (hopefully simple as I don't java).

This request is mainly for servers. Basically we have a need to be able to reset our farm/mining world on a semi regular basis. We do this to keep the Overworld in a semi pristine state.

So.. because we don't reset the overworld, and we have a world border for semi obvious reasons, I am wondering if we can change what dimension thaumcraft considers the overworld. But only for the spawning of obelisks and other world generation. ( basically anything that is required to be in the overworld to spawn). 

Not asking for more dimensions, just to change what dimension they spawn in.

This will allow us to delete the dimension on a monthly bases as we also delete the farming world monthly. 

This will also allow our players who join the server months after it started to have an equal access to end game thaumcraft.

https://github.com/Azanor/thaumcraft/issues/1870

Thank you for considering this.

**Comment by Azanor** [comment]
Its been requested before and thus I have added it to TC5. :)

**Comment by bookerthegeek** [comment]
Thank you good sir.
