### ISSUE TITLE
Overriding Request

### ISSUE THREAD

**Issue by Speiger** [Azanor/thaumcraft#1888]
Since you are no longer working on 1.7.10 Thaumcraft would you fine if i implement my Research Supporter thing with a Addon (that will override your Thaucraft Research calculation a little bit)?
I really want to support stuff with IC2 Classic but the current system do not allow support!

**Comment by Azanor** [comment]
Not sure why you felt the need to create a new issue, but sure - go ahead.

**Comment by Speiger** [comment]
I did not find the old one^^" That was the only thing^^. Thanks

**Comment by shobu9** [comment]
@Azanor  You should really come on irc
