### ISSUE TITLE
Outer Lands boss room made out of alternative, aspectless Ancient Stone

### ISSUE THREAD

**Issue by ViciousVinnyD** [Azanor/thaumcraft#1895]
The Outer Lands are normally made out of Ancient Stone, with an ID of 898:11. The boss room, however, is made out of an alternative version. This new version seems to function the same, but it does not contain any aspects. The ID for this varient is 898:13.

**Comment by Azanor** [comment]
yes?

**Comment by ViciousVinnyD** [comment]
I was just wondering, why is the boss room made out of an alternative version?

**Comment by Azanor** [comment]
The boss room version doesn't allow mobs to spawn on it.
