### ISSUE TITLE
Pickaxe of the core errors on TC ores

### ISSUE THREAD

**Issue by TheMadmanofChaos** [Azanor/thaumcraft#1896]
TC: 5.0.0
Forge: 11.14.3.1543

After using the "Sense Ore" ability of the pickaxe of the core this crash was cause, testing shows the player placed growable vis crystals were the cause.

http://pastebin.com/RQHZddPt

**Comment by Azanor** [comment]
Please report this in the TC 5 github. This one will be going away soon.
